# Generated by Django 4.2.13 on 2026-07-21 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Concern"),
                            ("attendance", "Attendance Issue"),
                            ("behavior", "Behavioral Concern"),
                            ("emotional", "Emotional / Mental Health"),
                            ("family", "Family / Home Issue"),
                            ("social", "Social / Peer Issue"),
                            ("safety", "Safety Concern"),
                            ("other", "Other"),
                        ],
                        default="academic",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("contacted", "Student Contacted"),
                            ("actioned", "Action Taken"),
                            ("closed", "Closed"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for the referral")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes and observations"
                    ),
                ),
                (
                    "intervention_plan",
                    models.TextField(
                        blank=True, help_text="Proposed intervention plan"
                    ),
                ),
                (
                    "outcome",
                    models.TextField(
                        blank=True, help_text="Outcome after action taken"
                    ),
                ),
                ("action_taken_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False,
                        help_text="Restrict visibility to counselors and admins",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Counselor assigned to handle this referral",
                        limit_choices_to={"role": "counselor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counseling_referrals_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        help_text="Teacher or admin who created the referral",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counseling_referrals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_referrals",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Referral",
                "verbose_name_plural": "Student Referrals",
                "db_table": "student_referrals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "status", "priority"],
                        name="student_ref_school__471c52_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="student_ref_assigne_3f7fc8_idx",
                    ),
                    models.Index(
                        fields=["student"], name="student_ref_student_810070_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CounselingAppointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Counseling"),
                            ("career", "Career Guidance"),
                            ("personal", "Personal / Emotional"),
                            ("behavioral", "Behavioral Intervention"),
                            ("college", "College Preparation"),
                            ("group", "Group Session"),
                            ("other", "Other"),
                        ],
                        default="academic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=30, help_text="Duration in minutes"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Room or virtual meeting link",
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the appointment"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Counselor's session notes (post-session)"
                    ),
                ),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        help_text="The counselor conducting the session",
                        limit_choices_to={"role": "counselor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_appointments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_appointments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counseling Appointment",
                "verbose_name_plural": "Counseling Appointments",
                "db_table": "counseling_appointments",
                "ordering": ["-scheduled_date", "-scheduled_time"],
                "indexes": [
                    models.Index(
                        fields=["school", "counselor", "status"],
                        name="counseling__school__10b0a0_idx",
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="counseling__student_712dce_idx",
                    ),
                    models.Index(
                        fields=["scheduled_date"], name="counseling__schedul_8d5dbe_idx"
                    ),
                ],
            },
        ),
    ]
