# Generated by Django 4.2.13 on 2026-07-22 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("counseling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "specialties",
                    models.TextField(
                        blank=True,
                        help_text="Areas of specialization, e.g. career counseling, academic advising, mental health",
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True, help_text="Professional certifications and licenses"
                    ),
                ),
                (
                    "office_hours",
                    models.TextField(
                        blank=True, help_text="Regular office hours and availability"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Professional biography"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_profiles",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Counselor Profile",
                "verbose_name_plural": "Counselor Profiles",
                "db_table": "counselor_profiles",
            },
        ),
    ]
