# Generated by Django 5.1.15 on 2026-08-31 14:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("counseling", "0002_counselor_profile"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("case_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("closed", "Closed"),
                            ("referred", "Referred"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("presenting_concerns", models.TextField(help_text="Primary concerns")),
                ("background_information", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("risk_factors", models.TextField(blank=True)),
                ("opened_date", models.DateField(auto_now_add=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("outcome_summary", models.TextField(blank=True)),
                ("is_successful", models.BooleanField(blank=True, null=True)),
                ("referral_source", models.CharField(blank=True, max_length=100)),
                ("referrals_made", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_manager",
                    models.ForeignKey(
                        limit_choices_to={"role": "counselor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_cases",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_cases",
                        to="students.student",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="case_team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Management",
                "verbose_name_plural": "Case Management",
                "db_table": "case_management",
                "ordering": ["-opened_date"],
            },
        ),
        migrations.CreateModel(
            name="CaseNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("session", "Session Note"),
                            ("phone", "Phone Call"),
                            ("email", "Email Communication"),
                            ("meeting", "Team Meeting"),
                            ("home_visit", "Home Visit"),
                            ("observation", "Observation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("is_confidential", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="counseling.casemanagement",
                    ),
                ),
            ],
            options={
                "db_table": "case_notes",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounselingReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Student Report"),
                            ("group", "Group Report"),
                            ("department", "Department Report"),
                            ("school", "School-wide Report"),
                            ("program", "Program Evaluation"),
                            ("compliance", "Compliance Report"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("final", "Final"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.TextField(blank=True)),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("total_students_served", models.PositiveIntegerField(default=0)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_referrals", models.PositiveIntegerField(default=0)),
                ("report_data", models.JSONField(blank=True, default=dict)),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="counseling/reports/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "counseling_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounselingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Session"),
                            ("group", "Group Session"),
                            ("family", "Family Session"),
                            ("crisis", "Crisis Intervention"),
                            ("follow_up", "Follow-up Session"),
                            ("assessment", "Assessment Session"),
                        ],
                        default="individual",
                        max_length=15,
                    ),
                ),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "presenting_issue",
                    models.TextField(blank=True, help_text="Primary issue discussed"),
                ),
                (
                    "session_summary",
                    models.TextField(blank=True, help_text="Summary of session content"),
                ),
                (
                    "interventions_used",
                    models.TextField(blank=True, help_text="Techniques or interventions applied"),
                ),
                (
                    "student_response",
                    models.TextField(blank=True, help_text="Student's response to interventions"),
                ),
                (
                    "risk_assessment",
                    models.TextField(blank=True, help_text="Current risk level and assessment"),
                ),
                (
                    "goals_addressed",
                    models.TextField(blank=True, help_text="Goals addressed in this session"),
                ),
                (
                    "progress_notes",
                    models.TextField(blank=True, help_text="Progress toward goals"),
                ),
                (
                    "follow_up_actions",
                    models.TextField(blank=True, help_text="Next steps and action items"),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("is_confidential", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="counseling.counselingappointment",
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        limit_choices_to={"role": "counselor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_sessions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counseling Session",
                "verbose_name_plural": "Counseling Sessions",
                "db_table": "counseling_sessions",
                "ordering": ["-session_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="CounselorAbsence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("sick", "Sick Leave"),
                            ("personal", "Personal Leave"),
                            ("pd", "Professional Development"),
                            ("conference", "Conference"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("appointments_affected", models.PositiveIntegerField(default=0)),
                ("students_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_absences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_absences",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "counselor_absences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CounselorAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "session_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of sessions available",
                        max_length=50,
                    ),
                ),
                ("max_appointments", models.PositiveIntegerField(default=5)),
                ("notes", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_availability",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counselor Availability",
                "verbose_name_plural": "Counselor Availability",
                "db_table": "counselor_availability",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CrisisIntervention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "crisis_type",
                    models.CharField(
                        choices=[
                            ("suicidal_ideation", "Suicidal Ideation"),
                            ("self_harm", "Self-Harm"),
                            ("violence", "Violence Threat"),
                            ("substance_abuse", "Substance Abuse"),
                            ("trauma", "Trauma Event"),
                            ("meltdown", "Emotional Meltdown"),
                            ("other", "Other Crisis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("stabilized", "Stabilized"),
                            ("follow_up", "Follow-up Required"),
                            ("resolved", "Resolved"),
                            ("referred", "Referred to External"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the crisis situation"),
                ),
                (
                    "immediate_actions",
                    models.TextField(blank=True, help_text="Actions taken immediately"),
                ),
                ("risk_to_self", models.BooleanField(default=False)),
                ("risk_to_others", models.BooleanField(default=False)),
                ("risk_level_assessment", models.TextField(blank=True)),
                ("response_time", models.DateTimeField(blank=True, null=True)),
                ("intervention_provided", models.TextField(blank=True)),
                ("follow_up_needed", models.BooleanField(default=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("external_referral", models.BooleanField(default=False)),
                ("external_agency", models.CharField(blank=True, max_length=200)),
                ("external_contact", models.CharField(blank=True, max_length=200)),
                ("parent_notified", models.BooleanField(default=False)),
                ("parent_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_crises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responding_counselor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_crises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crisis_interventions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crisis_interventions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crisis Intervention",
                "verbose_name_plural": "Crisis Interventions",
                "db_table": "crisis_interventions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrisisFollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("follow_up_date", models.DateField()),
                ("notes", models.TextField()),
                ("student_status", models.CharField(blank=True, max_length=50)),
                ("actions_taken", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crisis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="counseling.crisisintervention",
                    ),
                ),
            ],
            options={
                "db_table": "crisis_follow_ups",
                "ordering": ["-follow_up_date"],
            },
        ),
        migrations.CreateModel(
            name="GroupSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("social_skills", "Social Skills"),
                            ("grief", "Grief & Loss"),
                            ("anger_management", "Anger Management"),
                            ("anxiety", "Anxiety Support"),
                            ("depression", "Depression Support"),
                            ("behavioral", "Behavioral Support"),
                            ("career", "Career Exploration"),
                            ("peer_mediation", "Peer Mediation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("meeting_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "recurrence",
                    models.CharField(blank=True, help_text="e.g., Weekly, Bi-weekly", max_length=50),
                ),
                ("max_participants", models.PositiveIntegerField(default=10)),
                ("min_participants", models.PositiveIntegerField(default=3)),
                ("current_participants", models.PositiveIntegerField(default=0)),
                ("goals", models.TextField(blank=True)),
                ("curriculum", models.TextField(blank=True)),
                ("materials_needed", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        limit_choices_to={"role": "counselor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_group_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_sessions",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "group_sessions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CounselingFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("student", "Student Feedback"),
                            ("parent", "Parent Feedback"),
                            ("teacher", "Teacher Feedback"),
                        ],
                        default="student",
                        max_length=10,
                    ),
                ),
                (
                    "overall_satisfaction",
                    models.CharField(
                        choices=[
                            ("very_satisfied", "Very Satisfied"),
                            ("satisfied", "Satisfied"),
                            ("neutral", "Neutral"),
                            ("dissatisfied", "Dissatisfied"),
                            ("very_dissatisfied", "Very Dissatisfied"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "helpfulness_rating",
                    models.PositiveSmallIntegerField(default=5, help_text="Rating from 1-10"),
                ),
                (
                    "communication_rating",
                    models.PositiveSmallIntegerField(default=5, help_text="Rating from 1-10"),
                ),
                (
                    "professionalism_rating",
                    models.PositiveSmallIntegerField(default=5, help_text="Rating from 1-10"),
                ),
                ("what_went_well", models.TextField(blank=True)),
                ("areas_for_improvement", models.TextField(blank=True)),
                ("additional_comments", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(blank=True, null=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_feedback",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_feedback",
                        to="students.student",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="counseling.counselingsession",
                    ),
                ),
                (
                    "group_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="counseling.groupsession",
                    ),
                ),
            ],
            options={
                "db_table": "counseling_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupSessionAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_number", models.PositiveIntegerField(default=1)),
                ("attended_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("excused", "Excused"),
                            ("late", "Late"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="counseling.groupsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_session_attendances",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "group_session_attendances",
            },
        ),
        migrations.CreateModel(
            name="GroupSessionMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "group_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="counseling.groupsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "group_session_members",
            },
        ),
        migrations.CreateModel(
            name="InterventionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Intervention"),
                            ("behavioral", "Behavioral Intervention"),
                            ("social_emotional", "Social-Emotional"),
                            ("mental_health", "Mental Health"),
                            ("crisis", "Crisis Intervention"),
                            ("career", "Career Planning"),
                            ("other", "Other"),
                        ],
                        default="academic",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("target_end_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                (
                    "review_frequency",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Weekly, Bi-weekly, Monthly",
                        max_length=20,
                    ),
                ),
                ("last_review_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("outcome_summary", models.TextField(blank=True)),
                ("is_effective", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        limit_choices_to={"role": "counselor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_managed_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervention_plans",
                        to="counseling.studentreferral",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_plans",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_intervention_plans",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention Plan",
                "verbose_name_plural": "Intervention Plans",
                "db_table": "intervention_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterventionGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "measurable_outcome",
                    models.TextField(blank=True, help_text="How success will be measured"),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("achieved", "Achieved"),
                            ("partially_achieved", "Partially Achieved"),
                            ("not_achieved", "Not Achieved"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intervention_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="counseling.interventionplan",
                    ),
                ),
            ],
            options={
                "db_table": "intervention_goals",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CounselingOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "outcome_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Outcome"),
                            ("behavioral", "Behavioral Outcome"),
                            ("social_emotional", "Social-Emotional Outcome"),
                            ("attendance", "Attendance Outcome"),
                            ("career", "Career Outcome"),
                            ("overall", "Overall Outcome"),
                        ],
                        default="overall",
                        max_length=20,
                    ),
                ),
                ("assessment_date", models.DateField()),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("significant_improvement", "Significant Improvement"),
                            ("moderate_improvement", "Moderate Improvement"),
                            ("slight_improvement", "Slight Improvement"),
                            ("no_change", "No Change"),
                            ("decline", "Decline"),
                        ],
                        default="no_change",
                        max_length=25,
                    ),
                ),
                ("description", models.TextField(help_text="Description of outcome")),
                ("measurable_results", models.TextField(blank=True)),
                (
                    "data_sources",
                    models.TextField(blank=True, help_text="Sources of outcome data"),
                ),
                ("recommendations", models.TextField(blank=True)),
                ("continuation_needed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outcomes",
                        to="counseling.casemanagement",
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documented_outcomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_outcomes",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_outcomes",
                        to="students.student",
                    ),
                ),
                (
                    "intervention_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outcomes",
                        to="counseling.interventionplan",
                    ),
                ),
            ],
            options={
                "db_table": "counseling_outcomes",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="MentalHealthScreening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "screening_type",
                    models.CharField(
                        choices=[
                            ("phq9", "PHQ-9 (Depression)"),
                            ("gad7", "GAD-7 (Anxiety)"),
                            ("pss10", "PSS-10 (Stress)"),
                            ("audit", "AUDIT (Alcohol)"),
                            ("yrbs", "YRBS (Youth Risk)"),
                            ("sdq", "SDQ (Strengths & Difficulties)"),
                            ("custom", "Custom Screening"),
                        ],
                        max_length=15,
                    ),
                ),
                ("administered_date", models.DateField()),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("moderately_severe", "Moderately Severe"),
                            ("severe", "Severe Risk"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "interpretation",
                    models.TextField(blank=True, help_text="Professional interpretation of results"),
                ),
                ("recommendations", models.TextField(blank=True)),
                ("referral_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_completed", models.BooleanField(default=False)),
                ("consent_obtained", models.BooleanField(default=False)),
                ("consent_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="screening_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mental_health_screenings",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mental_health_screenings",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mental Health Screening",
                "verbose_name_plural": "Mental Health Screenings",
                "db_table": "mental_health_screenings",
                "ordering": ["-administered_date"],
            },
        ),
        migrations.CreateModel(
            name="ParentConsent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("general", "General Counseling"),
                            ("mental_health", "Mental Health Services"),
                            ("screening", "Mental Health Screening"),
                            ("group", "Group Counseling"),
                            ("external_referral", "External Referral"),
                            ("crisis", "Crisis Intervention"),
                            ("records_access", "Records Access"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "consent_form",
                    models.FileField(blank=True, null=True, upload_to="counseling/consent_forms/"),
                ),
                (
                    "signature",
                    models.ImageField(blank=True, null=True, upload_to="counseling/signatures/"),
                ),
                (
                    "scope_description",
                    models.TextField(blank=True, help_text="What the consent covers"),
                ),
                (
                    "restrictions",
                    models.TextField(blank=True, help_text="Any restrictions on consent"),
                ),
                ("withdrawal_date", models.DateField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_consents",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_consents",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Consent",
                "verbose_name_plural": "Parent Consents",
                "db_table": "parent_consents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("behavioral", "Behavioral"),
                            ("social", "Social"),
                            ("emotional", "Emotional"),
                            ("attendance", "Attendance"),
                            ("career", "Career"),
                            ("overall", "Overall"),
                        ],
                        default="overall",
                        max_length=15,
                    ),
                ),
                ("assessment_date", models.DateField()),
                ("current_rating", models.PositiveSmallIntegerField(default=5)),
                (
                    "previous_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "target_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                            ("fluctuating", "Fluctuating"),
                        ],
                        default="stable",
                        max_length=15,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("areas_for_growth", models.TextField(blank=True)),
                ("interventions_applied", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Teacher feedback, Test scores, Self-report",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervention_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progress_entries",
                        to="counseling.interventionplan",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_tracking",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_tracking",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress Tracking",
                "verbose_name_plural": "Progress Tracking",
                "db_table": "progress_tracking",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgressMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("achieved", models.BooleanField(default=False)),
                ("achieved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="counseling.progresstracking",
                    ),
                ),
            ],
            options={
                "db_table": "progress_milestones",
                "ordering": ["target_date"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_number", models.PositiveIntegerField()),
                ("question_text", models.TextField()),
                ("response_value", models.PositiveIntegerField(default=0)),
                ("response_text", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "screening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="counseling.mentalhealthscreening",
                    ),
                ),
            ],
            options={
                "db_table": "screening_responses",
                "ordering": ["question_number"],
            },
        ),
        migrations.CreateModel(
            name="SessionAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="counseling/sessions/attachments/"),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="counseling.counselingsession",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_attachments",
            },
        ),
        migrations.AddIndex(
            model_name="casemanagement",
            index=models.Index(
                fields=["school", "status", "priority"],
                name="case_manage_school__8a3667_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="casemanagement",
            index=models.Index(fields=["case_manager", "status"], name="case_manage_case_ma_0f4d42_idx"),
        ),
        migrations.AddIndex(
            model_name="casemanagement",
            index=models.Index(fields=["student", "status"], name="case_manage_student_97f64b_idx"),
        ),
        migrations.AddIndex(
            model_name="counselingsession",
            index=models.Index(
                fields=["school", "counselor", "session_date"],
                name="counseling__school__ddd332_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingsession",
            index=models.Index(
                fields=["student", "session_date"],
                name="counseling__student_c92ea9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crisisintervention",
            index=models.Index(
                fields=["school", "severity_level", "status"],
                name="crisis_inte_school__9483d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crisisintervention",
            index=models.Index(fields=["student", "status"], name="crisis_inte_student_2b0bc7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="groupsessionattendance",
            unique_together={("group_session", "student", "attended_date")},
        ),
        migrations.AlterUniqueTogether(
            name="groupsessionmember",
            unique_together={("group_session", "student")},
        ),
        migrations.AddIndex(
            model_name="interventionplan",
            index=models.Index(
                fields=["school", "student", "status"],
                name="interventio_school__9c8e13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interventionplan",
            index=models.Index(fields=["counselor", "status"], name="interventio_counsel_739d81_idx"),
        ),
        migrations.AddIndex(
            model_name="mentalhealthscreening",
            index=models.Index(
                fields=["school", "student", "screening_type"],
                name="mental_heal_school__109c4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mentalhealthscreening",
            index=models.Index(fields=["risk_level"], name="mental_heal_risk_le_a7808e_idx"),
        ),
        migrations.AddIndex(
            model_name="parentconsent",
            index=models.Index(
                fields=["student", "consent_type", "status"],
                name="parent_cons_student_659dbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="progresstracking",
            index=models.Index(
                fields=["student", "domain", "assessment_date"],
                name="progress_tr_student_5b9826_idx",
            ),
        ),
    ]
