# Generated by Django 5.1.15 on 2026-09-01 09:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
        ("counseling", "0003_add_counseling_gaps"),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicAdvising",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "advising_type",
                    models.CharField(
                        choices=[
                            ("course_selection", "Course Selection"),
                            ("scheduling", "Schedule Planning"),
                            ("standing", "Academic Standing Review"),
                            ("graduation", "Graduation Requirements"),
                            ("transfer", "Transfer Credit Review"),
                            ("other", "Other"),
                        ],
                        default="course_selection",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("follow_up", "Follow-up Needed"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("topics_discussed", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("courses_recommended", models.JSONField(blank=True, default=list)),
                ("courses_to_drop", models.JSONField(blank=True, default=list)),
                (
                    "current_gpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("credits_earned", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "credits_required",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "standing",
                    models.CharField(
                        blank=True,
                        help_text="Good, Academic Probation, etc.",
                        max_length=30,
                    ),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advised_students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_advising",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_academic_advising",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "academic_advising",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="BullyingReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Bullying"),
                            ("verbal", "Verbal Bullying"),
                            ("social", "Social / Relational Bullying"),
                            ("cyber", "Cyberbullying"),
                            ("sexual", "Sexual Harassment"),
                            ("racial", "Racial Harassment"),
                            ("discrimination", "Discrimination"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("severe", "Severe"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("investigating", "Under Investigation"),
                            ("confirmed", "Confirmed"),
                            ("unfounded", "Unfounded"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="reported",
                        max_length=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of bullying/harassment incident"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("date_of_incident", models.DateField(blank=True, null=True)),
                ("witnesses", models.TextField(blank=True)),
                (
                    "evidence",
                    models.TextField(blank=True, help_text="Description of any evidence"),
                ),
                ("investigation_notes", models.TextField(blank=True)),
                ("investigation_date", models.DateField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                ("actions_taken", models.TextField(blank=True)),
                ("victim_support_plan", models.TextField(blank=True)),
                ("victim_parent_notified", models.BooleanField(default=False)),
                ("perpetrator_parent_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alleged_perpetrator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bullying_alleged_reports",
                        to="students.student",
                    ),
                ),
                (
                    "counselor_assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bullying_counseling_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investigator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bullying_investigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bullying_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullying_reports",
                        to="auth_service.school",
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullying_victim_reports",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "bullying_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BullyingFollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("follow_up_date", models.DateField()),
                (
                    "participant",
                    models.CharField(help_text="Who was involved in follow-up", max_length=100),
                ),
                ("notes", models.TextField()),
                ("outcome", models.TextField(blank=True)),
                ("victim_status", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="counseling.bullyingreport",
                    ),
                ),
            ],
            options={
                "db_table": "bullying_follow_ups",
                "ordering": ["-follow_up_date"],
            },
        ),
        migrations.CreateModel(
            name="CareerAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("holland_code", "Holland Code (RIASEC)"),
                            ("mbti", "Myers-Briggs Type"),
                            ("clifton", "CliftonStrengths"),
                            ("strong", "Strong Interest Inventory"),
                            ("skills", "Skills & Aptitude Test"),
                            ("values", "Values Inventory"),
                            ("custom", "Custom Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("administered_date", models.DateField()),
                (
                    "result_summary",
                    models.TextField(blank=True, help_text="Overall result summary"),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, default=dict, help_text="Structured result data"),
                ),
                (
                    "recommended_careers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of recommended careers",
                    ),
                ),
                (
                    "recommended_fields",
                    models.JSONField(blank=True, default=list, help_text="Recommended study fields"),
                ),
                ("recommendations", models.TextField(blank=True)),
                ("counselor_notes", models.TextField(blank=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="counseling/career_assessments/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_assessments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_assessments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Career Assessment",
                "verbose_name_plural": "Career Assessments",
                "db_table": "career_assessments",
                "ordering": ["-administered_date"],
            },
        ),
        migrations.CreateModel(
            name="CareerGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "target_field",
                    models.CharField(blank=True, help_text="Target career field", max_length=100),
                ),
                ("target_university", models.CharField(blank=True, max_length=200)),
                ("target_program", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("changed", "Goal Changed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("action_steps", models.TextField(blank=True)),
                ("resources_needed", models.TextField(blank=True)),
                ("timeline", models.TextField(blank=True)),
                ("progress_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guided_career_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_goals",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_goals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "career_goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollegeApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("university_name", models.CharField(max_length=200)),
                ("program_name", models.CharField(blank=True, max_length=200)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("associate", "Associate's Degree"),
                            ("diploma", "Diploma/Certificate"),
                        ],
                        default="bachelors",
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("researching", "Researching"),
                            ("preparing", "Preparing"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                            ("enrolled", "Enrolled"),
                            ("declined", "Declined by Student"),
                        ],
                        default="researching",
                        max_length=15,
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("application_submitted_date", models.DateField(blank=True, null=True)),
                ("decision_date", models.DateField(blank=True, null=True)),
                ("enrollment_deadline", models.DateField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "scholarship_offered",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "financial_aid_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("sat_score", models.PositiveIntegerField(blank=True, null=True)),
                ("act_score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gpa_required",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("essays_completed", models.BooleanField(default=False)),
                ("letters_of_rec_sent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("counselor_recommendation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_applications",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_applications",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "College Application",
                "verbose_name_plural": "College Applications",
                "db_table": "college_applications",
                "ordering": ["application_deadline"],
            },
        ),
        migrations.CreateModel(
            name="CounselingContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("confidentiality", "Confidentiality Agreement"),
                            ("service", "Service Agreement"),
                            ("consent", "Consent for Treatment"),
                            ("release", "Information Release"),
                            ("safety", "Safety Plan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Signature"),
                            ("signed", "Signed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(help_text="Full contract/agreement text")),
                ("student_signed", models.BooleanField(default=False)),
                ("student_signed_date", models.DateField(blank=True, null=True)),
                ("parent_signed", models.BooleanField(default=False)),
                ("parent_signed_date", models.DateField(blank=True, null=True)),
                ("counselor_signed", models.BooleanField(default=False)),
                ("counselor_signed_date", models.DateField(blank=True, null=True)),
                (
                    "document_file",
                    models.FileField(blank=True, null=True, upload_to="counseling/contracts/"),
                ),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counseling_parent_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_contracts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_contracts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "counseling_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounselingGoalTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("social", "Social Skills"),
                            ("emotional", "Emotional Regulation"),
                            ("behavioral", "Behavioral"),
                            ("career", "Career Development"),
                            ("college", "College Readiness"),
                            ("wellness", "Overall Wellness"),
                        ],
                        max_length=15,
                    ),
                ),
                ("goal", models.TextField(help_text="Goal description")),
                ("measurable_criteria", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("partial", "Partially Achieved"),
                            ("ongoing", "Ongoing"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("target_date", models.DateField(blank=True, null=True)),
                ("achieved_date", models.DateField(blank=True, null=True)),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("progress_notes", models.TextField(blank=True)),
                ("barriers", models.TextField(blank=True)),
                ("support_strategies", models.TextField(blank=True)),
                ("review_dates", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_goal_tracking",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_goal_tracking",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counseling Goal Tracking",
                "verbose_name_plural": "Counseling Goal Tracking",
                "db_table": "counseling_goal_tracking",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CounselingNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appt_reminder", "Appointment Reminder"),
                            ("appt_confirmed", "Appointment Confirmed"),
                            ("appt_cancelled", "Appointment Cancelled"),
                            ("follow_up", "Follow-up Reminder"),
                            ("workshop", "Workshop Invitation"),
                            ("waitlist", "Waitlist Update"),
                            ("screening", "Screening Due"),
                            ("crisis", "Crisis Alert"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "sent_via",
                    models.CharField(blank=True, help_text="email, sms, push", max_length=50),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_notifications",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counseling_notifications",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "counseling_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounselingSessionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("viewed", "Record Viewed"),
                            ("created", "Record Created"),
                            ("edited", "Record Edited"),
                            ("shared", "Record Shared"),
                            ("exported", "Record Exported"),
                            ("deleted", "Record Deleted"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(help_text="Model type affected", max_length=50),
                ),
                (
                    "target_id",
                    models.CharField(help_text="ID of the affected record", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_session_logs",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Counseling Session Log",
                "verbose_name_plural": "Counseling Session Logs",
                "db_table": "counseling_session_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CounselingSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("satisfaction", "Satisfaction Survey"),
                            ("needs", "Needs Assessment"),
                            ("evaluation", "Program Evaluation"),
                            ("anonymous", "Anonymous Feedback"),
                            ("pre_post", "Pre/Post Assessment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("analyzed", "Analyzed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "questions",
                    models.JSONField(blank=True, default=list, help_text="List of survey questions"),
                ),
                (
                    "target_audience",
                    models.CharField(blank=True, help_text="Students, Parents, Staff", max_length=50),
                ),
                ("is_anonymous", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("results_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_surveys",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "counseling_surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounselingSurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "respondent_type",
                    models.CharField(blank=True, help_text="student, parent, staff", max_length=20),
                ),
                ("answers", models.JSONField(blank=True, default=dict)),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("comments", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counseling_survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="counseling.counselingsurvey",
                    ),
                ),
            ],
            options={
                "db_table": "counseling_survey_responses",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="CounselingWaitlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("expired", "Expired"),
                            ("removed", "Removed"),
                        ],
                        default="waiting",
                        max_length=15,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_date", models.DateField(auto_now_add=True)),
                ("contact_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preferred_counselor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduled_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="counseling.counselingappointment",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_waitlist",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_waitlist",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counseling Waitlist",
                "verbose_name_plural": "Counseling Waitlist",
                "db_table": "counseling_waitlist",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CounselingWorkshop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "workshop_type",
                    models.CharField(
                        choices=[
                            ("orientation", "Student Orientation"),
                            ("parent", "Parent Workshop"),
                            ("stress", "Stress Management"),
                            ("bullying", "Bullying Prevention"),
                            ("college_prep", "College Preparation"),
                            ("financial", "Financial Literacy"),
                            ("mental_health", "Mental Health Awareness"),
                            ("career", "Career Exploration"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("max_participants", models.PositiveIntegerField(default=30)),
                ("current_participants", models.PositiveIntegerField(default=0)),
                (
                    "target_grades",
                    models.CharField(blank=True, help_text="Comma-separated grades", max_length=100),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text="Students, Parents, Teachers",
                        max_length=50,
                    ),
                ),
                ("objectives", models.TextField(blank=True)),
                ("materials", models.TextField(blank=True)),
                ("speaker_name", models.CharField(blank=True, max_length=200)),
                ("speaker_org", models.CharField(blank=True, max_length=200)),
                (
                    "avg_satisfaction",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("total_feedback_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_workshops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_workshops",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "counseling_workshops",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CounselorCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("coverage_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "absence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="counseling.counselorabsence",
                    ),
                ),
                (
                    "absent_counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_coverage_absences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "covering_counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_coverage_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_coverages",
                        to="auth_service.school",
                    ),
                ),
                (
                    "students_covered",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coverage_sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "counselor_coverages",
                "ordering": ["coverage_date"],
            },
        ),
        migrations.CreateModel(
            name="CourseRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_code", models.CharField(max_length=20)),
                ("course_name", models.CharField(max_length=200)),
                ("semester", models.CharField(blank=True, max_length=20)),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        help_text="Required, Recommended, Optional",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advising",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_recommendations",
                        to="counseling.academicadvising",
                    ),
                ),
            ],
            options={
                "db_table": "course_recommendations",
            },
        ),
        migrations.CreateModel(
            name="ExternalReferralProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("therapist", "Therapist / Psychologist"),
                            ("psychiatrist", "Psychiatrist"),
                            ("social_worker", "Social Worker"),
                            ("community", "Community Agency"),
                            ("hospital", "Hospital / Medical"),
                            ("educational", "Educational Specialist"),
                            ("legal", "Legal Services"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("specialties", models.TextField(blank=True)),
                ("insurance_accepted", models.TextField(blank=True)),
                (
                    "referral_process",
                    models.TextField(blank=True, help_text="How to make a referral"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_referral_providers",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Referral Provider",
                "verbose_name_plural": "External Referral Providers",
                "db_table": "external_referral_providers",
            },
        ),
        migrations.CreateModel(
            name="PeerMentor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("training_completed", models.BooleanField(default=False)),
                ("training_date", models.DateField(blank=True, null=True)),
                ("specialties", models.TextField(blank=True)),
                ("max_mentees", models.PositiveIntegerField(default=3)),
                ("current_mentees", models.PositiveIntegerField(default=0)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_mentors",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_mentor_profile",
                        to="students.student",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_mentors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Peer Mentor",
                "verbose_name_plural": "Peer Mentors",
                "db_table": "peer_mentors",
            },
        ),
        migrations.CreateModel(
            name="PeerMentoringSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("session_date", models.DateField()),
                ("session_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("topics_covered", models.TextField(blank=True)),
                ("mentor_notes", models.TextField(blank=True)),
                ("mentee_feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_mentoring_sessions",
                        to="students.student",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="counseling.peermentor",
                    ),
                ),
            ],
            options={
                "db_table": "peer_mentoring_sessions",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="ReferralTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Referral Initiated"),
                            ("confirmed", "Appointment Confirmed"),
                            ("attended", "Student Attended"),
                            ("ongoing", "Ongoing Treatment"),
                            ("completed", "Treatment Completed"),
                            ("lost", "Lost to Follow-up"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("referral_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("outcome_notes", models.TextField(blank=True)),
                ("parent_consent", models.BooleanField(default=False)),
                ("parent_contacted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="counseling.externalreferralprovider",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_tracking",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_tracking",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "referral_tracking",
                "ordering": ["-referral_date"],
            },
        ),
        migrations.CreateModel(
            name="RestorativeJusticeSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("circle", "Restorative Circle"),
                            ("conference", "Restorative Conference"),
                            ("mediation", "Peer Mediation"),
                            ("dialogue", "Restorative Dialogue"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("participant_count", models.PositiveIntegerField(default=0)),
                ("incident_description", models.TextField(blank=True)),
                ("harm_caused", models.TextField(blank=True)),
                ("needs_identified", models.TextField(blank=True)),
                ("agreements", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolution", "Resolution Reached"),
                            ("partial", "Partial Resolution"),
                            ("no_resolution", "No Resolution"),
                            ("referred", "Referred"),
                        ],
                        max_length=20,
                    ),
                ),
                ("outcome_notes", models.TextField(blank=True)),
                ("agreements_met", models.BooleanField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restorative_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restorative_facilitated_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(related_name="restorative_sessions", to="students.student"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restorative_sessions",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "restorative_justice_sessions",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="RestorativeCommitment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "commitment",
                    models.TextField(help_text="What the student committed to"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restorative_commitments",
                        to="students.student",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="counseling.restorativejusticesession",
                    ),
                ),
            ],
            options={
                "db_table": "restorative_commitments",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="SELAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("self_awareness", "Self-Awareness"),
                            ("self_management", "Self-Management"),
                            ("social_awareness", "Social Awareness"),
                            ("relationship", "Relationship Skills"),
                            ("decisions", "Responsible Decision-Making"),
                            ("overall", "Overall SEL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assessment_date", models.DateField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("strength_areas", models.TextField(blank=True)),
                ("growth_areas", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("intervention_suggested", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_assessments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_assessments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "sel_assessments",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="SELGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("self_awareness", "Self-Awareness"),
                            ("self_management", "Self-Management"),
                            ("social_awareness", "Social Awareness"),
                            ("relationship", "Relationship Skills"),
                            ("decisions", "Responsible Decision-Making"),
                            ("overall", "Overall SEL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("goal_description", models.TextField()),
                ("measurable_outcome", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("target_date", models.DateField(blank=True, null=True)),
                ("achieved_date", models.DateField(blank=True, null=True)),
                ("strategies", models.TextField(blank=True)),
                ("progress_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sel_goals_guided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_goals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "sel_goals",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SpecialEducationReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "referral_type",
                    models.CharField(
                        choices=[
                            ("iep", "IEP Evaluation"),
                            ("504", "504 Plan"),
                            ("gifted", "Gifted/Talented"),
                            ("ld", "Learning Disability"),
                            ("adhd", "ADHD Accommodation"),
                            ("autism", "Autism Spectrum"),
                            ("emotional", "Emotional/Behavioral"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Referral Initiated"),
                            ("eval_scheduled", "Evaluation Scheduled"),
                            ("evaluating", "Under Evaluation"),
                            ("eligible", "Found Eligible"),
                            ("not_eligible", "Not Eligible"),
                            ("iep_created", "IEP/504 Created"),
                            ("in_progress", "Active Plan"),
                            ("review", "Under Review"),
                            ("closed", "Closed"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for referral")),
                ("supporting_data", models.TextField(blank=True)),
                ("evaluation_date", models.DateField(blank=True, null=True)),
                ("evaluation_results", models.TextField(blank=True)),
                (
                    "plan_type",
                    models.CharField(blank=True, help_text="IEP, 504, etc.", max_length=20),
                ),
                ("plan_created_date", models.DateField(blank=True, null=True)),
                ("plan_review_date", models.DateField(blank=True, null=True)),
                ("parent_consent", models.BooleanField(default=False)),
                ("parent_consent_date", models.DateField(blank=True, null=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="counseling/spec_ed/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spec_ed_referrals_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_ed_referrals",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_ed_referrals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Education Referral",
                "verbose_name_plural": "Special Education Referrals",
                "db_table": "special_education_referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=15,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("attended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback_rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                ("feedback_comments", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshop_registrations",
                        to="students.student",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="counseling.counselingworkshop",
                    ),
                ),
            ],
            options={
                "db_table": "workshop_registrations",
            },
        ),
        migrations.AddIndex(
            model_name="academicadvising",
            index=models.Index(
                fields=["student", "advising_type"],
                name="academic_ad_student_30ddac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bullyingreport",
            index=models.Index(
                fields=["school", "status", "severity"],
                name="bullying_re_school__2d15de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bullyingreport",
            index=models.Index(fields=["victim", "status"], name="bullying_re_victim__2c4157_idx"),
        ),
        migrations.AddIndex(
            model_name="careerassessment",
            index=models.Index(fields=["school", "student"], name="career_asse_school__43788e_idx"),
        ),
        migrations.AddIndex(
            model_name="collegeapplication",
            index=models.Index(fields=["student", "status"], name="college_app_student_fc9ae9_idx"),
        ),
        migrations.AddIndex(
            model_name="counselingcontract",
            index=models.Index(
                fields=["student", "contract_type"],
                name="counseling__student_3ac947_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselinggoaltracking",
            index=models.Index(
                fields=["student", "domain", "status"],
                name="counseling__student_1a99c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingnotification",
            index=models.Index(fields=["recipient", "is_read"], name="counseling__recipie_ad9c89_idx"),
        ),
        migrations.AddIndex(
            model_name="counselingsessionlog",
            index=models.Index(fields=["user", "action"], name="counseling__user_id_e94db1_idx"),
        ),
        migrations.AddIndex(
            model_name="counselingsessionlog",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="counseling__target__2bb6a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="referraltracking",
            index=models.Index(fields=["student", "status"], name="referral_tr_student_b353b1_idx"),
        ),
        migrations.AddIndex(
            model_name="selassessment",
            index=models.Index(fields=["student", "domain"], name="sel_assessm_student_395594_idx"),
        ),
        migrations.AddIndex(
            model_name="specialeducationreferral",
            index=models.Index(
                fields=["student", "referral_type"],
                name="special_edu_student_c63074_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="specialeducationreferral",
            index=models.Index(fields=["school", "status"], name="special_edu_school__041a5a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="workshopregistration",
            unique_together={("workshop", "student")},
        ),
    ]
