# Generated by Django 4.2.13 on 2026-07-02 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_attendance",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="students.classroom",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="attendanceleave",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_leaves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendanceleave",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaves",
                to="students.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="periodattendance",
            unique_together={("student", "assignment", "date", "period_number")},
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["classroom", "date"], name="attendance__classro_7ca9b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["student", "academic_year"],
                name="attendance__student_b43f88_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("student", "date")},
        ),
    ]
