# Generated by Django 5.2.17 on 2026-08-17 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_initial"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["classroom", "academic_year", "date"],
                name="attendance__classro_585b61_idx",
            ),
        ),
    ]
