# Generated by Django 5.2.17 on 2026-08-27 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_teacherprofile_bio"),
        ("attendance", "0005_add_audit_trail_and_changelog"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCodeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "period_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("qr_code", models.CharField(max_length=255, unique=True)),
                ("secret_key", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.classroom",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qr_code_sessions",
            },
        ),
        migrations.CreateModel(
            name="AttendanceDataArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archive_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("period", "Period")],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(help_text="Archived attendance records")),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_purged",
                    models.BooleanField(default=False, help_text="Original data has been purged"),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_data_archives",
                "indexes": [
                    models.Index(
                        fields=["school", "academic_year"],
                        name="attendance__school__1bb6d4_idx",
                    ),
                    models.Index(fields=["-archived_at"], name="attendance__archive_e0207a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Policy", max_length=100)),
                (
                    "min_attendance_pct",
                    models.DecimalField(decimal_places=2, default=75.0, max_digits=5),
                ),
                ("auto_fail_below", models.BooleanField(default=True)),
                (
                    "notify_parent_below_pct",
                    models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
                ),
                (
                    "notify_admin_below_pct",
                    models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
                ),
                ("edit_window_days", models.PositiveIntegerField(default=7)),
                (
                    "reminder_time",
                    models.TimeField(
                        default="10:00",
                        help_text="Time to remind teachers to record attendance",
                    ),
                ),
                ("escalation_enabled", models.BooleanField(default=True)),
                (
                    "escalation_after_minutes",
                    models.PositiveIntegerField(default=60, help_text="Minutes after reminder to escalate"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_policies",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_policies",
                "unique_together": {("school", "is_active")},
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("public", "Public Holiday"),
                            ("school", "School Holiday"),
                            ("exam", "Exam Holiday"),
                            ("vacation", "Vacation"),
                        ],
                        default="school",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "holidays",
                "ordering": ["date"],
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="LeaveApprovalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(help_text="Approval level (1=Teacher, 2=HOD, 3=Principal)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_levels",
                        to="attendance.attendanceleave",
                    ),
                ),
            ],
            options={
                "db_table": "leave_approval_levels",
                "ordering": ["level"],
                "unique_together": {("leave", "level")},
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sick_leave_total", models.PositiveIntegerField(default=10)),
                ("sick_leave_used", models.PositiveIntegerField(default=0)),
                ("casual_leave_total", models.PositiveIntegerField(default=5)),
                ("casual_leave_used", models.PositiveIntegerField(default=0)),
                ("other_leave_total", models.PositiveIntegerField(default=5)),
                ("other_leave_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "leave_balances",
                "unique_together": {("student", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="QRCodeCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="attendance.qrcodesession",
                    ),
                ),
            ],
            options={
                "db_table": "qr_code_checkins",
                "unique_together": {("session", "student")},
            },
        ),
        migrations.CreateModel(
            name="SubstituteTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "period_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("is_auto_assigned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.classroom",
                    ),
                ),
                (
                    "original_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_original",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
                (
                    "substitute_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "substitute_teachers",
                "unique_together": {("date", "period_number", "classroom")},
            },
        ),
    ]
