# Generated by Django 5.1.15 on 2026-08-31 11:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_versioning_and_course_catalog"),
        (
            "attendance",
            "0006_qrcodesession_attendancedataarchive_attendancepolicy_and_more",
        ),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCorrectionWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("status_change", "Status Change"),
                            ("time_change", "Time Change"),
                            ("add_record", "Add Record"),
                            ("delete_record", "Delete Record"),
                            ("bulk_update", "Bulk Update"),
                        ],
                        max_length=15,
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=1)),
                ("new_status", models.CharField(max_length=1)),
                ("old_time", models.DateTimeField(blank=True, null=True)),
                ("new_time", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "supporting_document",
                    models.FileField(blank=True, null=True, upload_to="attendance/corrections/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("auto_approved", "Auto-Approved"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "period_attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="attendance.periodattendance",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_attendance_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_attendance_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_corrections",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_corrections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("school", "School-wide"),
                            ("grade", "Grade Level"),
                            ("classroom", "Classroom"),
                            ("student", "Student"),
                            ("teacher", "Teacher"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_students", models.PositiveIntegerField(default=0)),
                (
                    "average_attendance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("present_count", models.PositiveIntegerField(default=0)),
                ("absent_count", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("excused_count", models.PositiveIntegerField(default=0)),
                ("attendance_trend", models.JSONField(blank=True, default=list)),
                ("daily_breakdown", models.JSONField(blank=True, default=dict)),
                ("chronic_absence_count", models.PositiveIntegerField(default=0)),
                ("at_risk_count", models.PositiveIntegerField(default=0)),
                ("chart_data", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_attendance_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_dashboards",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_dashboards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendancePatterns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("weekday", "Weekday Pattern"),
                            ("monthly", "Monthly Pattern"),
                            ("seasonal", "Seasonal Pattern"),
                            ("consecutive", "Consecutive Absences"),
                            ("before_after_break", "Before/After Break"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pattern_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.PositiveIntegerField(default=0, help_text="Number of occurrences"),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pattern_data", models.JSONField(blank=True, default=dict)),
                ("affected_dates", models.JSONField(blank=True, default=list)),
                ("intervention_recommended", models.BooleanField(default=False)),
                ("intervention_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_patterns",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_patterns",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_patterns",
                "ordering": ["-percentage"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Report"),
                            ("weekly", "Weekly Report"),
                            ("monthly", "Monthly Report"),
                            ("term", "Term Report"),
                            ("annual", "Annual Report"),
                            ("custom", "Custom Range"),
                            ("student", "Student Report"),
                            ("class", "Class Report"),
                            ("chronic", "Chronic Absence Report"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_students", models.PositiveIntegerField(default=0)),
                (
                    "average_attendance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("present_count", models.PositiveIntegerField(default=0)),
                ("absent_count", models.PositiveIntegerField(default=0)),
                ("late_count", models.PositiveIntegerField(default=0)),
                ("excused_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("report_url", models.URLField(blank=True)),
                (
                    "file_size_mb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("sent_to", models.JSONField(blank=True, default=list)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.classroom",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_attendance_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_reports",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BiometricCheckin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "biometric_type",
                    models.CharField(
                        choices=[
                            ("fingerprint", "Fingerprint"),
                            ("face", "Face Recognition"),
                            ("iris", "Iris Scan"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Biometric device identifier",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("denied", "Access Denied"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Recognition confidence (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                ("checkin_time", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_checkins",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_checkins",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_biometric_checkins",
                "ordering": ["-checkin_time"],
            },
        ),
        migrations.CreateModel(
            name="BulkAttendanceImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("successful_records", models.PositiveIntegerField(default=0)),
                ("failed_records", models.PositiveIntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("date_column", models.CharField(default="date", max_length=50)),
                (
                    "student_column",
                    models.CharField(default="student_id", max_length=50),
                ),
                ("status_column", models.CharField(default="status", max_length=50)),
                ("overwrite_existing", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_attendance_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_attendance_imports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_bulk_imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GPSAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "accuracy_meters",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("geofence_name", models.CharField(blank=True, max_length=100)),
                (
                    "geofence_radius",
                    models.PositiveIntegerField(default=100, help_text="Geofence radius in meters"),
                ),
                (
                    "distance_from_school",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("out_of_range", "Out of Range"),
                            ("pending", "Pending Verification"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("checkin_time", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_attendance",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_attendance",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_gps",
                "ordering": ["-checkin_time"],
            },
        ),
        migrations.CreateModel(
            name="ParentNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("absence", "Absence Alert"),
                            ("late", "Late Arrival"),
                            ("early_departure", "Early Departure"),
                            ("chronic", "Chronic Absence"),
                            ("pattern", "Attendance Pattern"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("all", "All Channels"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("parent_email", models.EmailField(blank=True, max_length=254)),
                ("parent_phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_notifications",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_notifications",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_parent_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("school", "School-wide"),
                            ("grade", "Grade Level"),
                            ("classroom", "Classroom"),
                            ("bus", "Bus Route"),
                            ("dormitory", "Dormitory"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "scope_id",
                    models.CharField(blank=True, help_text="ID of grade/classroom/bus", max_length=50),
                ),
                ("total_expected", models.PositiveIntegerField(default=0)),
                ("total_present", models.PositiveIntegerField(default=0)),
                ("total_absent", models.PositiveIntegerField(default=0)),
                ("total_late", models.PositiveIntegerField(default=0)),
                ("total_excused", models.PositiveIntegerField(default=0)),
                ("total_early_departure", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("live_checkins", models.JSONField(blank=True, default=list)),
                ("recent_alerts", models.JSONField(blank=True, default=list)),
                ("last_refreshed", models.DateTimeField(auto_now=True)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=30)),
                ("auto_refresh", models.BooleanField(default=True)),
                ("show_names", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtime_dashboards",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_realtime_dashboards",
                "ordering": ["-last_refreshed"],
            },
        ),
        migrations.CreateModel(
            name="RFIDCheckin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_number", models.CharField(max_length=50)),
                (
                    "reader_id",
                    models.CharField(blank=True, help_text="RFID reader device ID", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("denied", "Access Denied"),
                            ("lost", "Lost Card"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                ("checkin_time", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfid_checkins",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfid_checkins",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_rfid_checkins",
                "ordering": ["-checkin_time"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceHistoryView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_days", models.PositiveIntegerField(default=0)),
                ("days_present", models.PositiveIntegerField(default=0)),
                ("days_absent", models.PositiveIntegerField(default=0)),
                ("days_late", models.PositiveIntegerField(default=0)),
                ("days_excused", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "timeline_data",
                    models.JSONField(blank=True, default=list, help_text="Daily attendance timeline"),
                ),
                ("monthly_trend", models.JSONField(blank=True, default=list)),
                ("weekday_trend", models.JSONField(blank=True, default=dict)),
                (
                    "current_streak",
                    models.PositiveIntegerField(default=0, help_text="Consecutive present days"),
                ),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_history",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.academicterm",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_history_views",
                "ordering": ["-academic_year"],
                "unique_together": {("student", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="ChronicAbsenceTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_days", models.PositiveIntegerField(default=0)),
                ("days_present", models.PositiveIntegerField(default=0)),
                ("days_absent", models.PositiveIntegerField(default=0)),
                ("days_late", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "absence_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("watch", "Watch (5-10%)"),
                            ("warning", "Warning (10-15%)"),
                            ("concern", "Concerning (15-20%)"),
                            ("critical", "Critical (>20%)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("improving", "Improving"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("intervention_plan", models.TextField(blank=True)),
                ("intervention_start_date", models.DateField(blank=True, null=True)),
                ("intervention_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("admin_notified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chronic_absence_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chronic_absence_tracking",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chronic_absence_tracking",
                        to="students.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.academicterm",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_chronic_absence",
                "ordering": ["-absence_percentage"],
                "unique_together": {("student", "academic_year")},
            },
        ),
    ]
