# Generated by Django 5.1.15 on 2026-09-01 09:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0007_attendancecorrectionworkflow_attendancedashboard_and_more",
        ),
        ("auth_service", "0006_add_auth_gap_models"),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceAlertConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "absence_threshold",
                    models.PositiveIntegerField(default=3, help_text="Number of absences to trigger"),
                ),
                (
                    "tardy_threshold",
                    models.PositiveIntegerField(default=5, help_text="Number of tardies to trigger"),
                ),
                (
                    "lookback_days",
                    models.PositiveIntegerField(default=30, help_text="Look-back window in days"),
                ),
                (
                    "consecutive_absences",
                    models.BooleanField(default=False, help_text="Alert on consecutive absences"),
                ),
                ("consecutive_count", models.PositiveIntegerField(default=3)),
                ("notify_parent", models.BooleanField(default=True)),
                ("notify_counselor", models.BooleanField(default=False)),
                ("notify_admin", models.BooleanField(default=False)),
                ("notify_teacher", models.BooleanField(default=False)),
                ("email_template", models.TextField(blank=True)),
                ("sms_template", models.TextField(blank=True)),
                (
                    "max_alerts_per_student",
                    models.PositiveIntegerField(default=3, help_text="Max alerts per student per period"),
                ),
                (
                    "cooldown_days",
                    models.PositiveIntegerField(default=7, help_text="Days between repeated alerts"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alert_configs",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_alert_configs",
            },
        ),
        migrations.CreateModel(
            name="AttendanceConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attendance_mode",
                    models.CharField(
                        choices=[
                            ("class_period", "Class Period Attendance"),
                            ("daily", "Daily Attendance"),
                            ("both", "Both Period and Daily"),
                        ],
                        default="both",
                        max_length=15,
                    ),
                ),
                (
                    "check_in_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("qr", "QR Code"),
                            ("biometric", "Biometric"),
                            ("rfid", "RFID"),
                            ("gps", "GPS/Geofence"),
                            ("app", "Mobile App"),
                        ],
                        default="manual",
                        max_length=15,
                    ),
                ),
                (
                    "grace_period_minutes",
                    models.PositiveIntegerField(default=5, help_text="Minutes after period starts"),
                ),
                (
                    "tardy_threshold_minutes",
                    models.PositiveIntegerField(default=10, help_text="Minutes to mark as tardy"),
                ),
                (
                    "absent_threshold_minutes",
                    models.PositiveIntegerField(default=30, help_text="Minutes to mark as absent"),
                ),
                (
                    "early_departure_threshold_minutes",
                    models.PositiveIntegerField(default=15, help_text="Minutes before end to count as early"),
                ),
                ("auto_notify_absent", models.BooleanField(default=True)),
                ("auto_notify_tardy", models.BooleanField(default=False)),
                ("notify_after_minutes", models.PositiveIntegerField(default=30)),
                ("parent_portal_enabled", models.BooleanField(default=True)),
                ("parent_real_time_view", models.BooleanField(default=False)),
                ("auto_apply_holidays", models.BooleanField(default=True)),
                ("school_start_time", models.TimeField(default="08:00")),
                ("school_end_time", models.TimeField(default="15:00")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_config",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Configuration",
                "verbose_name_plural": "Attendance Configurations",
                "db_table": "attendance_configurations",
            },
        ),
        migrations.CreateModel(
            name="AttendanceIncentive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "incentive_type",
                    models.CharField(
                        choices=[
                            ("points", "Attendance Points"),
                            ("badge", "Achievement Badge"),
                            ("certificate", "Certificate"),
                            ("prize", "Physical Prize"),
                            ("recognition", "Public Recognition"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "required_streak_days",
                    models.PositiveIntegerField(default=30, help_text="Consecutive days required"),
                ),
                (
                    "required_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=95,
                        help_text="Min attendance %",
                        max_digits=5,
                    ),
                ),
                ("points_value", models.PositiveIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "total_available",
                    models.PositiveIntegerField(blank=True, help_text="Total available awards", null=True),
                ),
                ("total_awarded", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_incentives",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_incentives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceMakeUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("excused", "Excused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("make_up_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("reason", models.TextField(blank=True)),
                (
                    "hours_completed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "hours_required",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_absence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_makeups",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_makeups",
                        to="students.student",
                    ),
                ),
                (
                    "supervised_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="makeup_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_makeups",
                "ordering": ["-make_up_date"],
            },
        ),
        migrations.CreateModel(
            name="FieldTrip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("destination", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("approved", "Approved"),
                            ("active", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=15,
                    ),
                ),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("return_time", models.TimeField(blank=True, null=True)),
                ("eligible_grades", models.CharField(blank=True, max_length=100)),
                ("max_participants", models.PositiveIntegerField(default=50)),
                (
                    "cost_per_student",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("transportation", models.CharField(blank=True, max_length=200)),
                ("consent_required", models.BooleanField(default=True)),
                ("consent_deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chaperones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="chaperoned_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_trips",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "field_trips",
                "ordering": ["-departure_date"],
            },
        ),
        migrations.CreateModel(
            name="TardyPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "tardy_count",
                    models.PositiveIntegerField(help_text="Number of tardies this policy applies to"),
                ),
                (
                    "consequence",
                    models.TextField(help_text="Consequence for this number of tardies"),
                ),
                ("notify_parent", models.BooleanField(default=True)),
                ("detention_minutes", models.PositiveIntegerField(default=0)),
                ("in_school_suspension", models.BooleanField(default=False)),
                ("warning_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tardy_policies",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "tardy_policies",
                "ordering": ["tardy_count"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceAuditEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("check_in", "Check In"),
                            ("check_out", "Check Out"),
                            ("status_change", "Status Change"),
                            ("manual_override", "Manual Override"),
                            ("bulk_import", "Bulk Import"),
                            ("correction", "Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=15)),
                ("new_status", models.CharField(blank=True, max_length=15)),
                ("old_time", models.TimeField(blank=True, null=True)),
                ("new_time", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("change_date", models.DateField()),
                ("change_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="System, Manual, QR, Biometric, RFID, etc.",
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_audit_entries",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_audit_entries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Audit Entry",
                "verbose_name_plural": "Attendance Audit Entries",
                "db_table": "attendance_audit_entries",
                "ordering": ["-change_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["student", "change_date"],
                        name="attendance__student_51f654_idx",
                    ),
                    models.Index(
                        fields=["school", "change_type"],
                        name="attendance__school__c8d73f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive Note"),
                            ("concern", "Concern"),
                            ("intervention", "Intervention Note"),
                            ("parent_comm", "Parent Communication"),
                            ("general", "General Note"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField()),
                ("comment_date", models.DateField(auto_now_add=True)),
                ("related_date", models.DateField(blank=True, null=True)),
                ("is_visible_to_parent", models.BooleanField(default=True)),
                ("is_visible_to_student", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_comments_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_comments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_comments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_comments",
                "ordering": ["-comment_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "comment_type"],
                        name="attendance__student_fb8666_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceEscalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "escalation_level",
                    models.CharField(
                        choices=[
                            ("level_1", "Level 1 — Notification"),
                            ("level_2", "Level 2 — Meeting"),
                            ("level_3", "Level 3 — Intervention"),
                            ("level_4", "Level 4 — Administrative Action"),
                            ("level_5", "Level 5 — Legal/DCFS"),
                        ],
                        default="level_1",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("triggered", "Triggered"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated Further"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "trigger_reason",
                    models.TextField(help_text="Why this escalation was triggered"),
                ),
                ("absences_count", models.PositiveIntegerField(default=0)),
                ("tardies_count", models.PositiveIntegerField(default=0)),
                ("actions_taken", models.TextField(blank=True)),
                ("meeting_date", models.DateField(blank=True, null=True)),
                ("meeting_notes", models.TextField(blank=True)),
                ("parent_contacted", models.BooleanField(default=False)),
                ("parent_meeting_date", models.DateField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_escalations",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_escalations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_escalations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "escalation_level"],
                        name="attendance__student_4bbdef_idx",
                    ),
                    models.Index(
                        fields=["school", "status"],
                        name="attendance__school__32656b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceIncentiveAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("awarded_date", models.DateField(auto_now_add=True)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("points_earned", models.PositiveIntegerField(default=0)),
                (
                    "total_points",
                    models.PositiveIntegerField(default=0, help_text="Running total"),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incentive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="attendance.attendanceincentive",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_awards",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_incentive_awards",
                "ordering": ["-awarded_date"],
                "unique_together": {("incentive", "student")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceLockout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lock_date", models.DateField()),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text="Specific period or blank for all-day",
                        max_length=50,
                    ),
                ),
                ("lock_reason", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=True)),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_reason", models.TextField(blank=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_lockouts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_unlocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_lockouts",
                "ordering": ["-lock_date"],
                "unique_together": {("school", "lock_date", "period")},
            },
        ),
        migrations.CreateModel(
            name="AttendancePrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("absence", "Absence Risk"),
                            ("chronic", "Chronic Absence Risk"),
                            ("late", "Late Arrival Risk"),
                            ("drop", "Enrollment Drop Risk"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=2, help_text="0-100 risk score", max_digits=5),
                ),
                ("prediction_date", models.DateField()),
                ("predicted_period_start", models.DateField()),
                ("predicted_period_end", models.DateField()),
                (
                    "risk_factors",
                    models.JSONField(blank=True, default=list, help_text="Contributing risk factors"),
                ),
                ("historical_pattern", models.TextField(blank=True)),
                ("recommended_action", models.TextField(blank=True)),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("action_taken", models.TextField(blank=True)),
                ("actual_outcome", models.CharField(blank=True, max_length=20)),
                ("was_accurate", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_predictions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_predictions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_predictions",
                "ordering": ["-risk_score"],
                "indexes": [
                    models.Index(
                        fields=["student", "prediction_type"],
                        name="attendance__student_ee582c_idx",
                    ),
                    models.Index(
                        fields=["school", "risk_score"],
                        name="attendance__school__1f553a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EarlyDismissal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical Appointment"),
                            ("dental", "Dental Appointment"),
                            ("family", "Family Event"),
                            ("religious", "Religious Observance"),
                            ("personal", "Personal Reason"),
                            ("bus", "Early Bus"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("dismissal_date", models.DateField()),
                ("requested_departure_time", models.TimeField()),
                ("actual_departure_time", models.TimeField(blank=True, null=True)),
                ("reason_detail", models.TextField(blank=True)),
                (
                    "pickup_person",
                    models.CharField(
                        blank=True,
                        help_text="Who is picking up the student",
                        max_length=200,
                    ),
                ),
                ("pickup_id_verified", models.BooleanField(default=False)),
                ("approval_notes", models.TextField(blank=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="early_dismissal_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="early_dismissal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="early_dismissals",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="early_dismissals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "early_dismissals",
                "ordering": ["-dismissal_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "dismissal_date"],
                        name="early_dismi_student_84fb05_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FieldTripParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_status",
                    models.CharField(
                        choices=[
                            ("pending", "Consent Pending"),
                            ("granted", "Consent Granted"),
                            ("denied", "Consent Denied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("attended", "Attended"),
                            ("absent", "Absent"),
                            ("excused", "Excused"),
                        ],
                        default="enrolled",
                        max_length=10,
                    ),
                ),
                ("parent_contacted", models.BooleanField(default=False)),
                ("payment_status", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field_trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="attendance.fieldtrip",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_trip_participations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "field_trip_participants",
                "unique_together": {("field_trip", "student")},
            },
        ),
        migrations.CreateModel(
            name="StudentAttendanceSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=10)),
                ("semester", models.CharField(blank=True, max_length=10)),
                ("total_school_days", models.PositiveIntegerField(default=0)),
                ("days_present", models.PositiveIntegerField(default=0)),
                ("days_absent", models.PositiveIntegerField(default=0)),
                ("days_late", models.PositiveIntegerField(default=0)),
                ("days_excused", models.PositiveIntegerField(default=0)),
                ("days_early_departure", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tardiness_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("longest_present_streak", models.PositiveIntegerField(default=0)),
                ("current_present_streak", models.PositiveIntegerField(default=0)),
                ("longest_absent_streak", models.PositiveIntegerField(default=0)),
                ("subject_attendance", models.JSONField(blank=True, default=dict)),
                ("is_chronic_absentee", models.BooleanField(default=False)),
                ("is_honor_roll_eligible", models.BooleanField(default=True)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendance_summaries",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_attendance_summaries",
                "ordering": ["-academic_year", "-semester"],
                "unique_together": {("student", "academic_year", "semester")},
            },
        ),
        migrations.CreateModel(
            name="TardyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tardy_date", models.DateField()),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("minutes_late", models.PositiveIntegerField(default=0)),
                ("reason", models.TextField(blank=True)),
                ("excuse", models.CharField(blank=True, max_length=200)),
                ("consequence", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded"),
                            ("notified", "Parent Notified"),
                            ("consequence", "Consequence Applied"),
                            ("resolved", "Resolved"),
                        ],
                        default="recorded",
                        max_length=15,
                    ),
                ),
                ("parent_notified", models.BooleanField(default=False)),
                ("detention_served", models.BooleanField(default=False)),
                (
                    "total_tardies",
                    models.PositiveIntegerField(default=1, help_text="Running total for the year"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "policy_applied",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.tardypolicy",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tardy_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "tardy_records",
                "ordering": ["-tardy_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "tardy_date"],
                        name="tardy_recor_student_ed77b7_idx",
                    )
                ],
            },
        ),
    ]
