# Generated by Django 5.2.17 on 2026-08-10 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0002_initial"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "marks_obtained_old",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "marks_obtained_new",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("is_absent_old", models.BooleanField(null=True)),
                ("is_absent_new", models.BooleanField(null=True)),
                ("remarks_old", models.CharField(blank=True, max_length=255)),
                ("remarks_new", models.CharField(blank=True, max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_change_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_change_logs",
                        to="gradebook.examschedule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_change_logs",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "grade_change_logs",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "exam_schedule"],
                        name="grade_chang_student_4c4dc9_idx",
                    ),
                    models.Index(fields=["changed_by"], name="grade_chang_changed_c7f351_idx"),
                ],
            },
        ),
    ]
