# Generated by Django 5.2.17 on 2026-08-11 02:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0003_gradechangelog"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeChangeProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "marks_obtained_new",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("is_absent_new", models.BooleanField(null=True)),
                ("remarks_new", models.CharField(blank=True, max_length=255)),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=10,
                    ),
                ),
                ("proposed_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.CharField(blank=True, max_length=500)),
                (
                    "exam_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_change_proposals",
                        to="gradebook.examschedule",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_change_proposals",
                        to="gradebook.grade",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_change_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_grade_change_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_change_proposals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "grade_change_proposals",
                "ordering": ["-proposed_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "exam_schedule"],
                        name="grade_chang_student_6731b9_idx",
                    ),
                    models.Index(fields=["status"], name="grade_chang_status_47b543_idx"),
                ],
            },
        ),
    ]
