# Generated by Django 5.2.17 on 2026-08-11 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook", "0004_gradechangeproposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradechangeproposal",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grade_change_proposals",
                to="gradebook.grade",
            ),
        ),
    ]
