# Generated by Django 5.1.15 on 2026-08-31 13:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_versioning_and_course_catalog"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("gradebook", "0005_alter_gradechangeproposal_grade"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=4, max_digits=6),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "rubric_criteria",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExtraCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("assignment", "Extra Credit Assignment"),
                            ("bonus_points", "Bonus Points"),
                            ("participation", "Participation Bonus"),
                        ],
                        default="assignment",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "max_bonus_marks",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="extra_credit/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_credit_options",
                        to="gradebook.assessment",
                    ),
                ),
            ],
            options={
                "db_table": "extra_credit",
            },
        ),
        migrations.CreateModel(
            name="GPACalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Fall 2025, Spring 2026",
                        max_length=20,
                    ),
                ),
                (
                    "gpa_type",
                    models.CharField(
                        choices=[
                            ("semester", "Semester GPA"),
                            ("cumulative", "Cumulative GPA"),
                            ("weighted", "Weighted GPA"),
                            ("unweighted", "Unweighted GPA"),
                        ],
                        default="cumulative",
                        max_length=15,
                    ),
                ),
                ("gpa_value", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "total_grade_points",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("total_credits", models.DecimalField(decimal_places=2, max_digits=6)),
                ("class_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("class_size", models.PositiveIntegerField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpa_calculations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "gpa_calculations",
                "ordering": ["-academic_year", "-semester"],
                "unique_together": {("student", "academic_year", "semester", "gpa_type")},
            },
        ),
        migrations.CreateModel(
            name="CourseGradeCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=6)),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_letter", models.CharField(max_length=5)),
                ("grade_points", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "credits",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                (
                    "is_honors",
                    models.BooleanField(default=False, help_text="Honors/AP course"),
                ),
                ("is_pass_fail", models.BooleanField(default=False)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
                (
                    "gpa_calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grades",
                        to="gradebook.gpacalculation",
                    ),
                ),
            ],
            options={
                "db_table": "course_grade_calculations",
            },
        ),
        migrations.CreateModel(
            name="GradeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Performance"),
                            ("behavior", "Behavior"),
                            ("attendance", "Attendance"),
                            ("work_habits", "Work Habits"),
                            ("social", "Social Skills"),
                            ("general", "General"),
                        ],
                        max_length=15,
                    ),
                ),
                ("comment_text", models.TextField()),
                (
                    "grade_range_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Min percentage for this comment",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "grade_range_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Max percentage for this comment",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_comments",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "grade_comments",
                "ordering": ["category", "comment_text"],
            },
        ),
        migrations.CreateModel(
            name="GradeNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("grade_posted", "Grade Posted"),
                            ("grade_changed", "Grade Changed"),
                            ("missing_assignment", "Missing Assignment"),
                            ("grade_warning", "Grade Warning"),
                            ("report_card", "Report Card Available"),
                            ("transcript", "Transcript Ready"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("grade_value", models.CharField(blank=True, max_length=20)),
                ("previous_grade", models.CharField(blank=True, max_length=20)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(default="pending", max_length=15)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_notifications",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_notifications",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "grade_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GradingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage weight (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "drop_lowest",
                    models.PositiveIntegerField(default=0, help_text="Number of lowest scores to drop"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_categories",
                        to="auth_service.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_categories",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "grading_categories",
                "ordering": ["-weight"],
                "unique_together": {("name", "subject", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="LatePenaltyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Deduction"),
                            ("fixed", "Fixed Points Deduction"),
                            ("per_day", "Per Day Deduction"),
                            ("stepwise", "Stepwise Deduction"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "penalty_value",
                    models.DecimalField(decimal_places=2, help_text="Points or percentage", max_digits=6),
                ),
                (
                    "max_penalty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum deduction",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "grace_period_hours",
                    models.PositiveIntegerField(default=0, help_text="Hours before penalty applies"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_penalty_rules",
                        to="auth_service.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "late_penalty_rules",
            },
        ),
        migrations.CreateModel(
            name="RubricLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="gradebook.rubriccriterion",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_levels",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RubricTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric_templates",
                        to="auth_service.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="rubriccriterion",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria",
                to="gradebook.rubrictemplate",
            ),
        ),
        migrations.CreateModel(
            name="RubricAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric_assessments",
                        to="gradebook.assessment",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric_assessments",
                        to="students.student",
                    ),
                ),
                (
                    "rubric_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.rubrictemplate",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_assessments",
                "unique_together": {("assessment", "student")},
            },
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "standard_type",
                    models.CharField(
                        choices=[
                            ("course", "Course Standard"),
                            ("grade_level", "Grade Level Standard"),
                            ("district", "District Standard"),
                            ("state", "State Standard"),
                        ],
                        default="course",
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grade_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.grade",
                    ),
                ),
                (
                    "parent_standard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_standards",
                        to="gradebook.standard",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standards",
                        to="auth_service.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standards",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "standards",
                "ordering": ["code"],
                "unique_together": {("school", "code")},
            },
        ),
        migrations.CreateModel(
            name="StandardMasteryScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "levels",
                    models.JSONField(default=list, help_text="List of mastery levels with scores"),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mastery_scales",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "standard_mastery_scales",
            },
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transcript_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("final", "Final"),
                            ("requested", "Requested"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("cumulative_gpa", models.DecimalField(decimal_places=3, max_digits=4)),
                ("class_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("class_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total_credits_earned",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("graduation_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="transcripts/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gradebook_transcripts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "transcripts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranscriptEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(blank=True, max_length=20)),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=6)),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_letter", models.CharField(max_length=5)),
                ("grade_points", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "credits",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                ("is_honors", models.BooleanField(default=False)),
                ("is_repeated", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="gradebook.transcript",
                    ),
                ),
            ],
            options={
                "db_table": "transcript_entries",
                "ordering": ["academic_year", "semester", "subject"],
            },
        ),
        migrations.CreateModel(
            name="ExtraCreditSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_marks_obtained",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="extra_credit_submissions/"),
                ),
                ("remarks", models.TextField(blank=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "extra_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="gradebook.extracredit",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_credit_submissions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "extra_credit_submissions",
                "unique_together": {("extra_credit", "student")},
            },
        ),
        migrations.CreateModel(
            name="GradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(blank=True, max_length=20)),
                ("final_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=6)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_letter", models.CharField(max_length=5)),
                ("grade_points", models.DecimalField(decimal_places=2, max_digits=3)),
                ("is_pass", models.BooleanField(default=True)),
                ("teacher_name", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_history",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "grade_history",
                "ordering": ["-academic_year", "-semester"],
                "unique_together": {("student", "subject", "academic_year", "semester")},
            },
        ),
        migrations.CreateModel(
            name="CategoryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_links",
                        to="gradebook.assessment",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="gradebook.gradingcategory",
                    ),
                ),
            ],
            options={
                "db_table": "category_assignments",
                "unique_together": {("assessment", "category")},
            },
        ),
        migrations.CreateModel(
            name="ReportCardComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_text",
                    models.TextField(blank=True, help_text="Customized version of the comment"),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.gradecomment",
                    ),
                ),
                (
                    "report_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_comments",
                        to="gradebook.reportcard",
                    ),
                ),
            ],
            options={
                "db_table": "report_card_comments",
                "unique_together": {("report_card", "comment")},
            },
        ),
        migrations.CreateModel(
            name="RubricScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("feedback", models.TextField(blank=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gradebook.rubriccriterion",
                    ),
                ),
                (
                    "rubric_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="gradebook.rubricassessment",
                    ),
                ),
                (
                    "selected_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gradebook.rubriclevel",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_scores",
                "unique_together": {("rubric_assessment", "criterion")},
            },
        ),
        migrations.CreateModel(
            name="StudentStandardGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("exceeding", "Exceeding Mastery"),
                            ("meeting", "Meeting Mastery"),
                            ("approaching", "Approaching Mastery"),
                            ("beginning", "Beginning"),
                            ("not_yet", "Not Yet Meeting"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "evidence",
                    models.TextField(blank=True, help_text="Evidence supporting this grade"),
                ),
                ("graded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_grades",
                        to="gradebook.standard",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_grades",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_standard_grades",
                "unique_together": {("student", "standard", "academic_year")},
            },
        ),
    ]
