# Generated by Django 4.2.13 on 2026-07-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="bio",
            field=models.TextField(blank=True, help_text="Short personal biography"),
        ),
        migrations.AddField(
            model_name="student",
            name="interests",
            field=models.TextField(
                blank=True, help_text="Hobbies, extracurricular interests"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="learning_goals",
            field=models.TextField(
                blank=True, help_text="Academic goals and aspirations"
            ),
        ),
    ]
