# Generated by Django 4.2.13 on 2026-07-22 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0003_student_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, help_text="Current occupation", max_length=100
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True, help_text="Alternate contact number", max_length=20
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Residential address"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Short personal biography"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profiles",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Profile",
                "verbose_name_plural": "Parent Profiles",
                "db_table": "parent_profiles",
            },
        ),
    ]
