# Generated by Django 5.1.15 on 2026-08-31 11:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(blank=True, help_text="Hex color code", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("student_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_categories",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "student_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("personal_phone", models.CharField(blank=True, max_length=20)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                (
                    "emergency_contact_1_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "emergency_contact_1_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_1_relationship",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "emergency_contact_2_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "emergency_contact_2_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_2_relationship",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "medical_emergency_contact",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "medical_emergency_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("doctor_name", models.CharField(blank=True, max_length=150)),
                ("doctor_phone", models.CharField(blank=True, max_length=20)),
                ("insurance_provider", models.CharField(blank=True, max_length=150)),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_info",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_contacts",
            },
        ),
        migrations.CreateModel(
            name="StudentCustomField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Yes/No"),
                            ("select", "Dropdown"),
                            ("multi_select", "Multi-Select"),
                            ("url", "URL"),
                            ("email", "Email"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Options for select/multi-select fields",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_custom_fields",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "student_custom_fields",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentIDCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_number", models.CharField(max_length=50, unique=True)),
                ("barcode", models.CharField(blank=True, max_length=100)),
                ("rfid_number", models.CharField(blank=True, max_length=50)),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("lost", "Lost"),
                            ("replaced", "Replaced"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("photo_url", models.URLField(blank=True)),
                (
                    "access_level",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Library, Cafeteria, Building",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_cards",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_id_cards",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentMedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergy"),
                            ("condition", "Medical Condition"),
                            ("medication", "Medication"),
                            ("immunization", "Immunization"),
                            ("visit", "Medical Visit"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("life_threatening", "Life-Threatening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_recorded", models.DateField(auto_now_add=True)),
                ("date_of_visit", models.DateField(blank=True, null=True)),
                ("doctor_name", models.CharField(blank=True, max_length=150)),
                ("hospital_name", models.CharField(blank=True, max_length=200)),
                ("treatment_notes", models.TextField(blank=True)),
                ("medication_details", models.TextField(blank=True)),
                ("document_url", models.URLField(blank=True)),
                ("is_ongoing", models.BooleanField(default=False)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_medical_records",
                "ordering": ["-date_recorded"],
            },
        ),
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("academic", "Academic"),
                            ("behavior", "Behavior"),
                            ("medical", "Medical"),
                            ("pastoral", "Pastoral"),
                            ("confidential", "Confidential"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("is_confidential", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notes",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile Photo"),
                            ("id_photo", "ID Card Photo"),
                            ("class_photo", "Class Photo"),
                            ("event", "Event Photo"),
                            ("other", "Other"),
                        ],
                        default="profile",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("taken_date", models.DateField(auto_now_add=True)),
                ("photographer", models.CharField(blank=True, max_length=150)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="students.student",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_photos",
                "ordering": ["-taken_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentPortfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "portfolio_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Work"),
                            ("creative", "Creative Work"),
                            ("project", "Project"),
                            ("presentation", "Presentation"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("date_completed", models.DateField(auto_now_add=True)),
                ("grade_received", models.CharField(blank=True, max_length=10)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_portfolio",
                "ordering": ["-date_completed"],
            },
        ),
        migrations.CreateModel(
            name="StudentStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("transferred", "Transferred"),
                            ("expelled", "Expelled"),
                            ("deceased", "Deceased"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("transferred", "Transferred"),
                            ("expelled", "Expelled"),
                            ("deceased", "Deceased"),
                        ],
                        max_length=15,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("document_url", models.URLField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_status_history",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_tags",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "student_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentWellness",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wellness_type",
                    models.CharField(
                        choices=[
                            ("check_in", "Wellness Check-In"),
                            ("assessment", "Assessment"),
                            ("counseling", "Counseling Session"),
                            ("incident", "Incident Report"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("attention", "Needs Attention"),
                            ("concern", "Concerning"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "mood_score",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-10 scale", null=True),
                ),
                (
                    "stress_level",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-10 scale", null=True),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("is_confidential", models.BooleanField(default=True)),
                ("document_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_wellness",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellness_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_wellness",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiblingTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("sibling", "Sibling"),
                            ("twin", "Twin"),
                            ("step_sibling", "Step-Sibling"),
                        ],
                        default="sibling",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sibling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_siblings",
                        to="students.student",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siblings",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_siblings",
                "unique_together": {("student", "sibling")},
            },
        ),
        migrations.CreateModel(
            name="StudentArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("withdrawn", "Withdrawn"),
                            ("suspended", "Suspended"),
                            ("transferred", "Transferred"),
                        ],
                        max_length=15,
                    ),
                ),
                ("final_grade", models.CharField(blank=True, max_length=10)),
                (
                    "gpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "rank_in_class",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("report_card_url", models.URLField(blank=True)),
                ("transcript_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.classroom",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_archives",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_archives",
                "ordering": ["-academic_year"],
                "unique_together": {("student", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="StudentCategoryMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="students.studentcategory",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_memberships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_category_memberships",
                "unique_together": {("student", "category")},
            },
        ),
        migrations.CreateModel(
            name="StudentCustomFieldValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text_value", models.TextField(blank=True)),
                (
                    "number_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("date_value", models.DateField(blank=True, null=True)),
                ("boolean_value", models.BooleanField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="students.studentcustomfield",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_custom_field_values",
                "unique_together": {("student", "field")},
            },
        ),
        migrations.CreateModel(
            name="StudentSocialMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter/X"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100)),
                ("profile_url", models.URLField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_social_media",
                "unique_together": {("student", "platform")},
            },
        ),
        migrations.CreateModel(
            name="StudentTagAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to="students.student",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="students.studenttag",
                    ),
                ),
            ],
            options={
                "db_table": "student_tag_assignments",
                "unique_together": {("student", "tag")},
            },
        ),
    ]
