# Generated by Django 5.1.15 on 2026-09-01 08:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_versioning_and_course_catalog"),
        ("auth_service", "0006_add_auth_gap_models"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        (
            "transportation",
            "0002_fuellog_transportfee_transportincidentreport_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAcademicAdvisor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("advising_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("academic_goals", models.TextField(blank=True)),
                ("course_recommendations", models.TextField(blank=True)),
                ("academic_concerns", models.TextField(blank=True)),
                ("action_items", models.TextField(blank=True)),
                ("next_advising_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_academic_advising",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_advising",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_academic_advising",
                "ordering": ["-advising_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Honor"),
                            ("sports", "Sports Achievement"),
                            ("arts", "Arts Achievement"),
                            ("leadership", "Leadership"),
                            ("service", "Community Service"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_earned", models.DateField()),
                ("awarded_by", models.CharField(blank=True, max_length=200)),
                ("certificate_url", models.URLField(blank=True, max_length=500)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_achievements",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_achievements",
                "ordering": ["-date_earned"],
            },
        ),
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity_name", models.CharField(max_length=200)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("arts", "Arts"),
                            ("music", "Music"),
                            ("drama", "Drama"),
                            ("debate", "Debate"),
                            ("science", "Science Club"),
                            ("coding", "Coding Club"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "hours_per_week",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_activities",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_activities",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("award_name", models.CharField(max_length=200)),
                (
                    "award_level",
                    models.CharField(
                        choices=[
                            ("classroom", "Classroom"),
                            ("school", "School"),
                            ("district", "District"),
                            ("state", "State"),
                            ("national", "National"),
                            ("international", "International"),
                        ],
                        default="school",
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("date_awarded", models.DateField()),
                ("awarded_by", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("certificate_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_awards",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_awards",
                "ordering": ["-date_awarded"],
            },
        ),
        migrations.CreateModel(
            name="StudentCareerGuidance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "career_interest",
                    models.CharField(
                        choices=[
                            ("stem", "STEM"),
                            ("business", "Business"),
                            ("arts", "Arts & Humanities"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("law", "Law"),
                            ("engineering", "Engineering"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("career_goals", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("areas_for_development", models.TextField(blank=True)),
                ("recommended_courses", models.TextField(blank=True)),
                ("recommended_activities", models.TextField(blank=True)),
                ("college_preferences", models.TextField(blank=True)),
                ("scholarship_eligibility", models.BooleanField(default=False)),
                ("guidance_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_career_guidance",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_guidance",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_career_guidance",
                "ordering": ["-guidance_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentClub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("club_name", models.CharField(max_length=200)),
                ("club_type", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("president", "President"),
                            ("vice_president", "Vice President"),
                            ("secretary", "Secretary"),
                            ("treasurer", "Treasurer"),
                            ("advisor", "Faculty Advisor"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("join_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_club_memberships",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_club_memberships",
                "ordering": ["-join_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentDiscipline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("warning", "Warning"),
                            ("detention", "Detention"),
                            ("suspension", "Suspension"),
                            ("expulsion", "Expulsion"),
                            ("counseling", "Counseling"),
                            ("community_service", "Community Service"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                            ("critical", "Critical"),
                        ],
                        default="minor",
                        max_length=20,
                    ),
                ),
                ("incident_date", models.DateField()),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("witnesses", models.TextField(blank=True)),
                ("action_taken", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("parent_notified_date", models.DateField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_discipline",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_discipline",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("course", "Course Feedback"),
                            ("teacher", "Teacher Feedback"),
                            ("facility", "Facility Feedback"),
                            ("service", "Service Feedback"),
                            ("general", "General Feedback"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Neutral"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("suggestions", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("feedback_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_feedback",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentFinancialAid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aid_type",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("loan", "Loan"),
                            ("work_study", "Work-Study"),
                            ("waiver", "Fee Waiver"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("aid_name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("provider", models.CharField(blank=True, max_length=200)),
                ("application_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("disbursed", "Disbursed"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                ("renewal_required", models.BooleanField(default=False)),
                ("academic_requirement", models.TextField(blank=True)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_financial_aid",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_aid",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_financial_aid",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentGraduation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expected_graduation_year", models.PositiveSmallIntegerField()),
                (
                    "actual_graduation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "On Track"),
                            ("at_risk", "At Risk"),
                            ("graduated", "Graduated"),
                            ("not_graduated", "Not Graduated"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                (
                    "credits_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "credits_required",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("gpa", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("class_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("diploma_type", models.CharField(blank=True, max_length=100)),
                ("honors", models.CharField(blank=True, max_length=100)),
                ("college_acceptance", models.TextField(blank=True)),
                (
                    "scholarship_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_graduation",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graduation_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_graduation",
                "ordering": ["-expected_graduation_year"],
            },
        ),
        migrations.CreateModel(
            name="StudentIDActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("entry", "Building Entry"),
                            ("exit", "Building Exit"),
                            ("library", "Library"),
                            ("cafeteria", "Cafeteria"),
                            ("lab", "Lab Access"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("device", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "id_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.studentidcard",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_id_activities",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="id_activities",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_id_activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StudentInternship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("supervisor_name", models.CharField(blank=True, max_length=200)),
                ("supervisor_email", models.EmailField(blank=True, max_length=254)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "hours_per_week",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "stipend_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
                ("skills_gained", models.TextField(blank=True)),
                ("evaluation", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-5 rating", null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_internships",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_internships",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentLearningStyle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "primary_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual"),
                            ("auditory", "Auditory"),
                            ("kinesthetic", "Kinesthetic"),
                            ("reading", "Reading/Writing"),
                            ("multimodal", "Multimodal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "secondary_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visual", "Visual"),
                            ("auditory", "Auditory"),
                            ("kinesthetic", "Kinesthetic"),
                            ("reading", "Reading/Writing"),
                            ("multimodal", "Multimodal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assessment_tool", models.CharField(blank=True, max_length=100)),
                ("score_visual", models.PositiveSmallIntegerField(default=0)),
                ("score_auditory", models.PositiveSmallIntegerField(default=0)),
                ("score_kinesthetic", models.PositiveSmallIntegerField(default=0)),
                ("score_reading", models.PositiveSmallIntegerField(default=0)),
                ("recommendations", models.TextField(blank=True)),
                ("assessed_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_learning_styles",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_styles",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_learning_styles",
                "ordering": ["-assessed_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentMealPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Board"),
                            ("lunch", "Lunch Only"),
                            ("breakfast", "Breakfast Only"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plan_name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("meals_per_day", models.PositiveSmallIntegerField(default=3)),
                ("total_meals", models.PositiveIntegerField(default=0)),
                ("meals_consumed", models.PositiveIntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("dietary_restrictions", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_meal_plans",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_meal_plans",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentMentor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("program_name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("goals", models.TextField(blank=True)),
                ("meeting_frequency", models.CharField(blank=True, max_length=50)),
                ("progress_notes", models.TextField(blank=True)),
                ("outcome", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_mentorships",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentorships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_mentorships",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentParentCommunication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("phone_call", "Phone Call"),
                            ("email", "Email"),
                            ("note", "Written Note"),
                            ("conference", "Conference"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("communication_date", models.DateField()),
                ("parent_name", models.CharField(blank=True, max_length=200)),
                ("parent_phone", models.CharField(blank=True, max_length=20)),
                ("parent_email", models.EmailField(blank=True, max_length=254)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("is_confidential", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_parent_communications",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_communications",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_parent_communications",
                "ordering": ["-communication_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentParking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("permit_number", models.CharField(max_length=50, unique=True)),
                (
                    "permit_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("staff", "Staff"),
                            ("visitor", "Visitor"),
                            ("handicap", "Handicap"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("vehicle_make", models.CharField(blank=True, max_length=100)),
                ("vehicle_model", models.CharField(blank=True, max_length=100)),
                ("vehicle_color", models.CharField(blank=True, max_length=50)),
                ("license_plate", models.CharField(max_length=20)),
                ("parking_zone", models.CharField(blank=True, max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_parking",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_permits",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_parking_permits",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentScholarship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scholarship_name", models.CharField(max_length=200)),
                ("provider", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("scholarship_type", models.CharField(blank=True, max_length=100)),
                ("application_date", models.DateField()),
                ("deadline_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("pending", "Pending"),
                            ("awarded", "Awarded"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                ("award_date", models.DateField(blank=True, null=True)),
                ("renewal_required", models.BooleanField(default=False)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "gpa_requirement",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("documents", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_scholarships",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_scholarships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_scholarships",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("incoming", "Incoming"),
                            ("outgoing", "Outgoing"),
                            ("internal", "Internal Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_school", models.CharField(blank=True, max_length=200)),
                ("to_school", models.CharField(blank=True, max_length=200)),
                ("transfer_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_from",
                        to="students.classroom",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_transfers",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_transfers",
                        to="students.student",
                    ),
                ),
                (
                    "to_classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_to",
                        to="students.classroom",
                    ),
                ),
            ],
            options={
                "db_table": "student_transfers",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentTransportAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup Only"),
                            ("dropoff", "Dropoff Only"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("pickup_address", models.TextField(blank=True)),
                (
                    "pickup_latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_transport",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_transport_assignments",
                        to="students.student",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "student_transport_assignments",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="StudentTutoring",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("topics_covered", models.TextField(blank=True)),
                ("homework_assigned", models.TextField(blank=True)),
                ("progress_notes", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-5 rating", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_tutoring",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutoring_sessions",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutoring_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_tutoring",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentVolunteer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("organization", models.CharField(max_length=200)),
                ("activity", models.CharField(max_length=200)),
                ("hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date_performed", models.DateField()),
                ("supervisor_name", models.CharField(blank=True, max_length=200)),
                ("supervisor_phone", models.CharField(blank=True, max_length=20)),
                ("supervisor_email", models.EmailField(blank=True, max_length=254)),
                ("certificate_url", models.URLField(blank=True, max_length=500)),
                ("verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_volunteer",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_hours",
                        to="students.student",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_volunteer_hours",
                "ordering": ["-date_performed"],
            },
        ),
    ]
