# Generated by Django 4.2.13 on 2026-07-17 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("fees", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGatewayConfig",
            fields=[
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="payment_gateway_config",
                        serialize=False,
                        to="auth_service.school",
                    ),
                ),
                (
                    "stripe_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable Stripe (credit/debit card) payments",
                    ),
                ),
                (
                    "khalti_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable Khalti wallet payments"
                    ),
                ),
                (
                    "esewa_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable eSewa wallet payments"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_gateway_config",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("card", "Credit/Debit Card"),
                    ("cheque", "Cheque"),
                    ("online", "Online Gateway"),
                    ("mobile", "Mobile Money"),
                    ("khalti", "Khalti"),
                    ("esewa", "eSewa"),
                ],
                max_length=20,
            ),
        ),
    ]
