# Generated by Django 5.2.17 on 2026-08-17 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0005_alter_payment_transaction_id"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feeinvoice",
            index=models.Index(
                fields=["student", "academic_year"],
                name="fee_invoice_student_560ac0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status", "paid_at"], name="payments_status_ed0c90_idx"),
        ),
    ]
