# Generated by Django 5.2.17 on 2026-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0006_feeinvoice_fee_invoice_student_560ac0_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the payment receipt notification was sent (set once per successful payment)",
                null=True,
            ),
        ),
    ]
