# Generated by Django 5.2.17 on 2026-08-18 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0007_payment_receipt_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refunded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who initiated the refund",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunded_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="collected_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collected_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
