# Generated by Django 5.1.15 on 2026-08-31 14:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("fees", "0008_payment_refunded_by_alter_payment_collected_by"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "applied_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("applied_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_to_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fees.feeinvoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_payments",
                        to="fees.payment",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_payments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_payments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "advance_payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="BulkInvoiceGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_invoices_generated", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("errors", models.JSONField(default=list, help_text="List of errors")),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "fee_categories",
                    models.ManyToManyField(blank=True, to="fees.feecategory"),
                ),
                ("grades", models.ManyToManyField(blank=True, to="students.grade")),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_invoices",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "bulk_invoice_generations",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="FeeAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("discount", "Discount"),
                            ("surcharge", "Surcharge"),
                            ("waiver", "Fee Waiver"),
                            ("penalty", "Penalty"),
                            ("credit", "Credit"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("adjustment_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_fee_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fee_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="fees.feeinvoice",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_adjustments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_adjustments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "fee_adjustments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeeCollectionDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_expected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "collection_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("collected_by_category", models.JSONField(default=dict)),
                ("outstanding_by_category", models.JSONField(default=dict)),
                ("collected_by_grade", models.JSONField(default=dict)),
                ("outstanding_by_grade", models.JSONField(default=dict)),
                ("collected_by_method", models.JSONField(default=dict)),
                (
                    "daily_collection",
                    models.JSONField(default=list, help_text="Last 30 days collection"),
                ),
                (
                    "monthly_collection",
                    models.JSONField(default=list, help_text="Last 12 months collection"),
                ),
                ("total_defaulters", models.PositiveIntegerField(default=0)),
                (
                    "total_overdue_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_dashboards",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "fee_collection_dashboards",
            },
        ),
        migrations.CreateModel(
            name="FeeConcession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "concession_type",
                    models.CharField(
                        choices=[
                            ("sibling", "Sibling Discount"),
                            ("staff_ward", "Staff Ward"),
                            ("merit", "Merit-Based"),
                            ("need_based", "Need-Based"),
                            ("government", "Government Scheme"),
                            ("sports", "Sports Achievement"),
                            ("cultural", "Cultural Achievement"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed Amount")],
                        max_length=10,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum concession amount",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                (
                    "supporting_documents",
                    models.JSONField(default=list, help_text="List of document URLs"),
                ),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "applies_to_categories",
                    models.ManyToManyField(blank=True, to="fees.feecategory"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_concessions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_concessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "fee_concessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeeTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("tuition", "Tuition Fee"),
                            ("transport", "Transport Fee"),
                            ("hostel", "Hostel Fee"),
                            ("lab", "Lab Fee"),
                            ("library", "Library Fee"),
                            ("sports", "Sports Fee"),
                            ("exam", "Examination Fee"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("is_recurring", models.BooleanField(default=True)),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "late_fee_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_templates",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "fee_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeeWaiver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "waiver_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Waiver"),
                            ("partial", "Partial Waiver"),
                            ("category", "Category Waiver"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, help_text="Amount to waive", max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("reason", models.TextField(help_text="Reason for waiver")),
                ("supporting_documents", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "applies_to_categories",
                    models.ManyToManyField(blank=True, to="fees.feecategory"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_waivers",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_waivers",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "fee_waivers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("number_of_installments", models.PositiveSmallIntegerField()),
                (
                    "installment_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("defaulted", "Defaulted"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "late_fee_per_installment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("grace_period_days", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plans",
                        to="fees.feeinvoice",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plans",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plans",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "installment_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reconciliation_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Reconciliation"),
                            ("weekly", "Weekly Reconciliation"),
                            ("monthly", "Monthly Reconciliation"),
                            ("manual", "Manual Reconciliation"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("discrepancies", "Has Discrepancies"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_expected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_matched",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_unmatched",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "match_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discrepancies",
                    models.JSONField(default=list, help_text="List of discrepancies found"),
                ),
                ("discrepancy_count", models.PositiveIntegerField(default=0)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("report_url", models.URLField(blank=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_reconciliations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "payment_reconciliations",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="fees.feeinvoice",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_reminders",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_reminders",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "payment_reminders",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="RevenueReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Collection"),
                            ("weekly", "Weekly Collection"),
                            ("monthly", "Monthly Collection"),
                            ("quarterly", "Quarterly Collection"),
                            ("annual", "Annual Collection"),
                            ("category", "Category-wise Report"),
                            ("grade", "Grade-wise Report"),
                            ("outstanding", "Outstanding Dues"),
                            ("defaulters", "Defaulters Report"),
                            ("scholarship", "Scholarship Report"),
                            ("refund", "Refund Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.TextField(blank=True)),
                ("findings", models.JSONField(default=dict)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "total_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_refunded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_scholarships",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_concessions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("collection_by_category", models.JSONField(default=dict)),
                ("collection_by_grade", models.JSONField(default=dict)),
                ("collection_by_payment_method", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "revenue_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiblingDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed Amount")],
                        max_length=10,
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "min_siblings",
                    models.PositiveSmallIntegerField(default=2, help_text="Minimum siblings required"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(default=0, help_text="Higher priority applied first"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applies_to_categories",
                    models.ManyToManyField(blank=True, to="fees.feecategory"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sibling_discounts",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "sibling_discounts",
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="InstallmentPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("installment_number", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fees.payment",
                    ),
                ),
                (
                    "installment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="fees.installmentplan",
                    ),
                ),
            ],
            options={
                "db_table": "installment_payments",
                "ordering": ["installment_number"],
                "unique_together": {("installment_plan", "installment_number")},
            },
        ),
        migrations.CreateModel(
            name="StudentLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice Generated"),
                            ("payment", "Payment Received"),
                            ("adjustment", "Fee Adjustment"),
                            ("scholarship", "Scholarship Applied"),
                            ("concession", "Concession Applied"),
                            ("waiver", "Fee Waiver"),
                            ("refund", "Refund"),
                            ("late_fee", "Late Fee"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("transaction_date", models.DateField()),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fees.feeinvoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fees.payment",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_ledgers",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_ledgers",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_ledgers",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "academic_year", "transaction_date"],
                        name="student_led_student_ff2b88_idx",
                    )
                ],
            },
        ),
    ]
