# Generated by Django 5.2.17 on 2026-09-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0010_accountingentry_bankreconciliation_budgetplan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
