# Generated by Django 4.2.13 on 2026-07-02 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "auth_service",
            "0002_rename_users_school_role_idx_users_school__f0a553_idx_and_more",
        ),
        ("academics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherassignment",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="students.classroom",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="students.grade",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="auth_service.school",
            ),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_plans",
                to="academics.teacherassignment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together={("teacher", "subject", "classroom", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("school", "code", "grade")},
        ),
    ]
