# Generated by Django 4.2.13 on 2026-07-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Professional bio / biography"
            ),
        ),
    ]
