# Generated by Django 5.1.15 on 2026-08-31 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_teacherprofile_bio"),
        ("students", "0004_role_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSubjectEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dropped", "Dropped"),
                            ("transferred", "Transferred"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to="students.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_enrollments",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "student_subject_enrollments",
                "ordering": ["-enrolled_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "academic_year"],
                        name="student_sub_student_a46f26_idx",
                    ),
                    models.Index(
                        fields=["subject", "academic_year"],
                        name="student_sub_subject_18ec72_idx",
                    ),
                    models.Index(fields=["status"], name="student_sub_status_591202_idx"),
                ],
                "unique_together": {("student", "subject", "academic_year")},
            },
        ),
    ]
