# Generated by Django 5.1.15 on 2026-08-31 05:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_student_subject_enrollment"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumStandard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("common_core", "Common Core State Standards"),
                            ("ngss", "Next Generation Science Standards"),
                            ("cbse", "CBSE Curriculum"),
                            ("ncert", "NCERT Curriculum"),
                            ("national_uk", "National Curriculum (UK)"),
                            ("ib", "International Baccalaureate"),
                            ("custom", "Custom / School-Defined"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique standard code, e.g. CCSS.MATH.8.EE.1",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        help_text="High-level domain, e.g. Algebra, Geometry, Life Science",
                        max_length=100,
                    ),
                ),
                (
                    "cluster",
                    models.CharField(
                        blank=True,
                        help_text="Sub-domain cluster within the domain",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_standards",
                        to="students.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_standards",
                        to="auth_service.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_standards",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "curriculum_standards",
                "ordering": ["grade", "code"],
            },
        ),
        migrations.CreateModel(
            name="SubjectStandardMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coverage_level",
                    models.CharField(
                        choices=[
                            ("full", "Fully Covered"),
                            ("partial", "Partially Covered"),
                            ("introduced", "Introduced"),
                            ("not_covered", "Not Covered"),
                        ],
                        default="partial",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_mappings",
                        to="students.academicyear",
                    ),
                ),
                (
                    "mapped_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standard_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_mappings",
                        to="academics.curriculumstandard",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_mappings",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "subject_standard_mappings",
                "ordering": ["subject", "standard__code"],
            },
        ),
        migrations.AddIndex(
            model_name="curriculumstandard",
            index=models.Index(fields=["school", "framework"], name="curriculum__school__99b6e6_idx"),
        ),
        migrations.AddIndex(
            model_name="curriculumstandard",
            index=models.Index(fields=["school", "grade"], name="curriculum__school__fbe25e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="curriculumstandard",
            unique_together={("school", "code")},
        ),
        migrations.AddIndex(
            model_name="subjectstandardmapping",
            index=models.Index(
                fields=["subject", "academic_year"],
                name="subject_sta_subject_30825e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectstandardmapping",
            index=models.Index(
                fields=["standard", "academic_year"],
                name="subject_sta_standar_8841d9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectstandardmapping",
            unique_together={("subject", "standard", "academic_year")},
        ),
    ]
