# Generated by Django 5.1.15 on 2026-08-31 05:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_curriculum_standards_mapping"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Syllabus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("1st", "First Term"),
                            ("2nd", "Second Term"),
                            ("3rd", "Third Term"),
                            ("sem1", "Semester 1"),
                            ("sem2", "Semester 2"),
                            ("annual", "Annual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "learning_objectives",
                    models.TextField(help_text="High-level learning objectives for this term"),
                ),
                (
                    "resources",
                    models.TextField(
                        blank=True,
                        help_text="Textbooks, online resources, lab materials",
                    ),
                ),
                (
                    "assessment_criteria",
                    models.TextField(blank=True, help_text="How students will be assessed"),
                ),
                (
                    "total_hours",
                    models.PositiveSmallIntegerField(default=0, help_text="Planned total teaching hours for the term"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabi",
                        to="students.academicyear",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_syllabi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_syllabi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabi",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "syllabi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyllabusTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(help_text="Sequence order within the syllabus"),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True,
                        help_text="What students should know/be able to do after this topic",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        help_text="Estimated teaching hours",
                        max_digits=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "syllabus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="academics.syllabus",
                    ),
                ),
            ],
            options={
                "db_table": "syllabus_topics",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="syllabus",
            index=models.Index(fields=["subject", "academic_year"], name="syllabi_subject_590faf_idx"),
        ),
        migrations.AddIndex(
            model_name="syllabus",
            index=models.Index(fields=["status"], name="syllabi_status_b20ffa_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="syllabus",
            unique_together={("subject", "academic_year", "term")},
        ),
        migrations.AddIndex(
            model_name="syllabustopic",
            index=models.Index(fields=["syllabus", "status"], name="syllabus_to_syllabu_aa2e42_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="syllabustopic",
            unique_together={("syllabus", "order")},
        ),
    ]
