# Generated by Django 5.1.15 on 2026-08-31 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_syllabus_management"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherWorkloadConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_periods_per_week",
                    models.PositiveSmallIntegerField(default=30, help_text="Maximum teaching periods per week"),
                ),
                (
                    "max_periods_per_day",
                    models.PositiveSmallIntegerField(default=7, help_text="Maximum teaching periods per day"),
                ),
                (
                    "max_subjects",
                    models.PositiveSmallIntegerField(default=3, help_text="Maximum different subjects per teacher"),
                ),
                (
                    "max_classes",
                    models.PositiveSmallIntegerField(default=5, help_text="Maximum different classes per teacher"),
                ),
                (
                    "min_periods_per_week",
                    models.PositiveSmallIntegerField(default=15, help_text="Minimum teaching periods (for full-time)"),
                ),
                (
                    "warning_threshold_pct",
                    models.PositiveSmallIntegerField(default=90, help_text="Workload % at which to trigger warnings"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_workload_config",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "teacher_workload_configs",
            },
        ),
        migrations.CreateModel(
            name="TeacherWorkloadSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField(help_text="Monday of the week")),
                ("total_periods", models.PositiveSmallIntegerField(default=0)),
                (
                    "periods_per_day",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON map of day name to period count, e.g. {"Monday": 6}',
                    ),
                ),
                ("subjects_taught", models.PositiveSmallIntegerField(default=0)),
                ("classes_taught", models.PositiveSmallIntegerField(default=0)),
                (
                    "utilization_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of max periods used",
                        max_digits=5,
                    ),
                ),
                ("is_overloaded", models.BooleanField(default=False)),
                ("is_underloaded", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_snapshots",
                        to="students.academicyear",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teacher_workload_snapshots",
                "ordering": ["-week_start_date"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "academic_year"],
                        name="teacher_wor_teacher_f0f1f4_idx",
                    ),
                    models.Index(fields=["is_overloaded"], name="teacher_wor_is_over_c6eb7e_idx"),
                ],
                "unique_together": {("teacher", "academic_year", "week_start_date")},
            },
        ),
    ]
