# Generated by Django 5.1.15 on 2026-08-31 06:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_teacher_evaluation"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicTranscript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transcript_number",
                    models.CharField(
                        help_text="Unique transcript identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("verified", "Verified"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "total_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of max marks across all subjects",
                        max_digits=10,
                    ),
                ),
                (
                    "obtained_marks",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of marks obtained",
                        max_digits=10,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cumulative GPA",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(blank=True, help_text="Overall letter grade", max_length=5),
                ),
                (
                    "rank_in_class",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "rank_in_grade",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("attendance_days", models.PositiveSmallIntegerField(default=0)),
                ("total_school_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "subjects_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='JSON array of per-subject data: [{"name": ..., "marks": ..., "grade": ...}]',
                    ),
                ),
                ("principal_name", models.CharField(blank=True, max_length=255)),
                (
                    "principal_signature",
                    models.ImageField(blank=True, null=True, upload_to="transcripts/signatures/"),
                ),
                ("class_teacher_name", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="transcripts/pdfs/%Y/%m/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="students.academicyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="students.student",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "academic_transcripts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "academic_year"],
                        name="academic_tr_student_d19745_idx",
                    ),
                    models.Index(
                        fields=["transcript_number"],
                        name="academic_tr_transcr_d924bc_idx",
                    ),
                    models.Index(fields=["status"], name="academic_tr_status_da01d9_idx"),
                ],
                "unique_together": {("student", "academic_year")},
            },
        ),
    ]
