# Generated by Django 5.2.17 on 2026-08-17 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(fields=["recipient", "sent_at"], name="direct_mess_recipie_37d658_idx"),
        ),
        migrations.AddIndex(
            model_name="directmessage",
            index=models.Index(fields=["sender", "sent_at"], name="direct_mess_sender__551230_idx"),
        ),
    ]
