# Generated by Django 5.1.15 on 2026-08-31 14:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_versioning_and_course_catalog"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("communication", "0003_directmessage_direct_mess_recipie_37d658_idx_and_more"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                            ("all", "All Channels"),
                        ],
                        default="in_app",
                        max_length=10,
                    ),
                ),
                (
                    "target_audience",
                    models.JSONField(
                        default=list,
                        help_text="List of audience types: teachers, students, parents, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("partial", "Partially Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_delivered", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                ("total_read", models.PositiveIntegerField(default=0)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("require_read_receipt", models.BooleanField(default=False)),
                ("allow_reply", models.BooleanField(default=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="broadcasts/attachments/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_messages",
                        to="auth_service.school",
                    ),
                ),
                (
                    "target_classrooms",
                    models.ManyToManyField(blank=True, to="students.classroom"),
                ),
                (
                    "target_grades",
                    models.ManyToManyField(blank=True, to="students.grade"),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("class", "Class Group"),
                            ("subject", "Subject Group"),
                            ("club", "Club Group"),
                            ("department", "Department Group"),
                            ("staff", "Staff Group"),
                            ("parents", "Parents Group"),
                            ("custom", "Custom Group"),
                        ],
                        default="custom",
                        max_length=15,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="chat_groups/avatars/"),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("max_members", models.PositiveIntegerField(default=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_groups",
                        to="students.classroom",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_chat_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_groups",
                        to="auth_service.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_groups",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "chat_groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("voice", "Voice Message"),
                            ("video", "Video"),
                            ("system", "System Message"),
                            ("poll", "Poll"),
                            ("location", "Location"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="chat_groups/messages/"),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "reactions",
                    models.JSONField(blank=True, default=dict, help_text="{emoji: [user_ids]}"),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.chatgroup",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="communication.groupmessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_group_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "group_messages",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(help_text="Emoji character(s)", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to="communication.groupmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "message_reactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reply_count", models.PositiveIntegerField(default=0)),
                ("last_reply_at", models.DateTimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_reply_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="communication.groupmessage",
                    ),
                ),
            ],
            options={
                "db_table": "message_threads",
                "ordering": ["-last_reply_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentTeacherChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, help_text="Chat subject/topic", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("is_archived_by_parent", models.BooleanField(default=False)),
                ("is_archived_by_teacher", models.BooleanField(default=False)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("parent_unread_count", models.PositiveIntegerField(default=0)),
                ("teacher_unread_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_teacher_chats",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_teacher_chats",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "parent_teacher_chats",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentTeacherMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="parent_teacher_chat/"),
                ),
                ("is_read_by_parent", models.BooleanField(default=False)),
                ("is_read_by_teacher", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communication.parentteacherchat",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="communication.parentteachermessage",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_parent_teacher_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "parent_teacher_messages",
                "ordering": ["sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="communication.groupmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_read_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "read_receipts",
                "ordering": ["-read_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("nexmo", "Nexmo/Vonage"),
                            ("aws_sns", "AWS SNS"),
                            ("messagebird", "MessageBird"),
                            ("custom", "Custom Provider"),
                        ],
                        default="twilio",
                        max_length=15,
                    ),
                ),
                ("from_number", models.CharField(blank=True, max_length=20)),
                ("to_number", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_integrations",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_sms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sms_integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TypingIndicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chat_type",
                    models.CharField(
                        choices=[
                            ("group", "Group Chat"),
                            ("parent_teacher", "Parent-Teacher Chat"),
                            ("direct", "Direct Message"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        help_text="ID of the chat (group or parent-teacher)",
                        max_length=255,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_indicators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "typing_indicators",
            },
        ),
        migrations.CreateModel(
            name="VideoConference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "conference_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("parent_teacher", "Parent-Teacher Conference"),
                            ("staff", "Staff Meeting"),
                            ("class", "Virtual Class"),
                            ("tutoring", "Tutoring Session"),
                            ("interview", "Interview"),
                        ],
                        default="meeting",
                        max_length=15,
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(blank=True, help_text="Video meeting URL (Zoom, Meet, etc.)"),
                ),
                ("meeting_id", models.CharField(blank=True, max_length=100)),
                ("meeting_password", models.CharField(blank=True, max_length=50)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("max_participants", models.PositiveIntegerField(default=100)),
                ("is_recorded", models.BooleanField(default=False)),
                ("recording_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_conferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_conferences",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "video_conferences",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("attended", "Attended"),
                            ("no_show", "No Show"),
                        ],
                        default="invited",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="communication.videoconference",
                    ),
                ),
            ],
            options={
                "db_table": "conference_participants",
            },
        ),
        migrations.CreateModel(
            name="VoiceMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="voice_messages/%Y/%m/"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(help_text="Audio duration in seconds"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "transcription",
                    models.TextField(blank=True, help_text="Auto-generated transcription"),
                ),
                ("is_transcribed", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_messages",
                        to="communication.chatgroup",
                    ),
                ),
                (
                    "parent_teacher_chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voice_messages",
                        to="communication.parentteacherchat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_voice_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "voice_messages",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Message"),
                            ("announcement", "Announcement"),
                            ("broadcast", "Broadcast"),
                            ("direct_message", "Direct Message"),
                            ("group_message", "Group Message"),
                            ("parent_teacher", "Parent-Teacher Chat"),
                            ("video_conference", "Video Conference"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "content_preview",
                    models.TextField(blank=True, help_text="First 500 chars of content"),
                ),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="sent", max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_communications",
                        to="communication.chatgroup",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_logs",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "communication_logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "communication_type"],
                        name="communicati_school__643716_idx",
                    ),
                    models.Index(
                        fields=["sender", "sent_at"],
                        name="communicati_sender__501452_idx",
                    ),
                    models.Index(
                        fields=["recipient", "sent_at"],
                        name="communicati_recipie_988d3f_idx",
                    ),
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="communicati_referen_4e229f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("sendgrid", "SendGrid"),
                            ("aws_ses", "AWS SES"),
                            ("mailgun", "Mailgun"),
                            ("smtp", "SMTP Server"),
                            ("custom", "Custom Provider"),
                        ],
                        default="sendgrid",
                        max_length=15,
                    ),
                ),
                ("from_email", models.EmailField(max_length=254)),
                ("to_email", models.EmailField(max_length=254)),
                ("cc_emails", models.JSONField(blank=True, default=list)),
                ("bcc_emails", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(max_length=255)),
                ("body_html", models.TextField(blank=True)),
                ("body_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="emails/attachments/"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_integrations",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_integrations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "status"],
                        name="email_integ_school__b131bf_idx",
                    ),
                    models.Index(
                        fields=["to_email", "created_at"],
                        name="email_integ_to_emai_7239c3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="attachments/%Y/%m/"),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name e.g. GroupMessage",
                        max_length=50,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, help_text="Object ID", max_length=255),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_attachments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "file_attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="file_attach_referen_00f0b9_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by", "created_at"],
                        name="file_attach_uploade_198bff_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=10,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="Display name in this group",
                        max_length=100,
                    ),
                ),
                ("is_muted", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="communication.chatgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "group_memberships",
                "ordering": ["-joined_at"],
                "unique_together": {("group", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(fields=["group", "sent_at"], name="group_messa_group_i_ddb782_idx"),
        ),
        migrations.AddIndex(
            model_name="groupmessage",
            index=models.Index(fields=["sender", "sent_at"], name="group_messa_sender__1ee5dc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "user", "emoji")},
        ),
        migrations.AlterUniqueTogether(
            name="parentteacherchat",
            unique_together={("parent", "teacher", "student")},
        ),
        migrations.AddIndex(
            model_name="parentteachermessage",
            index=models.Index(fields=["chat", "sent_at"], name="parent_teac_chat_id_fec2ea_idx"),
        ),
        migrations.AddIndex(
            model_name="parentteachermessage",
            index=models.Index(fields=["sender", "sent_at"], name="parent_teac_sender__19f959_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="readreceipt",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="smsintegration",
            index=models.Index(fields=["school", "status"], name="sms_integra_school__a7d57f_idx"),
        ),
        migrations.AddIndex(
            model_name="smsintegration",
            index=models.Index(
                fields=["to_number", "created_at"],
                name="sms_integra_to_numb_80355a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="typingindicator",
            index=models.Index(fields=["chat_type", "chat_id"], name="typing_indi_chat_ty_9431a3_idx"),
        ),
        migrations.AddIndex(
            model_name="typingindicator",
            index=models.Index(fields=["user", "chat_type"], name="typing_indi_user_id_840ee1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="conferenceparticipant",
            unique_together={("conference", "user")},
        ),
    ]
