# Generated by Django 5.1.15 on 2026-09-01 09:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
        ("communication", "0004_broadcastmessage_chatgroup_groupmessage_and_more"),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                (
                    "announcements",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                (
                    "fee_notices",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                (
                    "attendance_alerts",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        default="sms",
                        max_length=10,
                    ),
                ),
                (
                    "emergency_alerts",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        default="push",
                        max_length=10,
                    ),
                ),
                (
                    "event_reminders",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_preferences",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "communication_preferences",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Email"),
                            ("fee_reminder", "Fee Reminder"),
                            ("event", "Event Invitation"),
                            ("report", "Report Card"),
                            ("absence", "Absence Alert"),
                            ("newsletter", "Newsletter"),
                            ("admission", "Admission"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "body_html",
                    models.TextField(help_text="HTML body with {{variable}} placeholders"),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, help_text="Plain text fallback"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "email_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Template"),
                            ("sms", "SMS Template"),
                            ("push", "Push Notification Template"),
                            ("in_app", "In-App Message"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fee", "Fee Related"),
                            ("attendance", "Attendance"),
                            ("event", "Event"),
                            ("academic", "Academic"),
                            ("general", "General"),
                            ("welcome", "Welcome"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "body",
                    models.TextField(help_text="Message body with {{variable}} placeholders"),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Available template variables",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "message_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=255)),
                ("content_html", models.TextField()),
                ("content_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text="Parents, Staff, Students, All",
                        max_length=50,
                    ),
                ),
                ("target_grades", models.CharField(blank=True, max_length=100)),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("total_opened", models.PositiveIntegerField(default=0)),
                ("total_clicked", models.PositiveIntegerField(default=0)),
                ("total_bounced", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletters",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "newsletters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "options",
                    models.JSONField(default=list, help_text="List of poll options"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Closed")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("target_audience", models.CharField(blank=True, max_length=50)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("allow_multiple_choices", models.BooleanField(default=False)),
                ("max_choices", models.PositiveIntegerField(default=1)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("total_votes", models.PositiveIntegerField(default=0)),
                ("results_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="auth_service.school",
                    ),
                ),
                (
                    "target_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="polls",
                        to="communication.chatgroup",
                    ),
                ),
            ],
            options={
                "db_table": "communication_polls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSGatewayConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("africastalking", "Africa's Talking"),
                            ("nexmo", "Nexmo/Vonage"),
                            ("msg91", "MSG91"),
                            ("custom", "Custom API"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("api_secret", models.CharField(blank=True, max_length=255)),
                ("sender_id", models.CharField(blank=True, max_length=20)),
                ("webhook_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_sms_sent", models.PositiveIntegerField(default=0)),
                (
                    "total_sms_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_gateway_config",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "sms_gateway_configs",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("feedback", "Feedback Survey"),
                            ("satisfaction", "Satisfaction Survey"),
                            ("needs", "Needs Assessment"),
                            ("academic", "Academic Survey"),
                            ("demographic", "Demographic Survey"),
                            ("custom", "Custom Survey"),
                        ],
                        default="feedback",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("analyzed", "Analyzed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("questions", models.JSONField(blank=True, default=list)),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text="Students, Parents, Staff, All",
                        max_length=50,
                    ),
                ),
                ("target_grades", models.CharField(blank=True, max_length=100)),
                ("is_anonymous", models.BooleanField(default=True)),
                ("allow_multiple_responses", models.BooleanField(default=False)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("total_invited", models.PositiveIntegerField(default=0)),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "communication_surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("respondent_type", models.CharField(blank=True, max_length=20)),
                ("answers", models.JSONField(blank=True, default=dict)),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("comments", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="communication.survey",
                    ),
                ),
            ],
            options={
                "db_table": "communication_survey_responses",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("emails_delivered", models.PositiveIntegerField(default=0)),
                ("emails_opened", models.PositiveIntegerField(default=0)),
                ("emails_clicked", models.PositiveIntegerField(default=0)),
                ("emails_bounced", models.PositiveIntegerField(default=0)),
                ("emails_unsubscribed", models.PositiveIntegerField(default=0)),
                ("sms_sent", models.PositiveIntegerField(default=0)),
                ("sms_delivered", models.PositiveIntegerField(default=0)),
                ("sms_failed", models.PositiveIntegerField(default=0)),
                ("push_sent", models.PositiveIntegerField(default=0)),
                ("push_opened", models.PositiveIntegerField(default=0)),
                ("push_failed", models.PositiveIntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "email_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "sms_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_open_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_click_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("top_categories", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_analytics",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "communication_analytics",
                "ordering": ["-period_start"],
                "unique_together": {("school", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="CommunicationBlacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("all", "All Channels"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("newsletter", "Newsletters"),
                            ("fee", "Fee Reminders"),
                            ("event", "Event Notifications"),
                            ("all", "All Categories"),
                        ],
                        default="all",
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_blacklists",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comm_blacklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "communication_blacklists",
                "unique_together": {("user", "channel", "category")},
            },
        ),
        migrations.CreateModel(
            name="EmergencyAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("test", "Test Alert"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("send_email", models.BooleanField(default=True)),
                ("send_sms", models.BooleanField(default=True)),
                ("send_push", models.BooleanField(default=True)),
                (
                    "send_pa",
                    models.BooleanField(default=False, help_text="Play on school PA system"),
                ),
                (
                    "target_audience",
                    models.CharField(
                        default="all",
                        help_text="all, parents, staff, students",
                        max_length=50,
                    ),
                ),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_delivered", models.PositiveIntegerField(default=0)),
                ("total_read", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_alerts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "emergency_alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "alert_level", "status"],
                        name="emergency_a_school__2e0d64_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageDeliveryStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App Message"),
                            ("announcement", "Announcement"),
                            ("broadcast", "Broadcast"),
                            ("direct_message", "Direct Message"),
                            ("group_message", "Group Message"),
                            ("parent_teacher", "Parent-Teacher Chat"),
                            ("video_conference", "Video Conference"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_statuses",
                        to="communication.broadcastmessage",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_statuses",
                        to="communication.notification",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_delivery_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_delivery_statuses",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "message_delivery_statuses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="message_del_recipie_3a2e22_idx",
                    ),
                    models.Index(
                        fields=["notification", "status"],
                        name="message_del_notific_563813_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(blank=True, help_text="daily, weekly, monthly", max_length=50),
                ),
                ("recurrence_end", models.DateField(blank=True, null=True)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("next_execution", models.DateTimeField(blank=True, null=True)),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="communication.announcement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="communication.notification",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_schedules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "notification_schedules",
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "status", "scheduled_at"],
                        name="notificatio_school__8ea3c2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("voter_type", models.CharField(blank=True, max_length=20)),
                (
                    "selected_options",
                    models.JSONField(default=list, help_text="List of selected option indices"),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="communication.poll",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_poll_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "communication_poll_votes",
                "unique_together": {("poll", "student")},
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_phone", models.CharField(max_length=30)),
                ("recipient_name", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sms_logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["school", "status"], name="sms_logs_school__e6842b_idx"),
                    models.Index(fields=["recipient_phone"], name="sms_logs_recipie_f7f060_idx"),
                ],
            },
        ),
    ]
