# Generated by Django 5.2.17 on 2026-08-08 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the incident occurred; defaults to now.",
            ),
        ),
    ]
