# Generated by Django 5.1.15 on 2026-08-31 09:24

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("behavior", "0002_alter_incident_occurred_at"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="follow_up_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="parents_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incident",
            name="parents_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="occurred_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the incident occurred",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="BehaviorAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("custom", "Custom"),
                        ],
                        default="weekly",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_incidents", models.PositiveIntegerField(default=0)),
                ("incidents_by_severity", models.JSONField(blank=True, default=dict)),
                ("incidents_by_type", models.JSONField(blank=True, default=dict)),
                ("incidents_by_grade", models.JSONField(blank=True, default=dict)),
                ("incidents_by_day", models.JSONField(blank=True, default=dict)),
                ("total_points_awarded", models.IntegerField(default=0)),
                ("total_points_deducted", models.IntegerField(default=0)),
                (
                    "average_points_per_student",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_consequences", models.PositiveIntegerField(default=0)),
                ("consequences_by_type", models.JSONField(blank=True, default=dict)),
                ("total_suspension_days", models.PositiveIntegerField(default=0)),
                ("total_detention_hours", models.PositiveIntegerField(default=0)),
                ("top_earners", models.JSONField(blank=True, default=list)),
                (
                    "students_needing_support",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "comparison_to_previous",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Comparison to previous period",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_analytics",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_analytics",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        default="positive",
                        max_length=10,
                    ),
                ),
                (
                    "points_value",
                    models.IntegerField(
                        default=0,
                        help_text="Points awarded/deducted (positive/negative)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_incident",
                    models.BooleanField(
                        default=False,
                        help_text="Does this category require an incident report?",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color code for display",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Icon identifier", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_categories",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_categories",
                "ordering": ["category_type", "name"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.AddField(
            model_name="incident",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="behavior.behaviorcategory",
            ),
        ),
        migrations.CreateModel(
            name="BehaviorConsequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consequence_type",
                    models.CharField(
                        choices=[
                            ("verbal_warning", "Verbal Warning"),
                            ("written_warning", "Written Warning"),
                            ("detention", "Detention"),
                            ("in_school_suspension", "In-School Suspension"),
                            ("out_of_school_suspension", "Out-of-School Suspension"),
                            ("expulsion", "Expulsion"),
                            ("community_service", "Community Service"),
                            ("parent_meeting", "Parent Meeting"),
                            ("loss_of_privileges", "Loss of Privileges"),
                            ("behavior_contract", "Behavior Contract"),
                            ("counseling", "Counseling"),
                            ("other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("appealed", "Appealed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("issued_date", models.DateField(default=django.utils.timezone.now)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "duration_hours",
                    models.PositiveIntegerField(default=0, help_text="Duration in hours (for detention)"),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(default=0, help_text="Duration in days (for suspension)"),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "conditions",
                    models.TextField(blank=True, help_text="Conditions for completion"),
                ),
                ("notes", models.TextField(blank=True)),
                ("parents_notified", models.BooleanField(default=False)),
                ("parents_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequences",
                        to="behavior.incident",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_consequences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_consequences",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequences",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_consequences",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "goals",
                    models.TextField(help_text="Specific goals and expectations"),
                ),
                ("consequences_for_violation", models.TextField()),
                ("rewards_for_compliance", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "review_dates",
                    models.JSONField(blank=True, default=list, help_text="List of review dates"),
                ),
                ("student_signed", models.BooleanField(default=False)),
                ("student_signed_at", models.DateTimeField(blank=True, null=True)),
                ("parent_signed", models.BooleanField(default=False)),
                ("parent_signed_at", models.DateTimeField(blank=True, null=True)),
                ("administrator_signed", models.BooleanField(default=False)),
                (
                    "administrator_signed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("violated", "Violated"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("progress_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="behavior.incident",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_contracts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_contracts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_contracts",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_url", models.URLField(help_text="URL to uploaded file")),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, help_text="File size in bytes"),
                ),
                ("is_confidential", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="behavior.incident",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "behavior_evidence",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("reduce_incidents", "Reduce Incidents"),
                            ("improve_attendance", "Improve Attendance"),
                            ("earn_points", "Earn Behavior Points"),
                            ("complete_consequence", "Complete Consequence"),
                            ("custom", "Custom Goal"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "target_value",
                    models.IntegerField(default=0, help_text="Target number to achieve"),
                ),
                (
                    "current_value",
                    models.IntegerField(default=0, help_text="Current progress"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("achieved", "Achieved"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("support_plan", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_goals",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_goals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_goals",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorMerit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "merit_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Excellence"),
                            ("citizenship", "Good Citizenship"),
                            ("leadership", "Leadership"),
                            ("service", "Community Service"),
                            ("improvement", "Behavior Improvement"),
                            ("attendance", "Perfect Attendance"),
                            ("other", "Other"),
                        ],
                        default="citizenship",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "is_public",
                    models.BooleanField(default=True, help_text="Show on school announcements"),
                ),
                ("certificate_generated", models.BooleanField(default=False)),
                ("awarded_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_merits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merits",
                        to="behavior.incident",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_merits",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merits",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_merits",
                "ordering": ["-awarded_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorPointBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_earned", models.PositiveIntegerField(default=0)),
                ("total_deducted", models.PositiveIntegerField(default=0)),
                ("current_balance", models.IntegerField(default=0)),
                ("lifetime_earned", models.PositiveIntegerField(default=0)),
                ("lifetime_deducted", models.PositiveIntegerField(default=0)),
                ("last_activity_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_balance",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_point_balances",
            },
        ),
        migrations.CreateModel(
            name="BehaviorRubric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("min_score", models.IntegerField(default=1)),
                ("max_score", models.IntegerField(default=5)),
                (
                    "applies_to",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of behavior categories this rubric applies to",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rubrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_rubrics",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_rubrics",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DetentionTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "detention_type",
                    models.CharField(
                        choices=[
                            ("lunch", "Lunch Detention"),
                            ("after_school", "After-School Detention"),
                            ("in_school", "In-School Detention"),
                            ("saturday", "Saturday Detention"),
                            ("other", "Other"),
                        ],
                        default="after_school",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("excused", "Excused"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("attended_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("parents_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detentions",
                        to="behavior.behaviorconsequence",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detentions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detentions",
                        to="students.student",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_detentions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "detention_tracking",
                "ordering": ["scheduled_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="SuspensionTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suspension_type",
                    models.CharField(
                        choices=[
                            ("in_school", "In-School Suspension"),
                            ("out_of_school", "Out-of-School Suspension"),
                            ("expulsion", "Expulsion"),
                        ],
                        default="out_of_school",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("appealed", "Appealed"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("conditions_for_return", models.TextField(blank=True)),
                ("meeting_required", models.BooleanField(default=False)),
                ("meeting_date", models.DateField(blank=True, null=True)),
                ("meeting_notes", models.TextField(blank=True)),
                ("parents_notified", models.BooleanField(default=False)),
                ("parents_notified_at", models.DateTimeField(blank=True, null=True)),
                ("parent_signature_required", models.BooleanField(default=False)),
                ("parent_signature_obtained", models.BooleanField(default=False)),
                ("make_up_work_required", models.BooleanField(default=False)),
                ("make_up_work_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions",
                        to="behavior.behaviorconsequence",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="behavior.incident",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_suspensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "suspension_tracking",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorAppeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appeal_type",
                    models.CharField(
                        choices=[
                            ("incident", "Incident Appeal"),
                            ("consequence", "Consequence Appeal"),
                            ("suspension", "Suspension Appeal"),
                        ],
                        default="incident",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for appeal")),
                ("supporting_evidence", models.TextField(blank=True)),
                ("requested_outcome", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=15,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upheld", "Original Decision Upheld"),
                            ("modified", "Decision Modified"),
                            ("overturned", "Decision Overturned"),
                            ("reduced", "Penalty Reduced"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("decision_notes", models.TextField(blank=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("parent_statement", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("hearing_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals",
                        to="behavior.incident",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_appeals",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_appeals",
                        to="students.student",
                    ),
                ),
                (
                    "consequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals",
                        to="behavior.behaviorconsequence",
                    ),
                ),
                (
                    "suspension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals",
                        to="behavior.suspensiontracking",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_appeals",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="WitnessStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "witness_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("staff", "Staff"),
                            ("parent", "Parent"),
                            ("other", "Other"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("witness_name", models.CharField(max_length=150)),
                ("witness_contact", models.CharField(blank=True, max_length=100)),
                ("statement", models.TextField()),
                ("statement_date", models.DateField(default=django.utils.timezone.now)),
                ("is_confidential", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witness_statements",
                        to="behavior.incident",
                    ),
                ),
                (
                    "witness_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="witness_statements",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "witness_statements",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("critical_incident", "Critical Incident"),
                            ("pattern_detected", "Pattern Detected"),
                            ("escalation", "Escalation"),
                            ("attendance", "Attendance Alert"),
                            ("parent_contact", "Parent Contact Required"),
                            ("follow_up", "Follow-Up Required"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="behavior.incident",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_alerts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_alerts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_alerts",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="behavior_al_status_c0f162_idx",
                    ),
                    models.Index(
                        fields=["student", "created_at"],
                        name="behavior_al_student_9fa9d3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BehaviorPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(help_text="Positive to award, negative to deduct"),
                ),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("earned", "Earned"),
                            ("deducted", "Deducted"),
                            ("adjusted", "Adjusted"),
                        ],
                        default="earned",
                        max_length=10,
                    ),
                ),
                ("reason", models.TextField()),
                ("is_redeemed", models.BooleanField(default=False)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points",
                        to="behavior.behaviorcategory",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points",
                        to="behavior.incident",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_points",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_points",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_points",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "created_at"],
                        name="behavior_po_student_e067b8_idx",
                    ),
                    models.Index(
                        fields=["school", "created_at"],
                        name="behavior_po_school__24f18e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BehaviorRubricLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField()),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("color", models.CharField(default="#007bff", max_length=7)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="behavior.behaviorrubric",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_rubric_levels",
                "ordering": ["score"],
                "unique_together": {("rubric", "score")},
            },
        ),
        migrations.CreateModel(
            name="BehaviorStreak",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "streak_type",
                    models.CharField(
                        choices=[
                            ("no_incidents", "No Incidents"),
                            ("perfect_attendance", "Perfect Attendance"),
                            ("on_time", "On Time"),
                            ("points_earned", "Points Earned"),
                            ("custom", "Custom"),
                        ],
                        default="no_incidents",
                        max_length=20,
                    ),
                ),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                (
                    "streak_unit",
                    models.CharField(default="days", help_text="days, weeks, months", max_length=20),
                ),
                ("streak_started_at", models.DateField()),
                ("last_activity_at", models.DateField()),
                (
                    "milestone_7",
                    models.BooleanField(default=False, help_text="7-day/week milestone achieved"),
                ),
                (
                    "milestone_30",
                    models.BooleanField(default=False, help_text="30-day/month milestone achieved"),
                ),
                (
                    "milestone_90",
                    models.BooleanField(default=False, help_text="90-day/quarter milestone achieved"),
                ),
                (
                    "milestone_180",
                    models.BooleanField(default=False, help_text="180-day/semester milestone achieved"),
                ),
                (
                    "milestone_365",
                    models.BooleanField(default=False, help_text="365-day/year milestone achieved"),
                ),
                ("reward_earned", models.BooleanField(default=False)),
                ("reward_description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_streaks",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_streaks",
                "ordering": ["-current_streak"],
                "unique_together": {("student", "streak_type")},
            },
        ),
        migrations.CreateModel(
            name="DigitalHallPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("bathroom", "Bathroom"),
                            ("nurse", "Nurse"),
                            ("counselor", "Counselor"),
                            ("administration", "Administration"),
                            ("library", "Library"),
                            ("other_class", "Other Class"),
                            ("office", "Office"),
                            ("other", "Other"),
                        ],
                        default="bathroom",
                        max_length=20,
                    ),
                ),
                ("from_class", models.CharField(blank=True, max_length=100)),
                ("to_destination", models.CharField(max_length=100)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expected_return_at", models.DateTimeField(blank=True, null=True)),
                ("actual_return_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("denied", "Denied"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("minutes_late", models.PositiveIntegerField(default=0)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_hall_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_passes",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hall_passes",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "digital_hall_passes",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "issued_at"],
                        name="digital_hal_student_e1cbbd_idx",
                    ),
                    models.Index(fields=["status"], name="digital_hal_status_128d16_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParentNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("incident", "Incident Report"),
                            ("consequence", "Consequence Notice"),
                            ("suspension", "Suspension Notice"),
                            ("meeting", "Meeting Request"),
                            ("goal_update", "Goal Update"),
                            ("positive", "Positive Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("phone", "Phone Call"),
                            ("letter", "Letter"),
                            ("in_app", "In-App Notification"),
                        ],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("parent_email", models.EmailField(blank=True, max_length=254)),
                ("parent_phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("parent_response", models.TextField(blank=True)),
                ("response_received_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_notifications",
                        to="behavior.behaviorconsequence",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_notifications",
                        to="behavior.incident",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_notifications",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_parent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_notifications",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "parent_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "notification_type"],
                        name="parent_noti_status_9a9308_idx",
                    ),
                    models.Index(
                        fields=["student", "created_at"],
                        name="parent_noti_student_a0be7c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TardyTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tardy_type",
                    models.CharField(
                        choices=[
                            ("excused", "Excused"),
                            ("unexcused", "Unexcused"),
                            ("medical", "Medical"),
                            ("family", "Family Emergency"),
                            ("transportation", "Transportation"),
                        ],
                        default="unexcused",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "scheduled_time",
                    models.TimeField(help_text="When class was supposed to start"),
                ),
                (
                    "arrival_time",
                    models.TimeField(help_text="When student actually arrived"),
                ),
                ("minutes_late", models.PositiveIntegerField(default=0)),
                ("class_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded"),
                            ("excused", "Excused"),
                            ("appealed", "Appealed"),
                        ],
                        default="recorded",
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("parent_contacted", models.BooleanField(default=False)),
                ("is_part_of_pattern", models.BooleanField(default=False)),
                ("pattern_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tardies",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tardies",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_tardies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tardy_tracking",
                "ordering": ["-date", "arrival_time"],
                "indexes": [
                    models.Index(
                        fields=["student", "date"],
                        name="tardy_track_student_eace12_idx",
                    ),
                    models.Index(fields=["tardy_type"], name="tardy_track_tardy_t_5f797b_idx"),
                ],
            },
        ),
    ]
