# Generated by Django 5.1.15 on 2026-08-31 09:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("behavior", "0003_incident_follow_up_date_incident_follow_up_notes_and_more"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorHouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(default="#007bff", help_text="Hex color code", max_length=7),
                ),
                ("mascot", models.CharField(blank=True, max_length=100)),
                ("total_points", models.IntegerField(default=0)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "captain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_captain_of",
                        to="students.student",
                    ),
                ),
                (
                    "faculty_advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_advised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_houses",
                        to="auth_service.school",
                    ),
                ),
                (
                    "vice_captain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_vice_captain_of",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_houses",
                "ordering": ["-total_points", "name"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorInterventionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("bip", "Behavior Intervention Plan"),
                            ("fba", "Functional Behavior Assessment"),
                            ("safety_plan", "Safety Plan"),
                            ("behavior_support", "Behavior Support Plan"),
                            ("other", "Other"),
                        ],
                        default="bip",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "target_behavior",
                    models.TextField(blank=True, help_text="Observable behavior to be changed"),
                ),
                (
                    "antecedents",
                    models.TextField(blank=True, help_text="What happens before the behavior"),
                ),
                (
                    "behaviors",
                    models.TextField(blank=True, help_text="The behavior itself"),
                ),
                (
                    "consequences",
                    models.TextField(blank=True, help_text="What happens after the behavior"),
                ),
                (
                    "function_of_behavior",
                    models.TextField(blank=True, help_text="Why the behavior occurs"),
                ),
                ("prevention_strategies", models.TextField(blank=True)),
                ("teaching_strategies", models.TextField(blank=True)),
                ("reinforcement_strategies", models.TextField(blank=True)),
                ("crisis_plan", models.TextField(blank=True)),
                (
                    "team_members",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of team member names/roles",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "review_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=15,
                    ),
                ),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "goals_met",
                    models.JSONField(blank=True, default=list, help_text="List of achieved goals"),
                ),
                (
                    "goals_remaining",
                    models.JSONField(blank=True, default=list, help_text="List of remaining goals"),
                ),
                ("progress_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("under_review", "Under Review"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("parent_signature_required", models.BooleanField(default=True)),
                ("parent_signed", models.BooleanField(default=False)),
                ("parent_signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_intervention_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_intervention_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_intervention_plans",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_plans",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_intervention_plans",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorLeaderboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("class", "Class"),
                            ("house", "House"),
                            ("grade", "Grade"),
                            ("overall", "Overall"),
                        ],
                        default="individual",
                        max_length=15,
                    ),
                ),
                (
                    "time_period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semester", "Semester"),
                            ("annual", "Annual"),
                            ("all_time", "All Time"),
                        ],
                        default="monthly",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leaderboard_data",
                    models.JSONField(blank=True, default=list, help_text="List of ranked entries"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("show_on_dashboard", models.BooleanField(default=True)),
                ("total_entries", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_leaderboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_leaderboards",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_leaderboards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorMTSS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier_level",
                    models.CharField(
                        choices=[
                            ("tier_1", "Tier 1 - Universal"),
                            ("tier_2", "Tier 2 - Targeted"),
                            ("tier_3", "Tier 3 - Intensive"),
                        ],
                        default="tier_1",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("monitoring", "Monitoring"),
                            ("progressing", "Progressing"),
                            ("referral", "Referral"),
                            ("exited", "Exited"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("referral_reason", models.TextField()),
                ("referral_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "interventions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of interventions applied",
                    ),
                ),
                (
                    "supports",
                    models.JSONField(blank=True, default=list, help_text="List of supports provided"),
                ),
                ("goals", models.JSONField(blank=True, default=list)),
                (
                    "progress_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Data points tracking progress",
                    ),
                ),
                ("baseline_date", models.DateField(blank=True, null=True)),
                ("baseline_notes", models.TextField(blank=True)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("team_members", models.JSONField(blank=True, default=list)),
                ("outcome_notes", models.TextField(blank=True)),
                ("outcome_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mtss_case_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mtss_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_mtss",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mtss_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_mtss",
                "ordering": ["-referral_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Item"),
                            ("privilege", "Privilege"),
                            ("experience", "Experience"),
                            ("certificate", "Certificate"),
                            ("digital", "Digital"),
                            ("other", "Other"),
                        ],
                        default="privilege",
                        max_length=15,
                    ),
                ),
                (
                    "points_cost",
                    models.PositiveIntegerField(help_text="Points required to redeem"),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("always", "Always Available"),
                            ("limited", "Limited Stock"),
                            ("seasonal", "Seasonal"),
                            ("event", "Event Only"),
                        ],
                        default="always",
                        max_length=15,
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                (
                    "max_per_student",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited per student"),
                ),
                ("total_redeemed", models.PositiveIntegerField(default=0)),
                ("image_url", models.URLField(blank=True)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("available_until", models.DateField(blank=True, null=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_rewards",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_rewards",
                "ordering": ["points_cost", "name"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorPointsRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "points_spent",
                    models.PositiveIntegerField(help_text="Points spent on this redemption"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fulfilled_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_redemptions",
                        to="students.student",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="behavior.behaviorreward",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_points_redemptions",
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorStaffDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("incidents_today", models.PositiveIntegerField(default=0)),
                ("points_given_today", models.IntegerField(default=0)),
                ("referrals_received_today", models.PositiveIntegerField(default=0)),
                ("hall_passes_active", models.PositiveIntegerField(default=0)),
                ("incidents_this_week", models.PositiveIntegerField(default=0)),
                ("points_given_this_week", models.IntegerField(default=0)),
                (
                    "class_points_data",
                    models.JSONField(blank=True, default=list, help_text="Points by class period"),
                ),
                ("top_students", models.JSONField(blank=True, default=list)),
                (
                    "students_needing_attention",
                    models.JSONField(blank=True, default=list),
                ),
                ("pending_alerts", models.PositiveIntegerField(default=0)),
                ("pending_referrals", models.PositiveIntegerField(default=0)),
                (
                    "recent_actions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recent behavior actions taken",
                    ),
                ),
                ("favorite_quick_actions", models.JSONField(blank=True, default=list)),
                ("last_refreshed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_staff_dashboards",
                        to="auth_service.school",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_dashboard",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "behavior_staff_dashboards",
            },
        ),
        migrations.CreateModel(
            name="SELCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("great", "Great"),
                            ("good", "Good"),
                            ("okay", "Okay"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                            ("anxious", "Anxious"),
                            ("sick", "Sick"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "energy_level",
                    models.PositiveSmallIntegerField(default=5, help_text="1-10 scale"),
                ),
                (
                    "stress_level",
                    models.PositiveSmallIntegerField(default=5, help_text="1-10 scale"),
                ),
                (
                    "how_are_you_feeling",
                    models.TextField(blank=True, help_text="Why do you feel this way?"),
                ),
                ("anything_else", models.TextField(blank=True)),
                ("needs_help", models.BooleanField(default=False)),
                (
                    "help_type",
                    models.CharField(blank=True, help_text="What kind of help?", max_length=100),
                ),
                (
                    "sleep_quality",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-10 scale", null=True),
                ),
                ("ate_breakfast", models.BooleanField(blank=True, null=True)),
                ("staff_response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_completed", models.BooleanField(default=False)),
                ("check_in_date", models.DateField(default=django.utils.timezone.now)),
                ("check_in_time", models.TimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sel_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_checkins",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_checkins",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "sel_checkins",
                "ordering": ["-check_in_date", "-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="SELCheckInResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("response", models.TextField()),
                ("action_taken", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_responses",
                        to="behavior.selcheckin",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_checkin_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sel_checkin_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorHouseMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("captain", "Captain"),
                            ("vice_captain", "Vice Captain"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=15,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="behavior.behaviorhouse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_memberships",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_house_members",
                "ordering": ["role", "-joined_at"],
                "unique_together": {("house", "student")},
            },
        ),
        migrations.CreateModel(
            name="BehaviorReportCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_period",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semester", "Semester"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_incidents", models.PositiveIntegerField(default=0)),
                ("total_merits", models.PositiveIntegerField(default=0)),
                ("total_points_earned", models.IntegerField(default=0)),
                ("total_points_deducted", models.IntegerField(default=0)),
                ("net_points", models.IntegerField(default=0)),
                ("total_detentions", models.PositiveIntegerField(default=0)),
                ("total_suspensions", models.PositiveIntegerField(default=0)),
                ("total_tardies", models.PositiveIntegerField(default=0)),
                (
                    "behavior_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "behavior_trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(blank=True, default=list, help_text="List of strengths observed"),
                ),
                (
                    "areas_for_growth",
                    models.JSONField(blank=True, default=list, help_text="Areas needing improvement"),
                ),
                ("teacher_comments", models.TextField(blank=True)),
                ("admin_comments", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("sent_to_parent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_report_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_report_cards",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_report_cards",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_report_cards",
                "ordering": ["-start_date"],
                "unique_together": {("student", "report_period", "start_date")},
            },
        ),
        migrations.AddIndex(
            model_name="selcheckin",
            index=models.Index(
                fields=["student", "check_in_date"],
                name="sel_checkin_student_add423_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="selcheckin",
            index=models.Index(fields=["mood"], name="sel_checkin_mood_f9154d_idx"),
        ),
    ]
