# Generated by Django 5.1.15 on 2026-08-31 10:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("behavior", "0004_behaviorhouse_behaviorinterventionplan_and_more"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorAcademicCorrelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_type",
                    models.CharField(
                        choices=[
                            ("gpa_impact", "GPA Impact"),
                            ("grade_trend", "Grade Trend"),
                            ("class_performance", "Class Performance"),
                            ("assignment_completion", "Assignment Completion"),
                        ],
                        default="gpa_impact",
                        max_length=25,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "behavior_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_incidents", models.PositiveIntegerField(default=0)),
                ("total_merits", models.PositiveIntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                (
                    "gpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "gpa_change",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                (
                    "grade_average",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "assignment_completion_rate",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "correlation_strength",
                    models.CharField(
                        choices=[
                            ("strong", "Strong"),
                            ("moderate", "Moderate"),
                            ("weak", "Weak"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_academic_correlations",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_correlations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_academic_correlations",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorAttendanceLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("tardy_behavior", "Tardy as Behavior"),
                            ("absence_behavior", "Absence as Behavior"),
                            ("attendance_reward", "Attendance Reward"),
                            ("attendance_consequence", "Attendance Consequence"),
                        ],
                        default="tardy_behavior",
                        max_length=25,
                    ),
                ),
                (
                    "attendance_record_id",
                    models.UUIDField(help_text="Reference to attendance record"),
                ),
                ("attendance_date", models.DateField()),
                ("points_adjusted", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "behavior_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_links",
                        to="behavior.behaviorpoint",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_links",
                        to="behavior.incident",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_attendance_links",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_attendance_links",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_attendance_links",
                "ordering": ["-attendance_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorAutoEscalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("incident_count", "Incident Count"),
                            ("point_threshold", "Point Threshold"),
                            ("consecutive_days", "Consecutive Days"),
                            ("same_type", "Same Incident Type"),
                            ("severity", "Severity Level"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_value",
                    models.PositiveIntegerField(help_text="Threshold value"),
                ),
                (
                    "trigger_window_days",
                    models.PositiveIntegerField(default=30, help_text="Look back period in days"),
                ),
                (
                    "incident_type_filter",
                    models.CharField(blank=True, help_text="Specific incident type", max_length=50),
                ),
                (
                    "severity_filter",
                    models.CharField(blank=True, help_text="Minimum severity level", max_length=10),
                ),
                (
                    "escalation_action",
                    models.CharField(
                        choices=[
                            ("warning", "Warning"),
                            ("parent_contact", "Parent Contact"),
                            ("detention", "Detention"),
                            ("suspension", "Suspension"),
                            ("meeting", "Meeting Required"),
                            ("intervention", "Intervention Plan"),
                            ("counseling", "Counseling"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, help_text="Higher priority checked first"),
                ),
                ("times_triggered", models.PositiveIntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_auto_escalations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_auto_escalations",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("incident_free", "Incident-Free Streak"),
                            ("points_milestone", "Points Milestone"),
                            ("attendance", "Perfect Attendance"),
                            ("improvement", "Behavior Improvement"),
                            ("leadership", "Leadership"),
                            ("service", "Community Service"),
                            ("academic", "Academic Excellence"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("criteria_description", models.TextField(blank=True)),
                ("points_required", models.PositiveIntegerField(default=0)),
                ("streak_required", models.PositiveIntegerField(default=0)),
                (
                    "incidents_allowed",
                    models.PositiveIntegerField(default=0, help_text="Max incidents allowed to earn"),
                ),
                ("icon_url", models.URLField(blank=True)),
                ("color", models.CharField(default="#FFD700", max_length=7)),
                ("total_earned", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_hidden",
                    models.BooleanField(default=False, help_text="Hidden until earned"),
                ),
                (
                    "points_value",
                    models.PositiveIntegerField(default=0, help_text="Points awarded when earned"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_badges",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_badges",
                "ordering": ["badge_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorDataVisualization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("incidents_by_type", "Incidents by Type"),
                            ("incidents_by_severity", "Incidents by Severity"),
                            ("incidents_by_grade", "Incidents by Grade"),
                            ("incidents_by_month", "Incidents by Month"),
                            ("points_distribution", "Points Distribution"),
                            ("top_earners", "Top Point Earners"),
                            ("behavior_trends", "Behavior Trends"),
                            ("house_rankings", "House Rankings"),
                            ("teacher_comparison", "Teacher Comparison"),
                            ("student_timeline", "Student Timeline"),
                        ],
                        max_length=25,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("chart_data", models.JSONField(blank=True, default=dict)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("datasets", models.JSONField(blank=True, default=list)),
                ("date_range_start", models.DateField(blank=True, null=True)),
                ("date_range_end", models.DateField(blank=True, null=True)),
                ("grade_filter", models.CharField(blank=True, max_length=20)),
                ("is_public", models.BooleanField(default=True)),
                ("refresh_interval_hours", models.PositiveIntegerField(default=24)),
                ("last_refreshed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_data_visualizations",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "behavior_data_visualizations",
                "ordering": ["chart_type"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorEscalationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trigger_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data that triggered the escalation",
                    ),
                ),
                ("action_taken", models.TextField(blank=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "action_taken_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalation_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="behavior.behaviorautoescalation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_logs",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_escalation_logs",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorPolicyTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("code_of_conduct", "Code of Conduct"),
                            ("discipline", "Discipline Policy"),
                            ("bullying", "Anti-Bullying"),
                            ("technology", "Technology Use"),
                            ("attendance", "Attendance Policy"),
                            ("dress_code", "Dress Code"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Policy document content")),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                (
                    "is_template",
                    models.BooleanField(default=True, help_text="Can be customized by schools"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policy_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_policy_templates",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_policy_templates",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorPredictiveAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("behavior_risk", "Behavior Risk"),
                            ("dropout_risk", "Dropout Risk"),
                            ("academic_risk", "Academic Risk"),
                            ("attendance_risk", "Attendance Risk"),
                        ],
                        default="behavior_risk",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="0-100 risk score",
                        max_digits=5,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of contributing factors",
                    ),
                ),
                (
                    "protective_factors",
                    models.JSONField(blank=True, default=list, help_text="List of protective factors"),
                ),
                ("predicted_outcome", models.TextField(blank=True)),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "recommended_interventions",
                    models.JSONField(blank=True, default=list),
                ),
                ("recommended_actions", models.TextField(blank=True)),
                ("prediction_date", models.DateField(auto_now_add=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_predictive_analytics",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictive_analytics",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_predictive_analytics",
                "ordering": ["-risk_score"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorSMSAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("critical_incident", "Critical Incident"),
                            ("suspension", "Suspension"),
                            ("violent_incident", "Violent Incident"),
                            ("substance", "Substance Violation"),
                            ("bullying", "Bullying"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("parent_phone", models.CharField(max_length=20)),
                ("parent_name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_alerts",
                        to="behavior.incident",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_sms_alerts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_sms_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_alerts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_sms_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorStreakChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("incident_free", "Incident-Free Streak"),
                            ("perfect_attendance", "Perfect Attendance"),
                            ("on_time", "On Time Streak"),
                            ("points_earned", "Points Earned"),
                            ("custom", "Custom Challenge"),
                        ],
                        default="incident_free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=15,
                    ),
                ),
                (
                    "target_streak",
                    models.PositiveIntegerField(help_text="Target streak length"),
                ),
                ("streak_unit", models.CharField(default="days", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("completion_reward_points", models.PositiveIntegerField(default=0)),
                (
                    "top_reward_points",
                    models.PositiveIntegerField(default=0, help_text="Extra points for top performers"),
                ),
                ("total_participants", models.PositiveIntegerField(default=0)),
                ("total_completions", models.PositiveIntegerField(default=0)),
                ("leaderboard", models.JSONField(blank=True, default=list)),
                ("is_class_competition", models.BooleanField(default=False)),
                ("is_house_competition", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completion_reward_badge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="streak_challenges",
                        to="behavior.behaviorbadge",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_streak_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_streak_challenges",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_streak_challenges",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorTrainingMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Video"),
                            ("presentation", "Presentation"),
                            ("course", "Online Course"),
                            ("workshop", "Workshop"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=15,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all_staff", "All Staff"),
                            ("teachers", "Teachers"),
                            ("administrators", "Administrators"),
                            ("counselors", "Counselors"),
                            ("support_staff", "Support Staff"),
                        ],
                        default="all_staff",
                        max_length=15,
                    ),
                ),
                ("file_url", models.URLField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                ("content_text", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("completions_count", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_training_materials",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_training_materials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SELSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("wellness", "Wellness Check"),
                            ("mood", "Mood Assessment"),
                            ("stress", "Stress Assessment"),
                            ("belonging", "School Belonging"),
                            ("safety", "Safety Perception"),
                            ("support", "Support Systems"),
                            ("custom", "Custom Survey"),
                        ],
                        default="wellness",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "questions",
                    models.JSONField(blank=True, default=list, help_text="List of survey questions"),
                ),
                ("target_grades", models.JSONField(blank=True, default=list)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("average_scores", models.JSONField(blank=True, default=dict)),
                ("is_anonymous", models.BooleanField(default=True)),
                ("allow_multiple_submissions", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sel_surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_surveys",
                        to="auth_service.school",
                    ),
                ),
                (
                    "target_students",
                    models.ManyToManyField(blank=True, related_name="sel_surveys", to="students.student"),
                ),
            ],
            options={
                "db_table": "sel_surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorBadgeAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("notified", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("shared_to_feed", models.BooleanField(default=False)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_behavior_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="behavior.behaviorbadge",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_awards",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_badge_awards",
                "ordering": ["-awarded_at"],
                "unique_together": {("badge", "student")},
            },
        ),
        migrations.CreateModel(
            name="BehaviorParentPortal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("view_only", "View Only"),
                            ("view_communicate", "View and Communicate"),
                            ("full_access", "Full Access"),
                        ],
                        default="view_only",
                        max_length=20,
                    ),
                ),
                ("show_incidents", models.BooleanField(default=True)),
                ("show_points", models.BooleanField(default=True)),
                ("show_consequences", models.BooleanField(default=True)),
                ("show_report_cards", models.BooleanField(default=True)),
                ("show_merits", models.BooleanField(default=True)),
                ("show_streaks", models.BooleanField(default=True)),
                ("show_goals", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=False)),
                ("notify_on_incident", models.BooleanField(default=True)),
                ("notify_on_consequence", models.BooleanField(default=True)),
                ("notify_on_positive", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_parent_portals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_parent_portals",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_behavior_portals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_parent_portals",
                "ordering": ["-created_at"],
                "unique_together": {("parent_user", "student")},
            },
        ),
        migrations.CreateModel(
            name="BehaviorTrainingCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="behavior.behaviortrainingmaterial",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_training_completions",
                "ordering": ["-completed_at"],
                "unique_together": {("material", "staff")},
            },
        ),
        migrations.CreateModel(
            name="SELSurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "responses",
                    models.JSONField(default=dict, help_text="Question-ID to answer mapping"),
                ),
                (
                    "overall_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("needs_follow_up", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("follow_up_completed", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sel_survey_responses",
                        to="students.student",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="behavior.selsurvey",
                    ),
                ),
            ],
            options={
                "db_table": "sel_survey_responses",
                "ordering": ["-submitted_at"],
                "unique_together": {("survey", "student")},
            },
        ),
    ]
