# Generated by Django 5.1.15 on 2026-09-01 07:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0012_versioning_and_course_catalog"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("reporting", "0001_initial"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicPerformanceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "highest_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "lowest_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "pass_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.classroom",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_performance_reports",
                        to="auth_service.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "report_academic_performance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("government", "Government Reporting"),
                            ("accreditation", "Accreditation"),
                            ("insurance", "Insurance"),
                            ("financial", "Financial Compliance"),
                            ("safety", "Safety Compliance"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                ("submitted_to", models.CharField(blank=True, max_length=200)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "report_compliance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_teachers", models.PositiveIntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "report_department",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeTrendReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("over_time", "Over Time"),
                            ("by_subject", "By Subject"),
                            ("by_class", "By Class"),
                            ("by_student", "By Student"),
                            ("comparison", "Comparison"),
                        ],
                        default="over_time",
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                (
                    "trend_direction",
                    models.CharField(
                        blank=True,
                        help_text="improving, declining, stable",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.grade",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_trend_reports",
                        to="auth_service.school",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "db_table": "report_grade_trends",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("parent", "Parent"),
                            ("teacher", "Teacher"),
                            ("admin", "Admin"),
                            ("external", "External"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("download", "Download"),
                            ("edit", "Edit"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("report_url", models.URLField(blank=True, max_length=500)),
                ("report_data", models.JSONField(blank=True, default=dict)),
                (
                    "shared_with",
                    models.JSONField(blank=True, default=list, help_text="List of user IDs or emails"),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("password_protected", models.BooleanField(default=False)),
                ("access_password", models.CharField(blank=True, max_length=100)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_shares",
                        to="auth_service.school",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Performance"),
                            ("attendance", "Attendance"),
                            ("fee", "Fee Collection"),
                            ("enrollment", "Enrollment"),
                            ("discipline", "Discipline"),
                            ("health", "Health"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Report configuration as JSON",
                    ),
                ),
                (
                    "columns",
                    models.JSONField(blank=True, default=list, help_text="List of column definitions"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=list, help_text="Available filter options"),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_templates",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "report_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Performance"),
                            ("attendance", "Attendance"),
                            ("fee", "Fee Collection"),
                            ("enrollment", "Enrollment"),
                            ("discipline", "Discipline"),
                            ("health", "Health"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("dashboard", "Dashboard"),
                            ("both", "Both"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of recipient user IDs or emails",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Report configuration as JSON",
                    ),
                ),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("next_generation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "report_scheduled_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentProgressTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "progress_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Progress"),
                            ("behavioral", "Behavioral Progress"),
                            ("attendance", "Attendance Progress"),
                            ("overall", "Overall Progress"),
                        ],
                        default="overall",
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("areas_for_improvement", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress_tracking",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_progress_tracking",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "report_student_progress",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherPerformanceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                (
                    "average_class_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "student_satisfaction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("classes_taught", models.PositiveIntegerField(default=0)),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_performance_reports",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_performance_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_teacher_performance",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YearOverYearReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                (
                    "enrollment_change",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "performance_change",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "attendance_change",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yoy_from",
                        to="students.academicyear",
                    ),
                ),
                (
                    "academic_year_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yoy_to",
                        to="students.academicyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_over_year_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "report_year_over_year",
                "ordering": ["-created_at"],
            },
        ),
    ]
