# Generated by Django 5.1.15 on 2026-09-01 11:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_service",
            "0007_ipgeolocationcache_permission_auditreportschedule_and_more",
        ),
        ("reporting", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar Chart"),
                            ("line", "Line Chart"),
                            ("pie", "Pie Chart"),
                            ("doughnut", "Doughnut Chart"),
                            ("scatter", "Scatter Plot"),
                            ("area", "Area Chart"),
                            ("heatmap", "Heat Map"),
                            ("table", "Data Table"),
                        ],
                        max_length=10,
                    ),
                ),
                ("data_source", models.CharField(max_length=100)),
                ("query", models.TextField(blank=True, help_text="SQL or API query")),
                ("colors", models.JSONField(blank=True, default=list)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_configurations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_chart_configurations",
            },
        ),
        migrations.CreateModel(
            name="CustomReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "data_sources",
                    models.JSONField(default=list, help_text="List of data sources/models"),
                ),
                ("default_filters", models.JSONField(blank=True, default=dict)),
                ("available_filters", models.JSONField(blank=True, default=list)),
                (
                    "columns",
                    models.JSONField(default=list, help_text="Report columns configuration"),
                ),
                ("default_sort", models.JSONField(blank=True, default=dict)),
                ("group_by", models.JSONField(blank=True, default=list)),
                ("aggregations", models.JSONField(blank=True, default=list)),
                ("chart_config", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("viewable_roles", models.JSONField(blank=True, default=list)),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_custom_reports",
            },
        ),
        migrations.CreateModel(
            name="CustomReportExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "result_file",
                    models.FileField(blank=True, null=True, upload_to="reporting/custom/"),
                ),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_seconds",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reporting.customreport",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_custom_report_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("columns", models.PositiveIntegerField(default=2)),
                ("theme", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_dashboard_configs",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart", "Chart"),
                            ("table", "Table"),
                            ("kpi", "KPI Card"),
                            ("map", "Map"),
                            ("list", "List"),
                            ("calendar", "Calendar"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="API endpoint or data query",
                        max_length=100,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=300)),
                ("position_x", models.PositiveIntegerField(default=0)),
                ("position_y", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=1)),
                ("height", models.PositiveIntegerField(default=1)),
                ("is_default", models.BooleanField(default=False)),
                ("visible_to_roles", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_dashboard_widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="KPIDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("financial", "Financial"),
                            ("operations", "Operations"),
                            ("student_life", "Student Life"),
                            ("staff", "Staff"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("percentage", "Percentage"),
                            ("currency", "Currency"),
                            ("ratio", "Ratio"),
                        ],
                        max_length=15,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "min_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "max_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "warning_threshold",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "critical_threshold",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "formula",
                    models.TextField(blank=True, help_text="How to calculate this KPI"),
                ),
                ("data_source", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_definitions",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_kpi_definitions",
            },
        ),
        migrations.CreateModel(
            name="ReportAccessControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                ("role", models.CharField(blank=True, max_length=50)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Edit"),
                            ("admin", "Full Access"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_access_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_access_controls",
            },
        ),
        migrations.CreateModel(
            name="ReportAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Breach"),
                            ("trend", "Trend Alert"),
                            ("anomaly", "Anomaly Detection"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("triggered", "Triggered"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("metric", models.CharField(max_length=100)),
                (
                    "threshold_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notify_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_alerts",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_alerts",
            },
        ),
        migrations.CreateModel(
            name="ReportBookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                ("report_id", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("saved_filters", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_bookmarks",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ReportComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("report_type", models.CharField(max_length=50)),
                ("period_a_start", models.DateField()),
                ("period_a_end", models.DateField()),
                ("period_b_start", models.DateField()),
                ("period_b_end", models.DateField()),
                ("comparison_data", models.JSONField(default=dict)),
                ("highlights", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_comparisons",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_comparisons",
            },
        ),
        migrations.CreateModel(
            name="ReportDataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("model", "Django Model"),
                            ("view", "Database View"),
                            ("api", "External API"),
                            ("sql", "Raw SQL"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "model_path",
                    models.CharField(blank=True, help_text="e.g., students.Student", max_length=200),
                ),
                ("view_name", models.CharField(blank=True, max_length=200)),
                ("api_url", models.URLField(blank=True, max_length=500)),
                ("sql_query", models.TextField(blank=True)),
                ("fields", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_data_sources",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_data_sources",
            },
        ),
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("excel", "Excel")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="reporting/exports/"),
                ),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_exports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_exports",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_shared", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="reporting.reportfolder",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_folders",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_folders",
            },
        ),
        migrations.CreateModel(
            name="ReportFolderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("report", "Report"),
                            ("folder", "Sub-folder"),
                            ("bookmark", "Bookmark"),
                        ],
                        max_length=10,
                    ),
                ),
                ("item_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reporting.reportfolder",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_folder_items",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ReportHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="reporting/history/"),
                ),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                ("format", models.CharField(default="pdf", max_length=10)),
                ("filters_applied", models.JSONField(blank=True, default=dict)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("record_count", models.PositiveIntegerField(default=0)),
                (
                    "generation_time_seconds",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_history",
                        to="auth_service.school",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportEmailDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_email_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_deliveries",
                        to="reporting.reporthistory",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_email_deliveries",
            },
        ),
        migrations.CreateModel(
            name="ReportComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="reporting.reportcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reporting.reporthistory",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("download", "Download"),
                            ("share", "Share"),
                            ("export", "Export"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="reporting.reporthistory",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_access_logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("trend", "Trend Insight"),
                            ("anomaly", "Anomaly"),
                            ("recommendation", "Recommendation"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("metric", models.CharField(blank=True, max_length=100)),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "change_percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("priority", models.CharField(default="medium", max_length=10)),
                ("is_read", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_insights",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_insights",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("report_type", models.CharField(max_length=50)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("day_of_week", models.CharField(blank=True, max_length=10)),
                ("day_of_month", models.PositiveIntegerField(blank=True, null=True)),
                ("time_of_day", models.TimeField()),
                ("email_delivery", models.BooleanField(default=True)),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("excel", "Excel")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("next_generation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_schedules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_schedules",
            },
        ),
        migrations.AddField(
            model_name="reporthistory",
            name="scheduled",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reporting.reportschedule",
            ),
        ),
        migrations.CreateModel(
            name="ReportScheduleDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reporting.reporthistory",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="reporting.reportschedule",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_schedule_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplateParameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "param_type",
                    models.CharField(
                        choices=[
                            ("date", "Date"),
                            ("select", "Dropdown"),
                            ("text", "Text Input"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("default_value", models.CharField(blank=True, max_length=200)),
                ("options", models.JSONField(blank=True, default=list)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="reporting.reporttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_template_parameters",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ReportVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("config_snapshot", models.JSONField(default=dict)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="reporting.reporttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "snapshot_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("term", "Term"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("data", models.JSONField(default=dict)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_staff", models.PositiveIntegerField(default=0)),
                (
                    "avg_attendance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_gpa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "pass_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("new_enrollments", models.PositiveIntegerField(default=0)),
                ("dropouts", models.PositiveIntegerField(default=0)),
                (
                    "retention_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_snapshots",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_analytics_snapshots",
                "ordering": ["-snapshot_date"],
                "unique_together": {("school", "snapshot_type", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="DashboardWidgetPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("custom_config", models.JSONField(blank=True, default=dict)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="reporting.dashboardconfiguration",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="reporting.dashboardwidget",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_dashboard_widget_placements",
                "unique_together": {("dashboard", "widget")},
            },
        ),
        migrations.CreateModel(
            name="KPIValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("target_met", models.BooleanField(default=False)),
                (
                    "trend",
                    models.CharField(blank=True, help_text="up, down, stable", max_length=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="reporting.kpidefinition",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_kpi_values",
                "ordering": ["-date"],
                "unique_together": {("kpi", "date")},
            },
        ),
        migrations.CreateModel(
            name="ReportAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_reports_generated", models.PositiveIntegerField(default=0)),
                ("total_reports_viewed", models.PositiveIntegerField(default=0)),
                ("total_reports_exported", models.PositiveIntegerField(default=0)),
                ("by_type_breakdown", models.JSONField(blank=True, default=dict)),
                ("top_reports", models.JSONField(blank=True, default=list)),
                ("active_users", models.PositiveIntegerField(default=0)),
                (
                    "avg_generation_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_usage_analytics",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_usage_analytics",
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="ReportDataCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cache_key", models.CharField(max_length=255, unique=True)),
                ("report_type", models.CharField(max_length=50)),
                ("data", models.JSONField(default=dict)),
                ("data_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("hit_count", models.PositiveIntegerField(default=0)),
                ("last_hit_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_data_caches",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_data_caches",
                "indexes": [
                    models.Index(
                        fields=["cache_key", "expires_at"],
                        name="reporting_d_cache_k_d50c81_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                ("report_name", models.CharField(max_length=200)),
                ("report_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_favorites",
                "unique_together": {("user", "report_type", "report_name")},
            },
        ),
        migrations.CreateModel(
            name="ReportSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_type", models.CharField(max_length=50)),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("new_data", "New Data Available"),
                            ("threshold", "Threshold Breached"),
                            ("scheduled", "Scheduled Report Ready"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_update_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reporting_subscriptions",
                "unique_together": {("user", "report_type", "update_type")},
            },
        ),
    ]
