# Generated by Django 4.2.13 on 2026-07-13 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0003_emailverificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorBackupCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hashed_code", models.CharField(db_index=True, max_length=64)),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "two_factor_backup_codes",
                "indexes": [
                    models.Index(
                        fields=["user", "hashed_code"],
                        name="two_factor__user_id_0743d9_idx",
                    )
                ],
            },
        ),
    ]
