# Generated by Django 4.2.13 on 2026-07-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0004_twofactorbackupcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="backup_code_failed_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="backup_code_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
