# Generated by Django 5.1.15 on 2026-09-01 08:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 chars of the key for identification",
                        max_length=10,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the API key",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed scopes/permissions",
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(default=1000, help_text="Requests per hour"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("device_name", models.CharField(max_length=200)),
                (
                    "device_type",
                    models.CharField(blank=True, help_text="e.g. Chrome on Windows", max_length=50),
                ),
                (
                    "device_id",
                    models.CharField(blank=True, help_text="Unique device identifier", max_length=255),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Browser/device fingerprint",
                        max_length=255,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trusted", "Trusted"),
                            ("pending", "Pending"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trusted_at", models.DateTimeField(blank=True, null=True)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="PasswordPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("min_length", models.PositiveSmallIntegerField(default=8)),
                ("max_length", models.PositiveSmallIntegerField(default=128)),
                ("require_uppercase", models.BooleanField(default=True)),
                ("require_lowercase", models.BooleanField(default=True)),
                ("require_digit", models.BooleanField(default=True)),
                ("require_special_char", models.BooleanField(default=True)),
                (
                    "special_chars",
                    models.CharField(default="!@#$%^&*()_+-=[]{}|;':\",./<>?", max_length=50),
                ),
                (
                    "prevent_REUSE",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Number of previous passwords to prevent reuse",
                    ),
                ),
                (
                    "max_age_days",
                    models.PositiveSmallIntegerField(default=90, help_text="Password expiry in days (0 = never)"),
                ),
                ("lockout_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "lockout_duration_minutes",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_policy",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_password_policy",
            },
        ),
        migrations.CreateModel(
            name="SessionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(default=480, help_text="8 hours default"),
                ),
                ("absolute_timeout_hours", models.PositiveIntegerField(default=24)),
                ("idle_timeout_minutes", models.PositiveIntegerField(default=30)),
                ("max_concurrent_sessions", models.PositiveIntegerField(default=5)),
                ("enforce_single_session", models.BooleanField(default=False)),
                ("require_reauthentication", models.BooleanField(default=False)),
                (
                    "reauthentication_interval_minutes",
                    models.PositiveIntegerField(default=60),
                ),
                ("remember_me_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_policy",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_session_policy",
            },
        ),
        migrations.CreateModel(
            name="IPWhitelist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "ip_range",
                    models.CharField(
                        blank=True,
                        help_text="CIDR notation e.g. 192.168.1.0/24",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("admin", "Admin Only"),
                            ("staff", "Staff Only"),
                            ("all", "All Users"),
                            ("api", "API Access"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_whitelist",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_ip_whitelist",
                "ordering": ["-created_at"],
                "unique_together": {("school", "ip_address")},
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("two_factor", "Two-Factor"),
                            ("oauth", "OAuth"),
                            ("sso", "SSO"),
                            ("magic_link", "Magic Link"),
                            ("passkey", "Passkey"),
                        ],
                        default="password",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("pending_2fa", "Pending 2FA"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("failure_reason", models.CharField(blank=True, max_length=200)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_login_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="auth_login__user_id_a4a878_idx",
                    ),
                    models.Index(
                        fields=["email", "created_at"],
                        name="auth_login__email_8b63d3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("microsoft", "Microsoft"),
                            ("github", "GitHub"),
                            ("apple", "Apple"),
                            ("facebook", "Facebook"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("client_id", models.CharField(max_length=255)),
                ("client_secret", models.CharField(max_length=255)),
                ("redirect_uri", models.URLField(max_length=500)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_providers",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_oauth_providers",
                "unique_together": {("school", "provider_type")},
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("password_change", "Password Change"),
                            ("profile_update", "Profile Update"),
                            ("settings_change", "Settings Change"),
                            ("data_export", "Data Export"),
                            ("data_import", "Data Import"),
                            ("file_upload", "File Upload"),
                            ("file_download", "File Download"),
                            ("report_view", "Report View"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="auth_user_a_user_id_ed7479_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "created_at"],
                        name="auth_user_a_activit_5b9c86_idx",
                    ),
                ],
            },
        ),
    ]
