# Generated by Django 5.1.15 on 2026-09-01 10:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPGeolocationCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("isp", models.CharField(blank=True, max_length=200)),
                ("is_vpn", models.BooleanField(default=False)),
                ("is_proxy", models.BooleanField(default=False)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_ip_geolocation_cache",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("module", "Module Access"),
                            ("action", "Action Permission"),
                            ("data", "Data Permission"),
                            ("report", "Report Permission"),
                        ],
                        default="module",
                        max_length=10,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text="e.g., students, fees, attendance",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "auth_permissions",
                "ordering": ["module", "name"],
            },
        ),
        migrations.CreateModel(
            name="AuditReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("login", "Login Summary"),
                            ("security", "Security Events"),
                            ("api", "API Usage"),
                            ("activity", "User Activity"),
                            ("compliance", "Compliance"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=15,
                    ),
                ),
                ("day_of_week", models.CharField(blank=True, max_length=10)),
                ("day_of_month", models.PositiveIntegerField(blank=True, null=True)),
                ("time_of_day", models.TimeField()),
                ("email_delivery", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("next_generation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="audit_report_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_report_schedules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_audit_report_schedules",
            },
        ),
        migrations.CreateModel(
            name="AuthWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                ("secret", models.CharField(blank=True, max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("password", "Password Change"),
                            ("mfa_setup", "MFA Setup"),
                            ("user_create", "User Created"),
                            ("user_deactivate", "User Deactivated"),
                            ("role", "Role Changed"),
                            ("suspicious", "Suspicious Activity"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("retry_interval_seconds", models.PositiveIntegerField(default=60)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                ("successful_deliveries", models.PositiveIntegerField(default=0)),
                ("failed_deliveries", models.PositiveIntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_webhooks",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_webhooks",
            },
        ),
        migrations.CreateModel(
            name="ComplianceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("gdpr", "GDPR Compliance"),
                            ("ferpa", "FERPA Compliance"),
                            ("hipaa", "HIPAA Compliance"),
                            ("soc2", "SOC 2 Compliance"),
                            ("iso27001", "ISO 27001"),
                            ("custom", "Custom Policy"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("in_progress", "In Progress"),
                            ("exempt", "Exempt"),
                        ],
                        default="in_progress",
                        max_length=15,
                    ),
                ),
                (
                    "requirement",
                    models.TextField(help_text="What needs to be compliant"),
                ),
                ("current_state", models.TextField(blank=True)),
                ("gap_analysis", models.TextField(blank=True)),
                ("remediation_plan", models.TextField(blank=True)),
                ("assessment_date", models.DateField()),
                ("next_assessment_date", models.DateField(blank=True, null=True)),
                ("last_compliant_date", models.DateField(blank=True, null=True)),
                (
                    "evidence_file",
                    models.FileField(blank=True, null=True, upload_to="auth/compliance/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_compliance_records",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_compliance_records",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Under Review"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("data_scope", models.TextField(help_text="What data to delete")),
                ("review_notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("denial_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_deletion_requests",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_data_deletion_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("all", "All Data"),
                            ("profile", "Profile Data"),
                            ("activity", "Activity Logs"),
                            ("academic", "Academic Records"),
                            ("financial", "Financial Data"),
                        ],
                        default="all",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "export_file",
                    models.FileField(blank=True, null=True, upload_to="auth/data_exports/"),
                ),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="Download link expiry", null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export_requests",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_data_export_requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domain", models.CharField(max_length=200, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("verification_token", models.CharField(blank=True, max_length=255)),
                (
                    "verification_method",
                    models.CharField(blank=True, help_text="DNS, HTML, Email", max_length=20),
                ),
                ("txt_record_name", models.CharField(blank=True, max_length=200)),
                ("txt_record_value", models.CharField(blank=True, max_length=255)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_verifications",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_domain_verifications",
            },
        ),
        migrations.CreateModel(
            name="MFAMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("totp", "Authenticator App (TOTP)"),
                            ("sms", "SMS Code"),
                            ("email", "Email Code"),
                            ("hardware", "Hardware Key (FIDO2)"),
                            ("backup", "Backup Codes"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Setup"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("totp_secret", models.CharField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("hardware_key_id", models.CharField(blank=True, max_length=255)),
                ("public_key", models.TextField(blank=True)),
                ("backup_codes", models.JSONField(blank=True, default=list)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_mfa_methods",
                "unique_together": {("user", "method_type")},
            },
        ),
        migrations.CreateModel(
            name="MFAVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mfa_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="auth_service.mfamethod",
                    ),
                ),
            ],
            options={
                "db_table": "auth_mfa_verifications",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("change_reason", models.CharField(blank=True, max_length=100)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="password_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_password_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.PositiveIntegerField(default=0, help_text="Higher = more authority"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system_role",
                    models.BooleanField(default=False, help_text="Cannot be deleted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_roles",
                        to="auth_service.role",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_roles",
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("password", "Password Policy"),
                            ("session", "Session Policy"),
                            ("login", "Login Policy"),
                            ("mfa", "Multi-Factor Authentication"),
                            ("api", "API Access Policy"),
                            ("ip", "IP Policy"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "settings",
                    models.JSONField(default=dict, help_text="Policy settings as JSON"),
                ),
                ("min_length", models.PositiveIntegerField(blank=True, null=True)),
                ("require_uppercase", models.BooleanField(default=False)),
                ("require_lowercase", models.BooleanField(default=False)),
                ("require_numbers", models.BooleanField(default=False)),
                ("require_special", models.BooleanField(default=False)),
                ("max_age_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "history_count",
                    models.PositiveIntegerField(default=5, help_text="Remember last N passwords"),
                ),
                ("session_timeout_minutes", models.PositiveIntegerField(default=30)),
                ("max_concurrent_sessions", models.PositiveIntegerField(default=5)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("lockout_duration_minutes", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_policies",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_security_policies",
            },
        ),
        migrations.CreateModel(
            name="SSOConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("saml", "SAML 2.0"),
                            ("oidc", "OpenID Connect"),
                            ("cas", "CAS"),
                            ("azure", "Azure AD"),
                            ("google", "Google Workspace"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("configuring", "Configuring"),
                            ("disabled", "Disabled"),
                        ],
                        default="configuring",
                        max_length=15,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, max_length=500)),
                ("sso_url", models.URLField(blank=True, max_length=500)),
                ("slo_url", models.URLField(blank=True, max_length=500)),
                ("x509_cert", models.TextField(blank=True)),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("discovery_url", models.URLField(blank=True, max_length=500)),
                ("attribute_mapping", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                ("auto_provision_users", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sso_configurations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_sso_configurations",
            },
        ),
        migrations.CreateModel(
            name="UserTrustScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trust_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="0-100 (100 = fully trusted)",
                        max_digits=5,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        help_text="Low, Medium, High, Critical",
                        max_length=20,
                    ),
                ),
                ("account_age_days", models.PositiveIntegerField(default=0)),
                ("successful_logins", models.PositiveIntegerField(default=0)),
                ("failed_logins", models.PositiveIntegerField(default=0)),
                ("suspicious_activities", models.PositiveIntegerField(default=0)),
                ("devices_used", models.PositiveIntegerField(default=0)),
                ("locations_used", models.PositiveIntegerField(default=0)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("mfa_methods_count", models.PositiveIntegerField(default=0)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("last_password_change", models.DateTimeField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_score",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_trust_scores",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("headers", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "response_status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="auth_service.authwebhook",
                    ),
                ),
            ],
            options={
                "db_table": "auth_webhook_deliveries",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("endpoint", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.PositiveIntegerField()),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("request_size_bytes", models.PositiveIntegerField(default=0)),
                ("response_size_bytes", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="auth_service.apikey",
                    ),
                ),
            ],
            options={
                "db_table": "auth_api_usage_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["api_key", "timestamp"],
                        name="auth_api_us_api_key_1d492e_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "timestamp"],
                        name="auth_api_us_endpoin_ae13c9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms of Service"),
                            ("privacy", "Privacy Policy"),
                            ("cookie", "Cookie Consent"),
                            ("data", "Data Processing"),
                            ("marketing", "Marketing Communications"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("withdrawn", "Withdrawn"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("policy_version", models.CharField(blank=True, max_length=50)),
                ("policy_url", models.URLField(blank=True)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_consent_records",
                "unique_together": {("user", "consent_type", "policy_version")},
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("locked", "Account Locked"),
                            ("blocked", "IP Blocked"),
                        ],
                        max_length=10,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_attempts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_login_attempts",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["username", "attempted_at"],
                        name="auth_login__usernam_7e0f3d_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "attempted_at"],
                        name="auth_login__ip_addr_0fb781_idx",
                    ),
                    models.Index(
                        fields=["school", "status"],
                        name="auth_login__school__f041cc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_type", models.CharField(default="Bearer", max_length=50)),
                ("provider_user_id", models.CharField(max_length=255)),
                ("provider_username", models.CharField(blank=True, max_length=200)),
                ("provider_email", models.EmailField(blank=True, max_length=254)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="auth_service.oauthprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_oauth_tokens",
                "unique_together": {("user", "provider")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("granted", models.BooleanField(default=True)),
                (
                    "conditions",
                    models.JSONField(blank=True, default=dict, help_text="Conditional permissions"),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="auth_service.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="auth_service.role",
                    ),
                ),
            ],
            options={
                "db_table": "auth_role_permissions",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="SchoolFeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("enrollment", "Enrollment"),
                            ("billing", "Billing"),
                            ("reporting", "Reporting"),
                            ("integration", "Integration"),
                            ("ui", "User Interface"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "rollout_percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "auth_feature_flags",
                "unique_together": {("school", "feature_name")},
            },
        ),
        migrations.CreateModel(
            name="SecurityNotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("login", "New Login"),
                            ("password", "Password Changed"),
                            ("mfa", "MFA Changed"),
                            ("api_key", "API Key Used"),
                            ("suspicious", "Suspicious Activity"),
                            ("device", "New Device"),
                        ],
                        max_length=15,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_security_notification_prefs",
                "unique_together": {("user", "notification_type")},
            },
        ),
        migrations.CreateModel(
            name="SessionToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("access", "Access Token"),
                            ("refresh", "Refresh Token"),
                            ("reset", "Password Reset"),
                            ("verify", "Email Verification"),
                            ("api", "API Token"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("token_hash", models.CharField(max_length=255, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_session_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "token_type", "status"],
                        name="auth_sessio_user_id_5843b9_idx",
                    ),
                    models.Index(fields=["expires_at"], name="auth_sessio_expires_60a1c4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.JSONField(blank=True, default=dict, help_text="Role scope constraints"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="auth_service.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_roles",
                "unique_together": {("user", "role")},
            },
        ),
        migrations.CreateModel(
            name="UserSessionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                (
                    "device_type",
                    models.CharField(blank=True, help_text="Desktop, Mobile, Tablet", max_length=50),
                ),
                ("device_name", models.CharField(blank=True, max_length=200)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("login_at", models.DateTimeField()),
                ("last_active_at", models.DateTimeField()),
                ("logout_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auth_session_history",
                "ordering": ["-login_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_current"],
                        name="auth_sessio_user_id_4ebb0f_idx",
                    )
                ],
            },
        ),
    ]
