# Generated by Django 4.2.13 on 2026-07-22 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountantProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        help_text="Professional qualification (e.g., ACCA, CPA, MBA Finance)",
                        max_length=100,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Area of expertise (e.g., Taxation, Audit, Financial Planning)",
                        max_length=100,
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Years of professional experience"
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True, help_text="Professional certifications and licenses"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Professional biography"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountant_profiles",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accountant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accountant Profile",
                "verbose_name_plural": "Accountant Profiles",
                "db_table": "accountant_profiles",
            },
        ),
    ]
