# Generated by Django 5.1.15 on 2026-08-31 07:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("hr", "0002_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("resume_url", models.URLField(blank=True, max_length=500)),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("screening", "Screening"),
                            ("interview", "Interview"),
                            ("offer", "Offer Extended"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="new",
                        max_length=15,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Website, Referral, LinkedIn",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_applicants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BenefitPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("health", "Health Insurance"),
                            ("dental", "Dental Insurance"),
                            ("vision", "Vision Insurance"),
                            ("life", "Life Insurance"),
                            ("retirement", "Retirement Plan"),
                            ("disability", "Disability Insurance"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=255)),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("enrollment_start", models.DateField(blank=True, null=True)),
                ("enrollment_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_plans",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_benefit_plans",
                "ordering": ["benefit_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuing_organization", models.CharField(blank=True, max_length=255)),
                ("credential_id", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending_renewal", "Pending Renewal"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("document_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "hr_certifications",
                "ordering": ["-expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBenefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("enrollment_date", models.DateField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("dependents_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="hr.employee",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="hr.benefitplan",
                    ),
                ),
            ],
            options={
                "db_table": "hr_employee_benefits",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Screen"),
                            ("video", "Video Call"),
                            ("in_person", "In-Person"),
                            ("panel", "Panel Interview"),
                            ("technical", "Technical Assessment"),
                        ],
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-5 rating", null=True),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hire", "Hire"),
                            ("maybe", "Maybe"),
                            ("no_hire", "Don't Hire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="hr.applicant",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_interview_schedules",
                "ordering": ["scheduled_date", "scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                (
                    "salary_range_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "salary_range_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("positions_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("filled", "Filled"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("closing_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_job_postings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="applicant",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicants",
                to="hr.jobposting",
            ),
        ),
        migrations.CreateModel(
            name="OnboardingChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.department",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_checklists",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_onboarding_checklists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "due_days_after_joining",
                    models.PositiveSmallIntegerField(default=0, help_text="Days after employee joining date"),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="hr.onboardingchecklist",
                    ),
                ),
            ],
            options={
                "db_table": "hr_onboarding_tasks",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to="hr.employee",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="hr.onboardingtask",
                    ),
                ),
            ],
            options={
                "db_table": "hr_onboarding_progress",
            },
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_overtime",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_overtime_requests",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("self_review", "Awaiting Self-Review"),
                            ("manager_review", "Awaiting Manager Review"),
                            ("hr_review", "Awaiting HR Review"),
                            ("completed", "Completed"),
                            ("appealed", "Appealed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "overall_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("5", "Exceptional (5)"),
                            ("4", "Exceeds Expectations (4)"),
                            ("3", "Meets Expectations (3)"),
                            ("2", "Needs Improvement (2)"),
                            ("1", "Unsatisfactory (1)"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("areas_for_improvement", models.TextField(blank=True)),
                (
                    "goals_summary",
                    models.TextField(blank=True, help_text="Summary of goal achievement"),
                ),
                (
                    "development_plan",
                    models.TextField(blank=True, help_text="Future development actions"),
                ),
                (
                    "self_comments",
                    models.TextField(blank=True, help_text="Employee self-assessment"),
                ),
                ("manager_comments", models.TextField(blank=True)),
                ("hr_comments", models.TextField(blank=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("promotion_recommended", models.BooleanField(default=False)),
                (
                    "salary_revision_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Recommended salary revision percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="hr.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_performance_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PeerFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("peer", "Peer Feedback"),
                            ("subordinate", "Subordinate Feedback"),
                            ("self", "Self Feedback"),
                            ("customer", "External Feedback"),
                        ],
                        default="peer",
                        max_length=15,
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("improvements", models.TextField(blank=True)),
                (
                    "collaboration_score",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-5 scale", null=True),
                ),
                (
                    "communication_score",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-5 scale", null=True),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-5 scale", null=True),
                ),
                ("comments", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_feedbacks",
                        to="hr.performancereview",
                    ),
                ),
            ],
            options={
                "db_table": "hr_peer_feedbacks",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReviewCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_review_cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_cycles",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_review_cycles",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="performancereview",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="hr.performancereviewcycle",
            ),
        ),
        migrations.CreateModel(
            name="PerformanceGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Teaching, Administration, Research",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit",
                    models.CharField(blank=True, help_text="e.g. %, count, score", max_length=20),
                ),
                ("progress_pct", models.PositiveSmallIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="hr.employee",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="hr.performancereviewcycle",
                    ),
                ),
            ],
            options={
                "db_table": "hr_performance_goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("clock_in", models.DateTimeField()),
                ("clock_out", models.DateTimeField(blank=True, null=True)),
                ("break_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_time_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "hr_time_entries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField(help_text="Monday of the week")),
                ("week_end", models.DateField()),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_overtime",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_timesheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "hr_timesheets",
                "ordering": ["-week_start"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("course", "Online Course"),
                            ("certification", "Certification"),
                            ("conference", "Conference"),
                            ("on_job", "On-the-Job Training"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=255)),
                ("instructor", models.CharField(blank=True, max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "max_participants",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "cost_per_participant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_programs",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_training_programs",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="enrolled",
                        max_length=15,
                    ),
                ),
                ("enrolled_date", models.DateField(auto_now_add=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("certificate_url", models.URLField(blank=True, max_length=500)),
                (
                    "hours_attended",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-5 rating", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_enrollments",
                        to="hr.employee",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="hr.trainingprogram",
                    ),
                ),
            ],
            options={
                "db_table": "hr_training_enrollments",
                "ordering": ["-enrolled_date"],
            },
        ),
        migrations.AddIndex(
            model_name="benefitplan",
            index=models.Index(fields=["school", "benefit_type"], name="hr_benefit__school__ff29f2_idx"),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(fields=["employee", "status"], name="hr_certific_employe_b1189b_idx"),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(fields=["expiry_date"], name="hr_certific_expiry__263f3d_idx"),
        ),
        migrations.AddIndex(
            model_name="employeebenefit",
            index=models.Index(fields=["employee", "status"], name="hr_employee_employe_e853be_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="employeebenefit",
            unique_together={("employee", "plan")},
        ),
        migrations.AddIndex(
            model_name="interviewschedule",
            index=models.Index(fields=["applicant", "status"], name="hr_intervie_applica_4a4e9f_idx"),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(fields=["school", "status"], name="hr_job_post_school__832984_idx"),
        ),
        migrations.AddIndex(
            model_name="applicant",
            index=models.Index(fields=["job_posting", "status"], name="hr_applican_job_pos_ccc8b4_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingtask",
            index=models.Index(fields=["checklist", "order"], name="hr_onboardi_checkli_88ceef_idx"),
        ),
        migrations.AddIndex(
            model_name="onboardingprogress",
            index=models.Index(fields=["employee", "status"], name="hr_onboardi_employe_67c6bf_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="onboardingprogress",
            unique_together={("employee", "task")},
        ),
        migrations.AddIndex(
            model_name="overtimerequest",
            index=models.Index(fields=["employee", "status"], name="hr_overtime_employe_ec341f_idx"),
        ),
        migrations.AddIndex(
            model_name="peerfeedback",
            index=models.Index(
                fields=["review", "feedback_type"],
                name="hr_peer_fee_review__642365_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performancereviewcycle",
            unique_together={("school", "name")},
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(fields=["employee", "cycle"], name="hr_performa_employe_16f14a_idx"),
        ),
        migrations.AddIndex(
            model_name="performancereview",
            index=models.Index(fields=["status"], name="hr_performa_status_7e7fb2_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="performancereview",
            unique_together={("employee", "cycle")},
        ),
        migrations.AddIndex(
            model_name="performancegoal",
            index=models.Index(fields=["employee", "cycle"], name="hr_performa_employe_df95d6_idx"),
        ),
        migrations.AddIndex(
            model_name="performancegoal",
            index=models.Index(fields=["status"], name="hr_performa_status_4f9e45_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["employee", "date"], name="hr_time_ent_employe_5b43c8_idx"),
        ),
        migrations.AddIndex(
            model_name="timeentry",
            index=models.Index(fields=["status"], name="hr_time_ent_status_3b4288_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="timeentry",
            unique_together={("employee", "date")},
        ),
        migrations.AddIndex(
            model_name="timesheet",
            index=models.Index(fields=["employee", "week_start"], name="hr_timeshee_employe_4519df_idx"),
        ),
        migrations.AddIndex(
            model_name="timesheet",
            index=models.Index(fields=["status"], name="hr_timeshee_status_7f88f6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="timesheet",
            unique_together={("employee", "week_start")},
        ),
        migrations.AddIndex(
            model_name="trainingprogram",
            index=models.Index(fields=["school", "status"], name="hr_training_school__ad97ad_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingenrollment",
            index=models.Index(fields=["employee", "status"], name="hr_training_employe_7b3119_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="trainingenrollment",
            unique_together={("program", "employee")},
        ),
    ]
