# Generated by Django 5.1.15 on 2026-08-31 08:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("hr", "0003_performance_recruitment_time_benefits_training"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=50, unique=True)),
                (
                    "retention_days",
                    models.PositiveIntegerField(help_text="Days to retain data"),
                ),
                ("auto_delete", models.BooleanField(default=False)),
                ("last_purge_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_retention_policies",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_data_retention_policies",
                "ordering": ["model_name"],
            },
        ),
        migrations.CreateModel(
            name="PayslipViewLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslip_views",
                        to="hr.employee",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="hr.payslip",
                    ),
                ),
            ],
            options={
                "db_table": "hr_payslip_view_logs",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField(help_text="Policy content or URL")),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Leave Policy, Code of Conduct, Safety",
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("requires_acknowledgment", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_documents",
                        to="auth_service.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_policy_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicyAcknowledgment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_acknowledgments",
                        to="hr.employee",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgments",
                        to="hr.policydocument",
                    ),
                ),
            ],
            options={
                "db_table": "hr_policy_acknowledgments",
                "ordering": ["-acknowledged_at"],
            },
        ),
        migrations.CreateModel(
            name="SalaryReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField(help_text="First day of the month")),
                (
                    "total_gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_pension",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "average_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("headcount", models.PositiveIntegerField(default=0)),
                ("department_breakdown", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_salary_reports",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="TurnoverReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField(help_text="First day of the month")),
                ("total_employees_start", models.PositiveIntegerField(default=0)),
                ("new_hires", models.PositiveIntegerField(default=0)),
                ("separations", models.PositiveIntegerField(default=0)),
                (
                    "turnover_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("resignations", models.PositiveIntegerField(default=0)),
                ("terminations", models.PositiveIntegerField(default=0)),
                ("retirements", models.PositiveIntegerField(default=0)),
                ("department_breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "top_reasons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"reason": "...", "count": 3}]',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnover_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_turnover_reports",
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("contract", "Employment Contract"),
                            ("id_proof", "ID Proof"),
                            ("address_proof", "Address Proof"),
                            ("education", "Education Certificate"),
                            ("experience", "Experience Certificate"),
                            ("offer_letter", "Offer Letter"),
                            ("appraisal", "Appraisal Letter"),
                            ("salary_slip", "Salary Slip"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file_url", models.URLField(max_length=500)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_hr_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_hr_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_employee_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "document_type"],
                        name="hr_employee_employe_f591c8_idx",
                    ),
                    models.Index(fields=["expiry_date"], name="hr_employee_expiry__239e17_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfileUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_updates",
                        to="hr.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_profile_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hr_profile_updates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="hr_profile__employe_5af384_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HRAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("export", "Exported"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="e.g. Employee, Payslip, LeaveRequest", max_length=50),
                ),
                ("object_id", models.CharField(blank=True, max_length=50)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_audit_logs",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "model_name"],
                        name="hr_audit_lo_school__f4d0a3_idx",
                    ),
                    models.Index(fields=["performed_by"], name="hr_audit_lo_perform_c5e716_idx"),
                    models.Index(fields=["-created_at"], name="hr_audit_lo_created_1165a3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HRDashboardMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_employees", models.PositiveIntegerField(default=0)),
                ("active_employees", models.PositiveIntegerField(default=0)),
                ("new_hires_this_month", models.PositiveIntegerField(default=0)),
                ("separations_this_month", models.PositiveIntegerField(default=0)),
                (
                    "turnover_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_tenure_months",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_payroll_this_month",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("pending_leave_requests", models.PositiveIntegerField(default=0)),
                ("pending_overtime_requests", models.PositiveIntegerField(default=0)),
                ("expiring_certifications", models.PositiveIntegerField(default=0)),
                ("active_trainings", models.PositiveIntegerField(default=0)),
                (
                    "department_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"Mathematics": 5, "Science": 3}',
                    ),
                ),
                (
                    "employment_type_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"full_time": 20, "part_time": 5}',
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_metrics",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hr_dashboard_metrics",
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "-calculated_at"],
                        name="hr_dashboar_school__ebab06_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalanceHR",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("personal", "Personal Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("unpaid", "Unpaid Leave"),
                        ],
                        max_length=15,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("total_days", models.PositiveSmallIntegerField(default=0)),
                ("used_days", models.PositiveSmallIntegerField(default=0)),
                ("carried_over", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_leave_balances",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "db_table": "hr_leave_balances",
                "ordering": ["-year", "leave_type"],
                "unique_together": {("employee", "leave_type", "year")},
            },
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(fields=["school", "status"], name="hr_policy_d_school__f624b3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="policyacknowledgment",
            unique_together={("policy", "employee")},
        ),
        migrations.AlterUniqueTogether(
            name="salaryreport",
            unique_together={("school", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="turnoverreport",
            unique_together={("school", "month")},
        ),
    ]
