# Generated by Django 5.2.17 on 2026-09-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_self_service_analytics_documents_compliance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyacknowledgment",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Null when the acknowledging user has no Employee record (e.g. admins).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policy_acknowledgments",
                to="hr.employee",
            ),
        ),
    ]
