# Generated by Django 4.2.13 on 2026-07-15 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_initial"),
        ("hr", "0001_initial"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to HR employee record if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_records",
                        to="hr.employee",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transport_drivers",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "origin",
                    models.CharField(
                        help_text="Starting point / depot", max_length=255
                    ),
                ),
                (
                    "destination",
                    models.CharField(help_text="School location", max_length=255),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveSmallIntegerField(default=30),
                ),
                (
                    "operating_days",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated days: monday,tuesday,wednesday,thursday,friday",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_routes",
                        to="transportation.driver",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_routes",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transport_routes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Main Gate, City Center", max_length=200
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "stop_order",
                    models.PositiveSmallIntegerField(
                        help_text="Order along the route (1 = first)"
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "pickup_time",
                    models.TimeField(
                        blank=True,
                        help_text="Estimated pickup time at this stop",
                        null=True,
                    ),
                ),
                (
                    "dropoff_time",
                    models.TimeField(
                        blank=True,
                        help_text="Estimated dropoff time at this stop",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="transportation.route",
                    ),
                ),
            ],
            options={
                "db_table": "transport_route_stops",
                "ordering": ["route", "stop_order"],
                "unique_together": {("route", "stop_order")},
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plate_number", models.CharField(max_length=30, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("mini_bus", "Mini Bus"),
                            ("van", "Van"),
                            ("suv", "SUV"),
                            ("sedan", "Sedan"),
                            ("other", "Other"),
                        ],
                        default="bus",
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        help_text="Maximum number of students"
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("chassis_number", models.CharField(blank=True, max_length=50)),
                ("engine_number", models.CharField(blank=True, max_length=50)),
                ("insurance_number", models.CharField(blank=True, max_length=50)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("fitness_expiry", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("in_maintenance", "In Maintenance"),
                            ("retired", "Retired"),
                            ("out_of_service", "Out of Service"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transport_vehicles",
                "ordering": ["plate_number"],
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Service"),
                            ("repair", "Repair"),
                            ("inspection", "Inspection"),
                            ("tire", "Tire Change"),
                            ("engine", "Engine Service"),
                            ("body", "Body Work"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(
                        blank=True, help_text="Odometer at service (km)", null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=150)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("next_service_date", models.DateField(blank=True, null=True)),
                (
                    "next_service_odometer",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_maintenance",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.AddField(
            model_name="route",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_routes",
                to="transportation.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="StudentRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup Only"),
                            ("dropoff", "Dropoff Only"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dropoff_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropoff_students",
                        to="transportation.routestop",
                    ),
                ),
                (
                    "pickup_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_students",
                        to="transportation.routestop",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_assignments",
                        to="transportation.route",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_assignments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "transport_student_assignments",
                "ordering": ["route", "student"],
                "unique_together": {("route", "student", "effective_from")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("school", "name")},
        ),
    ]
