# Generated by Django 5.1.15 on 2026-09-01 07:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        ("transportation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("petrol", "Petrol"),
                            ("cng", "CNG"),
                            ("electric", "Electric"),
                            ("other", "Other"),
                        ],
                        default="diesel",
                        max_length=20,
                    ),
                ),
                ("fill_date", models.DateField()),
                ("odometer_reading", models.PositiveIntegerField()),
                ("liters", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cost_per_liter", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("station_name", models.CharField(blank=True, max_length=200)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_fuel_logs",
                "ordering": ["-fill_date"],
            },
        ),
        migrations.CreateModel(
            name="TransportFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("term", "Term"),
                            ("annual", "Annual"),
                            ("one_time", "One-Time"),
                            ("other", "Other"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.academicyear",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_fees",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_fees",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "transport_fees",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="TransportIncidentReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("accident", "Accident"),
                            ("breakdown", "Breakdown"),
                            ("medical", "Medical Emergency"),
                            ("behavioral", "Behavioral"),
                            ("route_delay", "Route Delay"),
                            ("vehicle_damage", "Vehicle Damage"),
                            ("weather", "Weather Related"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("incident_date", models.DateField()),
                ("incident_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("students_involved", models.JSONField(blank=True, default=list)),
                ("injuries_reported", models.BooleanField(default=False)),
                ("injury_details", models.TextField(blank=True)),
                ("witnesses", models.TextField(blank=True)),
                ("police_report", models.BooleanField(default=False)),
                ("police_report_number", models.CharField(blank=True, max_length=50)),
                ("insurance_claim", models.BooleanField(default=False)),
                ("insurance_claim_number", models.CharField(blank=True, max_length=50)),
                ("corrective_actions", models.TextField(blank=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.driver",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_incidents_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_incidents",
                        to="auth_service.school",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_incidents",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.CreateModel(
            name="TransportNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("delay", "Delay Alert"),
                            ("cancellation", "Cancellation"),
                            ("route_change", "Route Change"),
                            ("pickup_complete", "Pickup Complete"),
                            ("dropoff_complete", "Dropoff Complete"),
                            ("incident", "Incident"),
                            ("fee_reminder", "Fee Reminder"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of recipient IDs or emails",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_notifications",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("route_summary", "Route Summary"),
                            ("vehicle_status", "Vehicle Status"),
                            ("fuel_consumption", "Fuel Consumption"),
                            ("incident_summary", "Incident Summary"),
                            ("fee_collection", "Fee Collection"),
                            ("attendance_summary", "Attendance Summary"),
                            ("maintenance_cost", "Maintenance Cost"),
                            ("general", "General Report"),
                        ],
                        default="general",
                        max_length=25,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("report_data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transport_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("field_trip", "Field Trip"),
                            ("sports_event", "Sports Event"),
                            ("cultural_event", "Cultural Event"),
                            ("examination", "Examination"),
                            ("other", "Other"),
                        ],
                        default="field_trip",
                        max_length=20,
                    ),
                ),
                ("destination", models.CharField(max_length=255)),
                ("trip_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("return_time", models.TimeField(blank=True, null=True)),
                ("expected_students", models.PositiveIntegerField(default=0)),
                ("actual_students", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_schedules",
                        to="auth_service.school",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_trip_schedules",
                "ordering": ["-trip_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("insurance", "Insurance"),
                            ("permit", "Permit"),
                            ("fitness", "Fitness Certificate"),
                            ("pollution", "Pollution Certificate"),
                            ("tax", "Tax Receipt"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_name", models.CharField(max_length=200)),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("issued_by", models.CharField(blank=True, max_length=200)),
                ("document_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_vehicle_documents",
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("pre_trip", "Pre-Trip"),
                            ("post_trip", "Post-Trip"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                        ],
                        default="pre_trip",
                        max_length=20,
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("inspector_name", models.CharField(max_length=150)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("needs_repair", "Needs Repair"),
                        ],
                        default="pass",
                        max_length=20,
                    ),
                ),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("exterior_check", models.BooleanField(default=True)),
                ("interior_check", models.BooleanField(default=True)),
                ("tires_check", models.BooleanField(default=True)),
                ("lights_check", models.BooleanField(default=True)),
                ("brakes_check", models.BooleanField(default=True)),
                ("signals_check", models.BooleanField(default=True)),
                ("emergency_equipment", models.BooleanField(default=True)),
                ("first_aid_kit", models.BooleanField(default=True)),
                ("fire_extinguisher", models.BooleanField(default=True)),
                ("defects_found", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_inspections",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleInsurance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("comprehensive", "Comprehensive"),
                            ("third_party", "Third Party"),
                            ("liability", "Liability"),
                            ("other", "Other"),
                        ],
                        default="comprehensive",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=200)),
                ("policy_number", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "premium_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending_renewal", "Pending Renewal"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("document_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_records",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_vehicle_insurance",
                "ordering": ["-end_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyTransportAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("dropoff_time", models.TimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dropoff_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dropoff_attendance",
                        to="transportation.routestop",
                    ),
                ),
                (
                    "pickup_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_attendance",
                        to="transportation.routestop",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_attendance",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_attendance",
                        to="students.student",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_daily_attendance",
                "ordering": ["-date", "student"],
                "unique_together": {("student", "route", "date", "attendance_type")},
            },
        ),
    ]
