# Generated by Django 5.1.15 on 2026-09-01 10:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        (
            "transportation",
            "0002_fuellog_transportfee_transportincidentreport_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("on_route", "On Route"),
                            ("at_stop", "At Stop"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                ("scheduled_start", models.TimeField()),
                ("scheduled_end", models.TimeField()),
                ("actual_start", models.TimeField(blank=True, null=True)),
                ("actual_end", models.TimeField(blank=True, null=True)),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                ("total_students_expected", models.PositiveIntegerField(default=0)),
                ("total_students_onboard", models.PositiveIntegerField(default=0)),
                ("total_students_picked_up", models.PositiveIntegerField(default=0)),
                ("total_students_dropped", models.PositiveIntegerField(default=0)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.routestop",
                    ),
                ),
                (
                    "next_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_stop_tracking",
                        to="transportation.routestop",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_sessions",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "bus_tracking",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "license_type",
                    models.CharField(blank=True, help_text="Commercial, Regular, etc.", max_length=50),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("issuing_authority", models.CharField(blank=True, max_length=200)),
                ("endorsements", models.JSONField(blank=True, default=list)),
                ("restrictions", models.JSONField(blank=True, default=list)),
                (
                    "license_image",
                    models.ImageField(blank=True, null=True, upload_to="transportation/licenses/"),
                ),
                ("is_valid", models.BooleanField(default=True)),
                ("suspension_reason", models.TextField(blank=True)),
                ("suspension_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_info",
                        to="transportation.driver",
                    ),
                ),
            ],
            options={
                "db_table": "driver_licenses",
            },
        ),
        migrations.CreateModel(
            name="DriverPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("evaluation_date", models.DateField()),
                ("safety_rating", models.PositiveSmallIntegerField(default=3)),
                ("punctuality_rating", models.PositiveSmallIntegerField(default=3)),
                ("vehicle_care_rating", models.PositiveSmallIntegerField(default=3)),
                (
                    "student_interaction_rating",
                    models.PositiveSmallIntegerField(default=3),
                ),
                (
                    "overall_rating",
                    models.DecimalField(decimal_places=2, default=3, max_digits=3),
                ),
                ("total_trips", models.PositiveIntegerField(default=0)),
                ("accidents", models.PositiveIntegerField(default=0)),
                ("complaints", models.PositiveIntegerField(default=0)),
                ("compliments", models.PositiveIntegerField(default=0)),
                (
                    "on_time_percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("strengths", models.TextField(blank=True)),
                ("areas_for_improvement", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="transportation.driver",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "driver_performance",
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="GeofenceZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("school", "School Zone"),
                            ("stop", "Bus Stop"),
                            ("restricted", "Restricted Area"),
                            ("danger", "Danger Zone"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "center_latitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                (
                    "center_longitude",
                    models.DecimalField(decimal_places=7, max_digits=10),
                ),
                ("radius_meters", models.PositiveIntegerField(default=500)),
                ("polygon_coordinates", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("alert_on_entry", models.BooleanField(default=False)),
                ("alert_on_exit", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_zones",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "geofence_zones",
            },
        ),
        migrations.CreateModel(
            name="RouteOptimization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("optimization_date", models.DateField()),
                (
                    "original_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("original_time_minutes", models.PositiveIntegerField(default=0)),
                (
                    "original_fuel_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "optimized_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("optimized_time_minutes", models.PositiveIntegerField(default=0)),
                (
                    "optimized_fuel_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "distance_saved_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("time_saved_minutes", models.PositiveIntegerField(default=0)),
                (
                    "fuel_saved",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "optimized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_optimizations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "route_optimizations",
                "ordering": ["-optimization_date"],
            },
        ),
        migrations.CreateModel(
            name="StopETA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_time", models.TimeField()),
                ("estimated_time", models.DateTimeField(blank=True, null=True)),
                ("actual_time", models.DateTimeField(blank=True, null=True)),
                ("students_expected", models.PositiveIntegerField(default=0)),
                ("students_picked_up", models.PositiveIntegerField(default=0)),
                ("students_dropped", models.PositiveIntegerField(default=0)),
                ("delay_minutes", models.IntegerField(default=0)),
                ("delay_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etas",
                        to="transportation.routestop",
                    ),
                ),
                (
                    "tracking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_etas",
                        to="transportation.bustracking",
                    ),
                ),
            ],
            options={
                "db_table": "stop_etas",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="StudentTransportProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("needs_morning", models.BooleanField(default=True)),
                ("needs_evening", models.BooleanField(default=True)),
                ("has_disability", models.BooleanField(default=False)),
                ("disability_notes", models.TextField(blank=True)),
                ("needs_wheelchair", models.BooleanField(default=False)),
                ("needs_escort", models.BooleanField(default=False)),
                (
                    "emergency_pickup_person",
                    models.CharField(blank=True, max_length=200),
                ),
                ("emergency_pickup_phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "assigned_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.routestop",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_transport_profiles",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_profile",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_transport_profiles",
            },
        ),
        migrations.CreateModel(
            name="TransportAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("delay", "Route Delay"),
                            ("cancel", "Route Cancellation"),
                            ("breakdown", "Vehicle Breakdown"),
                            ("accident", "Accident"),
                            ("weather", "Weather Advisory"),
                            ("route_change", "Route Change"),
                            ("maintenance", "Scheduled Maintenance"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("affected_students", models.PositiveIntegerField(default=0)),
                ("affected_routes", models.JSONField(blank=True, default=list)),
                (
                    "estimated_delay_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("parents_notified", models.BooleanField(default=False)),
                ("staff_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_alert_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_alerts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransportAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("vehicle_add", "Vehicle Added"),
                            ("vehicle_update", "Vehicle Updated"),
                            ("route_create", "Route Created"),
                            ("route_modify", "Route Modified"),
                            ("driver_assign", "Driver Assigned"),
                            ("maint_schedule", "Maintenance Scheduled"),
                            ("fee_collect", "Fee Collected"),
                            ("incident", "Incident Reported"),
                            ("alert", "Alert Sent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_model", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_audit_logs",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transport_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TransportComplianceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("reg", "Vehicle Registration"),
                            ("insurance", "Insurance"),
                            ("safety", "Safety Inspection"),
                            ("license", "Driver License"),
                            ("emergency", "Emergency Equipment"),
                            ("env", "Environmental"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("expiring", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("non_compliant", "Non-Compliant"),
                        ],
                        default="compliant",
                        max_length=15,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("issued_by", models.CharField(blank=True, max_length=200)),
                (
                    "document_file",
                    models.FileField(blank=True, null=True, upload_to="transportation/compliance/"),
                ),
                (
                    "alert_days_before",
                    models.PositiveIntegerField(default=30, help_text="Days before expiry to alert"),
                ),
                ("last_alert_sent", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.driver",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_compliance",
                        to="auth_service.school",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transport_compliance_records",
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="TransportEmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("alternate_phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("priority_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_emergency_contacts",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transport_emergency_contacts",
                "ordering": ["priority_order", "-is_primary"],
            },
        ),
        migrations.CreateModel(
            name="TransportFeeStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("per_trip", "Per Trip"),
                            ("one_time", "One Time"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "min_distance_km",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "max_distance_km",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "sibling_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "early_bird_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("academic_year", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_fee_structures",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transport_fee_structures",
            },
        ),
        migrations.CreateModel(
            name="TransportIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("accident", "Accident"),
                            ("breakdown", "Breakdown"),
                            ("delay", "Major Delay"),
                            ("medical", "Medical Emergency"),
                            ("behavioral", "Student Behavioral Issue"),
                            ("weather", "Weather Related"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=300)),
                ("incident_date", models.DateField()),
                ("incident_time", models.TimeField(blank=True, null=True)),
                ("witnesses", models.TextField(blank=True)),
                ("injuries_reported", models.BooleanField(default=False)),
                ("injury_details", models.TextField(blank=True)),
                ("first_aid_administered", models.BooleanField(default=False)),
                ("investigation_notes", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("insurance_claim_filed", models.BooleanField(default=False)),
                ("claim_number", models.CharField(blank=True, max_length=50)),
                (
                    "photos",
                    models.ImageField(blank=True, null=True, upload_to="transportation/incidents/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.driver",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_incidents_resolved_detail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_detailed_incidents",
                        to="auth_service.school",
                    ),
                ),
                (
                    "students_involved",
                    models.ManyToManyField(
                        blank=True,
                        related_name="transport_incidents",
                        to="students.student",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_incidents_detail",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleAssignmentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assignment_date", models.DateField()),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("route", "Route Assignment"),
                            ("trip", "Trip Assignment"),
                            ("pool", "Pool Assignment"),
                            ("maintenance", "Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_logs",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_assignment_logs",
                "ordering": ["-assignment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleConditionReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("pre_trip", "Pre-Trip"),
                            ("post_trip", "Post-Trip"),
                            ("spot_check", "Spot Check"),
                        ],
                        max_length=15,
                    ),
                ),
                ("report_date", models.DateField()),
                (
                    "tires_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("not_working", "Not Working"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                (
                    "brakes_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("not_working", "Not Working"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                (
                    "lights_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("not_working", "Not Working"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                (
                    "mirrors_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("not_working", "Not Working"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                (
                    "body_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("not_working", "Not Working"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                (
                    "interior_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("not_working", "Not Working"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                (
                    "fuel_level",
                    models.PositiveIntegerField(default=100, help_text="Percentage"),
                ),
                ("mileage", models.PositiveIntegerField(default=0)),
                ("issues_found", models.TextField(blank=True)),
                (
                    "photos",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="transportation/condition_reports/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_reports",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_condition_reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="VehicleGPSLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "speed_kmh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "heading",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("timestamp", models.DateTimeField()),
                ("ignition_on", models.BooleanField(default=True)),
                ("battery_level", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_logs",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_gps_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GeofenceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("entry", "Zone Entry"),
                            ("exit", "Zone Exit"),
                            ("speed", "Speed Violation"),
                            ("deviation", "Route Deviation"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "speed_recorded",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "speed_limit",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_alerts",
                        to="transportation.vehicle",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.geofencezone",
                    ),
                ),
                (
                    "gps_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehiclegpslog",
                    ),
                ),
            ],
            options={
                "db_table": "geofence_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehiclePool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pool_type",
                    models.CharField(
                        choices=[
                            ("field_trip", "Field Trip"),
                            ("staff", "Staff Use"),
                            ("emergency", "Emergency"),
                            ("replacement", "Maintenance Replacement"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("in_use", "In Use"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="available",
                        max_length=15,
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("destination", models.CharField(blank=True, max_length=300)),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("expected_passengers", models.PositiveIntegerField(default=0)),
                ("actual_passengers", models.PositiveIntegerField(default=0)),
                ("approved", models.BooleanField(default=False)),
                ("start_mileage", models.PositiveIntegerField(default=0)),
                ("end_mileage", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_pool_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_pools",
                        to="auth_service.school",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_bookings",
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_pool_bookings",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ParentTransportAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracking_enabled", models.BooleanField(default=True)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("email_alerts", models.BooleanField(default=True)),
                ("sms_alerts", models.BooleanField(default=False)),
                ("alert_pickup", models.BooleanField(default=True)),
                ("alert_dropoff", models.BooleanField(default=True)),
                ("alert_delay", models.BooleanField(default=True)),
                ("alert_incident", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_transport_access",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_transport_access",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "parent_transport_access",
                "unique_together": {("parent", "student")},
            },
        ),
        migrations.CreateModel(
            name="TransportationDailyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_vehicles_active", models.PositiveIntegerField(default=0)),
                ("total_trips_completed", models.PositiveIntegerField(default=0)),
                ("total_routes_served", models.PositiveIntegerField(default=0)),
                ("total_students_transport", models.PositiveIntegerField(default=0)),
                (
                    "avg_occupancy_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_fuel_consumed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_fuel_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_incidents", models.PositiveIntegerField(default=0)),
                ("total_delays", models.PositiveIntegerField(default=0)),
                (
                    "avg_delay_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("vehicles_maintained", models.PositiveIntegerField(default=0)),
                ("vehicles_in_repair", models.PositiveIntegerField(default=0)),
                (
                    "total_operational_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_daily_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transportation_daily_reports",
                "ordering": ["-date"],
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="TransportBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=10)),
                (
                    "fuel_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maintenance_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "salary_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "new_vehicle_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "miscellaneous_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "fuel_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maintenance_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "salary_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "new_vehicle_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "miscellaneous_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_budgets",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transport_budgets",
                "unique_together": {("school", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="TransportDriverSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning Shift"),
                            ("afternoon", "Afternoon Shift"),
                            ("full_day", "Full Day"),
                            ("overtime", "Overtime"),
                        ],
                        max_length=15,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("routes_assigned", models.JSONField(blank=True, default=list)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_on_leave", models.BooleanField(default=False)),
                ("leave_type", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_schedules",
                        to="transportation.driver",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_schedules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transport_driver_schedules",
                "ordering": ["-date"],
                "unique_together": {("driver", "date")},
            },
        ),
        migrations.CreateModel(
            name="TransportMonthlyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                ("total_operational_days", models.PositiveIntegerField(default=0)),
                ("total_trips", models.PositiveIntegerField(default=0)),
                ("total_routes_active", models.PositiveIntegerField(default=0)),
                ("vehicles_active", models.PositiveIntegerField(default=0)),
                ("vehicles_maintained", models.PositiveIntegerField(default=0)),
                (
                    "avg_fleet_age_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("total_students_served", models.PositiveIntegerField(default=0)),
                ("avg_daily_riders", models.PositiveIntegerField(default=0)),
                (
                    "total_fuel_liters",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fuel_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_fuel_efficiency",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_incidents", models.PositiveIntegerField(default=0)),
                ("total_accidents", models.PositiveIntegerField(default=0)),
                ("total_delays", models.PositiveIntegerField(default=0)),
                (
                    "on_time_percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_parent_rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("total_complaints", models.PositiveIntegerField(default=0)),
                ("complaints_resolved", models.PositiveIntegerField(default=0)),
                ("highlights", models.TextField(blank=True)),
                ("issues", models.TextField(blank=True)),
                ("next_month_plans", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_monthly_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "transport_monthly_reports",
                "unique_together": {("school", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="TransportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pickup_start", models.TimeField()),
                ("pickup_end", models.TimeField()),
                ("dropoff_start", models.TimeField(blank=True, null=True)),
                ("dropoff_end", models.TimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="transportation.route",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_schedules",
                        to="auth_service.school",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transportation.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "transport_schedules",
                "unique_together": {("route", "day_of_week")},
            },
        ),
    ]
