# Generated by Django 4.2.13 on 2026-07-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("application_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                            ("enrolled", "Enrolled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                ("previous_grade", models.CharField(blank=True, max_length=20)),
                ("applying_for_grade", models.CharField(max_length=20)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("guardian_name", models.CharField(blank=True, max_length=200)),
                ("guardian_phone", models.CharField(blank=True, max_length=20)),
                ("guardian_email", models.EmailField(blank=True, max_length=254)),
                ("guardian_relation", models.CharField(blank=True, max_length=50)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="How did they hear about us?",
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admissions_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentIntake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. Fall 2026 Intake", max_length=100),
                ),
                ("academic_year", models.CharField(blank=True, max_length=30)),
                ("application_start", models.DateField()),
                ("application_end", models.DateField()),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("upcoming", "Upcoming"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "max_applications",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = unlimited"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_intakes",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_intakes",
                "ordering": ["-application_start"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("birth_cert", "Birth Certificate"),
                            ("passport", "Passport"),
                            ("transcript", "Academic Transcript"),
                            ("recommendation", "Recommendation Letter"),
                            ("report_card", "Previous Report Card"),
                            ("medical", "Medical Records"),
                            ("photo", "Passport Photo"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_url", models.URLField(max_length=500)),
                ("file_name", models.CharField(max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="application",
            name="intake",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="admissions.enrollmentintake",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="auth_service.school",
            ),
        ),
        migrations.CreateModel(
            name="ApplicationReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Score out of 100", null=True
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("weaknesses", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        help_text="Strongly Recommend, Recommend, etc.",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="admissions.application",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admissions_reviews",
                "ordering": ["-created_at"],
                "unique_together": {("application", "reviewer")},
            },
        ),
    ]
