# Generated by Django 5.2.17 on 2026-08-11 04:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="linked_student",
            field=models.ForeignKey(
                blank=True,
                help_text="Student record created when this application is enrolled",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admission_application",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="offer_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="offer_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="tour_date",
            field=models.DateField(blank=True, help_text="Scheduled campus tour date", null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="toured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ApplicationTimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("created", "Application Created"),
                            ("submitted", "Submitted"),
                            ("tour_scheduled", "Tour Scheduled"),
                            ("tour_completed", "Tour Completed"),
                            ("offer_sent", "Offer Sent"),
                            ("offer_accepted", "Offer Accepted"),
                            ("enrolled", "Enrolled"),
                            ("status_changed", "Status Changed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="admissions.application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admissions_timeline",
                "ordering": ["-created_at"],
            },
        ),
    ]
