# Generated by Django 5.2.17 on 2026-08-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_application_linked_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="offer_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline for the family to accept the offer; after this date the offer expires.",
                null=True,
            ),
        ),
    ]
