# Generated by Django 5.2.17 on 2026-08-18 16:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_application_offer_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntranceAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        help_text="e.g. Written Test, Interview, Portfolio Review",
                        max_length=50,
                    ),
                ),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score out of 100",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Maximum possible score",
                        max_digits=5,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("assessor_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_assessments",
                "ordering": ["-created_at"],
            },
        ),
    ]
