# Generated by Django 5.1.15 on 2026-08-31 15:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0004_entranceassessment"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionsEmailNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("received", "Application Received"),
                            ("review", "Application Under Review"),
                            ("interview", "Interview Scheduled"),
                            ("document", "Document Request"),
                            ("decision", "Decision Made"),
                            ("acceptance", "Acceptance Letter"),
                            ("rejection", "Rejection Letter"),
                            ("waitlist", "Waitlist Notification"),
                            ("enrollment", "Enrollment Deadline Reminder"),
                            ("fee", "Fee Payment Reminder"),
                            ("welcome", "Welcome to School"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(max_length=150)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notifications",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_email_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionsPipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("application", "Application Received"),
                            ("documentation", "Documentation Complete"),
                            ("assessment", "Assessment Scheduled"),
                            ("interview", "Interview Scheduled"),
                            ("review", "Under Review"),
                            ("decision", "Decision Pending"),
                            ("enrollment", "Enrollment"),
                            ("onboarded", "Onboarded"),
                        ],
                        default="inquiry",
                        max_length=15,
                    ),
                ),
                ("inquiry_date", models.DateTimeField(blank=True, null=True)),
                ("application_date", models.DateTimeField(blank=True, null=True)),
                ("documentation_date", models.DateTimeField(blank=True, null=True)),
                ("assessment_date", models.DateTimeField(blank=True, null=True)),
                ("interview_date", models.DateTimeField(blank=True, null=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
                ("enrollment_date", models.DateTimeField(blank=True, null=True)),
                ("onboarded_date", models.DateTimeField(blank=True, null=True)),
                ("is_priority", models.BooleanField(default=False)),
                ("is_hot_lead", models.BooleanField(default=False)),
                ("lead_source", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline",
                        to="admissions.application",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions_pipelines",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_pipeline",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionsReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("summary", "Admissions Summary"),
                            ("pipeline", "Pipeline Analysis"),
                            ("conversion", "Conversion Rates"),
                            ("demographic", "Demographic Report"),
                            ("financial", "Financial Report"),
                            ("grade", "Grade-wise Report"),
                            ("source", "Source Analysis"),
                            ("timeline", "Timeline Analysis"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.TextField(blank=True)),
                ("findings", models.JSONField(default=dict)),
                ("recommendations", models.TextField(blank=True)),
                ("total_applications", models.PositiveIntegerField(default=0)),
                ("total_enrolled", models.PositiveIntegerField(default=0)),
                ("total_rejected", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("by_status", models.JSONField(default=dict)),
                ("by_grade", models.JSONField(default=dict)),
                ("by_source", models.JSONField(default=dict)),
                ("by_demographic", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.enrollmentintake",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionsSMSNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("received", "Application Received"),
                            ("interview", "Interview Reminder"),
                            ("decision", "Decision Made"),
                            ("enrollment", "Enrollment Deadline"),
                            ("fee", "Fee Reminder"),
                            ("general", "General Update"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_notifications",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_sms_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Credit/Debit Card"),
                            ("online", "Online Gateway"),
                            ("mobile", "Mobile Money"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("waiver_reason", models.TextField(blank=True)),
                ("gateway_response", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_fees",
                        to="admissions.application",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admissions_fees",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "required_fields",
                    models.JSONField(default=list, help_text="List of required fields"),
                ),
                (
                    "optional_fields",
                    models.JSONField(default=list, help_text="List of optional fields"),
                ),
                (
                    "required_documents",
                    models.JSONField(default=list, help_text="List of required documents"),
                ),
                (
                    "application_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("allow_late_applications", models.BooleanField(default=False)),
                ("late_fee_deadline_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_applications_per_student",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intake",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admissions.enrollmentintake",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_templates",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BulkApplicationImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "errors",
                    models.JSONField(default=list, help_text="List of import errors"),
                ),
                ("error_file_url", models.URLField(blank=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_applications",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_bulk_imports",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("confirmation_deadline", models.DateField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Deposit"),
                            ("paid", "Deposit Paid"),
                            ("waived", "Deposit Waived"),
                            ("refunded", "Deposit Refunded"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("deposit_paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deposit_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("decline_reason", models.TextField(blank=True)),
                (
                    "enrollment_documents",
                    models.JSONField(default=list, help_text="List of required enrollment documents"),
                ),
                ("documents_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_confirmation",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_enrollment_confirmations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In-Person"),
                            ("video", "Video Call"),
                            ("phone", "Phone Call"),
                            ("panel", "Panel Interview"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("meeting_link", models.URLField(blank=True)),
                ("meeting_id", models.CharField(blank=True, max_length=100)),
                (
                    "panel_members",
                    models.JSONField(default=list, help_text="List of panel member IDs"),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="Rating out of 5", null=True),
                ),
                ("recommendation", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="admissions.application",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admissions_interviews",
                "ordering": ["scheduled_date", "scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="MeritList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "grade",
                    models.CharField(help_text="Grade or program this list is for", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("total_applicants", models.PositiveIntegerField(default=0)),
                ("total_selected", models.PositiveIntegerField(default=0)),
                ("total_waitlisted", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merit_lists",
                        to="admissions.enrollmentintake",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merit_lists",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_merit_lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WaitlistManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("offered", "Offer Extended"),
                            ("accepted", "Accepted Offer"),
                            ("declined", "Declined Offer"),
                            ("expired", "Offer Expired"),
                            ("removed", "Removed from Waitlist"),
                        ],
                        default="waiting",
                        max_length=15,
                    ),
                ),
                ("offer_extended_at", models.DateTimeField(blank=True, null=True)),
                ("offer_expires_at", models.DateTimeField(blank=True, null=True)),
                ("offer_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("offer_declined_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("notification_count", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist",
                        to="admissions.application",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_waitlist",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="MeritListEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("selected", "Selected"),
                            ("waitlisted", "Waitlisted"),
                            ("rejected", "Rejected"),
                            ("declined", "Declined by Applicant"),
                        ],
                        default="selected",
                        max_length=15,
                    ),
                ),
                (
                    "academic_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "assessment_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "interview_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "extracurricular_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merit_entries",
                        to="admissions.application",
                    ),
                ),
                (
                    "merit_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="admissions.meritlist",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_merit_entries",
                "ordering": ["rank"],
                "unique_together": {("merit_list", "application")},
            },
        ),
        migrations.CreateModel(
            name="ReEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="invited",
                        max_length=15,
                    ),
                ),
                ("current_grade", models.CharField(max_length=20)),
                ("next_grade", models.CharField(max_length=20)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.TextField(blank=True)),
                (
                    "re_enrollment_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fee_paid", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="re_enrollments",
                        to="admissions.enrollmentintake",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="re_enrollments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="re_enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "admissions_re_enrollments",
                "ordering": ["-invited_at"],
                "unique_together": {("student", "intake")},
            },
        ),
    ]
