# Generated by Django 4.2.13 on 2026-07-15 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male Only"),
                            ("female", "Female Only"),
                            ("coed", "Co-Educational"),
                        ],
                        default="male",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("under_maintenance", "Under Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("total_floors", models.PositiveSmallIntegerField(default=1)),
                ("rules", models.TextField(blank=True)),
                (
                    "amenities",
                    models.TextField(blank=True, help_text="Comma-separated list"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assistant_warden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_warden_hostels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostels",
                        to="auth_service.school",
                    ),
                ),
                (
                    "warden",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warden_hostels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_hostels",
                "ordering": ["name"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="HostelVisitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visitor_name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "id_proof",
                    models.CharField(
                        blank=True, help_text="ID proof number", max_length=100
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("in_time", models.DateTimeField()),
                ("out_time", models.DateTimeField(blank=True, null=True)),
                ("relationship", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitors",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "student_visited",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_visitors",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_visitors",
                "ordering": ["-in_time"],
            },
        ),
        migrations.CreateModel(
            name="HostelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=20)),
                ("floor", models.PositiveSmallIntegerField(default=1)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("triple", "Triple"),
                            ("dormitory", "Dormitory (4+)"),
                        ],
                        default="double",
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(default=2)),
                ("is_furnished", models.BooleanField(default=True)),
                ("has_ac", models.BooleanField(default=False)),
                ("has_attached_bathroom", models.BooleanField(default=True)),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_rooms",
                "ordering": ["hostel", "floor", "room_number"],
                "unique_together": {("hostel", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="HostelFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("triple", "Triple"),
                            ("dormitory", "Dormitory (4+)"),
                        ],
                        help_text="Leave blank to apply to all room types",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("includes_meals", models.BooleanField(default=False)),
                ("includes_laundry", models.BooleanField(default=False)),
                ("includes_wifi", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_fees",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_fees",
                "ordering": ["hostel", "name"],
            },
        ),
        migrations.CreateModel(
            name="HostelAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("checked_out", "Checked Out"),
                            ("transferred", "Transferred"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField(blank=True, null=True)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostel_allocations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="hostel.hostelroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_allocations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_allocations",
                "ordering": ["-check_in_date"],
                "unique_together": {("student", "check_in_date")},
            },
        ),
    ]
