# Generated by Django 5.1.15 on 2026-08-31 16:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0001_initial"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("checkout_date", models.DateField()),
                ("room_inspected", models.BooleanField(default=False)),
                ("inspection_notes", models.TextField(blank=True)),
                ("damage_detected", models.BooleanField(default=False)),
                ("damage_description", models.TextField(blank=True)),
                (
                    "damage_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "items_returned",
                    models.JSONField(default=list, help_text="List of items returned"),
                ),
                (
                    "missing_items",
                    models.JSONField(default=list, help_text="List of missing items"),
                ),
                (
                    "pending_dues",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "security_deposit_refund",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("keys_returned", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_process",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_checkout_process",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("cleanliness", "Cleanliness"),
                            ("noise", "Noise"),
                            ("security", "Security"),
                            ("food", "Food Quality"),
                            ("roommate", "Roommate Issues"),
                            ("facility", "Facility Issues"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "satisfaction_rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="Rating out of 5", null=True),
                ),
                ("feedback", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostel_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_complaints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("warden", "Hostel Warden"),
                            ("assistant_warden", "Assistant Warden"),
                            ("security", "Security"),
                            ("medical", "Medical"),
                            ("fire", "Fire Department"),
                            ("police", "Police"),
                            ("parent", "Parent/Guardian"),
                            ("school", "School Administration"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone_primary", models.CharField(max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_available_24x7", models.BooleanField(default=False)),
                ("available_hours", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_emergency_contacts",
                "ordering": ["contact_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="HostelFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("room", "Room Quality"),
                            ("cleanliness", "Cleanliness"),
                            ("food", "Food Quality"),
                            ("security", "Security"),
                            ("staff", "Staff Behavior"),
                            ("facilities", "Facilities"),
                            ("maintenance", "Maintenance"),
                            ("general", "General Feedback"),
                            ("suggestion", "Suggestion"),
                            ("complaint", "Complaint"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField()),
                ("suggestion", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HostelNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("general", "General Announcement"),
                            ("emergency", "Emergency"),
                            ("maintenance", "Maintenance Update"),
                            ("leave", "Leave Status"),
                            ("complaint", "Complaint Update"),
                            ("fee", "Fee Reminder"),
                            ("event", "Hostel Event"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("all", "All Students"),
                            ("specific", "Specific Students"),
                            ("warden", "Warden Only"),
                            ("parent", "Parents"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(default=list, help_text="List of recipient IDs"),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_count", models.PositiveIntegerField(default=0)),
                ("is_priority", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HostelReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("occupancy", "Occupancy Report"),
                            ("financial", "Financial Report"),
                            ("maintenance", "Maintenance Report"),
                            ("discipline", "Discipline Report"),
                            ("attendance", "Attendance Report"),
                            ("mess", "Mess Report"),
                            ("complaint", "Complaint Report"),
                            ("general", "General Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.TextField(blank=True)),
                ("findings", models.JSONField(default=dict)),
                ("recommendations", models.TextField(blank=True)),
                ("total_rooms", models.PositiveIntegerField(default=0)),
                ("occupied_rooms", models.PositiveIntegerField(default=0)),
                (
                    "occupancy_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total_complaints", models.PositiveIntegerField(default=0)),
                ("resolved_complaints", models.PositiveIntegerField(default=0)),
                ("total_maintenance", models.PositiveIntegerField(default=0)),
                ("completed_maintenance", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                (
                    "item_category",
                    models.CharField(
                        choices=[
                            ("furniture", "Furniture"),
                            ("electronics", "Electronics"),
                            ("bedding", "Bedding"),
                            ("fixture", "Fixtures"),
                            ("appliance", "Appliances"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("needs_repair", "Needs Repair"),
                            ("damaged", "Damaged"),
                            ("retired", "Retired"),
                        ],
                        default="good",
                        max_length=15,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=100)),
                ("last_inspected_date", models.DateField(blank=True, null=True)),
                ("condition_notes", models.TextField(blank=True)),
                ("asset_tag", models.CharField(blank=True, max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory",
                        to="hostel.hostelroom",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_inventory",
                "ordering": ["item_name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("sick", "Sick Leave"),
                            ("home", "Home Leave"),
                            ("personal", "Personal Leave"),
                            ("emergency", "Emergency Leave"),
                            ("academic", "Academic Leave"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("total_days", models.PositiveSmallIntegerField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("parent_consent", models.BooleanField(default=False)),
                ("emergency_contact", models.CharField(blank=True, max_length=150)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_leave_management",
                "ordering": ["-from_date"],
            },
        ),
        migrations.CreateModel(
            name="MessManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "menu_items",
                    models.JSONField(default=list, help_text="List of menu items"),
                ),
                ("description", models.TextField(blank=True)),
                ("is_vegetarian", models.BooleanField(default=True)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_halal", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="Average rating out of 5", null=True),
                ),
                (
                    "cost_per_meal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_menu",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_mess_management",
                "ordering": ["-date", "meal_type"],
                "unique_together": {("hostel", "date", "meal_type")},
            },
        ),
        migrations.CreateModel(
            name="RoomInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Check"),
                            ("weekly", "Weekly Inspection"),
                            ("monthly", "Monthly Inspection"),
                            ("random", "Random Check"),
                            ("checkout", "Checkout Inspection"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "cleanliness_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "orderliness_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "condition_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "issues_found",
                    models.JSONField(default=list, help_text="List of issues found"),
                ),
                ("has_issues", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("action_required", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="hostel.hostelroom",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_inspections",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="RoomMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("furniture", "Furniture"),
                            ("cleaning", "Cleaning"),
                            ("painting", "Painting"),
                            ("general", "General Maintenance"),
                            ("emergency", "Emergency Repair"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("reported_date", models.DateTimeField(auto_now_add=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostel_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="hostel.hostelroom",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_maintenance",
                "ordering": ["-reported_date"],
            },
        ),
        migrations.CreateModel(
            name="RoomTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("requested_date", models.DateField(auto_now_add=True)),
                ("transfer_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_from",
                        to="hostel.hostelroom",
                    ),
                ),
                (
                    "to_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_to",
                        to="hostel.hostelroom",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_room_transfers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HostelAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("on_leave", "On Leave"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("is_in_campus", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_attendance",
                "ordering": ["-date"],
                "unique_together": {("allocation", "date")},
            },
        ),
        migrations.CreateModel(
            name="MessAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attended", "Attended"),
                            ("absent", "Absent"),
                            ("skipped", "Skipped"),
                        ],
                        default="attended",
                        max_length=10,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_attendance",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "mess_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="hostel.messmanagement",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_mess_attendance",
                "unique_together": {("mess_menu", "allocation")},
            },
        ),
    ]
