# Generated by Django 5.1.15 on 2026-09-01 09:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
        ("hostel", "0002_add_hostel_gaps"),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonAreaBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("study", "Study Room"),
                            ("gym", "Gym / Fitness"),
                            ("tv", "TV Room"),
                            ("game", "Game Room"),
                            ("library", "Hostel Library"),
                            ("terrace", "Terrace / Garden"),
                            ("meeting", "Meeting Room"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("area_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("active", "In Use"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="booked",
                        max_length=10,
                    ),
                ),
                ("booking_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("group_size", models.PositiveIntegerField(default=1)),
                ("purpose", models.TextField(blank=True)),
                ("rules_acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="common_area_bookings_guest",
                        to="students.student",
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_area_bookings",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_area_bookings",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "common_area_bookings",
                "ordering": ["-booking_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="HostelAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_name", models.CharField(max_length=200)),
                ("asset_tag", models.CharField(blank=True, max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                            ("retired", "Retired"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("last_inspected", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="hostel.hostelroom",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_assets",
                "ordering": ["asset_name"],
            },
        ),
        migrations.CreateModel(
            name="HostelAssetTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transfer_date", models.DateField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "condition_at_transfer",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                            ("retired", "Retired"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="hostel.hostelasset",
                    ),
                ),
                (
                    "from_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_sent",
                        to="hostel.hostelroom",
                    ),
                ),
                (
                    "to_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_received",
                        to="hostel.hostelroom",
                    ),
                ),
                (
                    "transferred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_asset_transfers",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="HostelEmergencyProtocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[
                            ("fire", "Fire Emergency"),
                            ("medical", "Medical Emergency"),
                            ("natural", "Natural Disaster"),
                            ("lockdown", "Lockdown"),
                            ("evacuation", "Evacuation"),
                            ("power", "Power Outage"),
                            ("other", "Other Emergency"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "procedures",
                    models.TextField(help_text="Step-by-step emergency procedures"),
                ),
                (
                    "contacts",
                    models.TextField(help_text="Emergency contacts and numbers"),
                ),
                ("assembly_point", models.CharField(blank=True, max_length=200)),
                ("last_drill_date", models.DateField(blank=True, null=True)),
                ("next_drill_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="hostel/emergency_docs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_protocols",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_emergency_protocols",
                "ordering": ["emergency_type"],
            },
        ),
        migrations.CreateModel(
            name="HostelEmergencyDrill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("drill_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("participants_count", models.PositiveIntegerField(default=0)),
                (
                    "evaluation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("satisfactory", "Satisfactory"),
                            ("needs_improvement", "Needs Improvement"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "evacuation_time_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("issues_identified", models.TextField(blank=True)),
                ("improvements_needed", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_drills",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostelemergencyprotocol",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_emergency_drills",
                "ordering": ["-drill_date"],
            },
        ),
        migrations.CreateModel(
            name="HostelEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("orientation", "Resident Orientation"),
                            ("social", "Social Event"),
                            ("cleanliness", "Cleanliness Drive"),
                            ("safety", "Safety Drill"),
                            ("cultural", "Cultural Event"),
                            ("sports", "Sports Event"),
                            ("workshop", "Workshop"),
                            ("celebration", "Celebration"),
                            ("other", "Other"),
                        ],
                        default="social",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=15,
                    ),
                ),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("max_participants", models.PositiveIntegerField(default=50)),
                ("current_participants", models.PositiveIntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("total_feedback", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="HostelInspectionSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="weekly",
                        max_length=15,
                    ),
                ),
                ("day_of_week", models.CharField(blank=True, max_length=10)),
                ("time_of_day", models.TimeField(blank=True, null=True)),
                (
                    "rooms_to_inspect",
                    models.CharField(
                        blank=True,
                        help_text="All, Floor 1, Specific rooms, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Checklist items for inspection",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                ("next_inspection_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection_schedules",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hostel_inspection_schedules",
            },
        ),
        migrations.CreateModel(
            name="LaundryService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup Scheduled"),
                            ("picked_up", "Picked Up"),
                            ("in_process", "In Process"),
                            ("ready", "Ready for Delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pickup",
                        max_length=15,
                    ),
                ),
                (
                    "garment_type",
                    models.CharField(
                        choices=[
                            ("uniform", "Uniform"),
                            ("bedding", "Bedding"),
                            ("personal", "Personal Clothes"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=15,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("delivery_time", models.TimeField(blank=True, null=True)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("paid", models.BooleanField(default=False)),
                ("special_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laundry_requests",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laundry_services",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "laundry_services",
                "ordering": ["-pickup_date"],
            },
        ),
        migrations.CreateModel(
            name="MessDietaryRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("gluten_free", "Gluten Free"),
                            ("diabetic", "Diabetic Friendly"),
                            ("low_sodium", "Low Sodium"),
                            ("halal", "Halal"),
                            ("kosher", "Kosher"),
                            ("allergy", "Allergy Specific"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("medical_reason", models.TextField(blank=True)),
                (
                    "doctor_note",
                    models.FileField(blank=True, null=True, upload_to="hostel/dietary_notes/"),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_dietary_requests",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_dietary_requests",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "mess_dietary_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "food_quality",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "portion_size",
                    models.CharField(
                        blank=True,
                        help_text="Too Small, Just Right, Too Large",
                        max_length=20,
                    ),
                ),
                (
                    "hygiene_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "liked_items",
                    models.TextField(blank=True, help_text="What did you like?"),
                ),
                (
                    "disliked_items",
                    models.TextField(blank=True, help_text="What could be improved?"),
                ),
                ("suggestions", models.TextField(blank=True)),
                ("meal_date", models.DateField()),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_feedbacks",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_feedbacks",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "mess_feedbacks",
                "ordering": ["-meal_date"],
            },
        ),
        migrations.CreateModel(
            name="MessMenuPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("snack", "Snack"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "week_number",
                    models.PositiveIntegerField(default=1, help_text="Week number for rotation"),
                ),
                ("main_course", models.TextField(blank=True)),
                ("side_dish", models.TextField(blank=True)),
                ("bread_rice", models.TextField(blank=True)),
                ("dessert", models.TextField(blank=True)),
                ("beverage", models.TextField(blank=True)),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_student_rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_menu_plans",
                        to="hostel.hostel",
                    ),
                ),
            ],
            options={
                "db_table": "mess_menu_plans",
                "ordering": ["week_number", "day_of_week", "meal_type"],
            },
        ),
        migrations.CreateModel(
            name="RoomKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("returned", "Returned"),
                            ("lost", "Lost"),
                            ("replaced", "Replaced"),
                        ],
                        default="assigned",
                        max_length=10,
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "replacement_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("reported_lost_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostel_keys",
                        to="students.student",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="hostel.hostelroom",
                    ),
                ),
            ],
            options={
                "db_table": "room_keys",
                "ordering": ["key_number"],
            },
        ),
        migrations.CreateModel(
            name="RoommatePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sleep_time", models.TimeField(blank=True, null=True)),
                ("wake_time", models.TimeField(blank=True, null=True)),
                ("is_light_sleeper", models.BooleanField(default=False)),
                (
                    "study_habits",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Quiet, Background noise",
                        max_length=50,
                    ),
                ),
                ("prefers_study_at", models.CharField(blank=True, max_length=50)),
                (
                    "visitor_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Never, Rarely, Sometimes, Often",
                        max_length=50,
                    ),
                ),
                ("is_social", models.BooleanField(default=True)),
                ("smoking", models.BooleanField(default=False)),
                ("snoring", models.BooleanField(default=False)),
                (
                    "neatness_level",
                    models.CharField(
                        blank=True,
                        help_text="Very Neat, Average, Relaxed",
                        max_length=20,
                    ),
                ),
                ("temperature_preference", models.CharField(blank=True, max_length=20)),
                ("additional_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avoid_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="avoided_by_roommate",
                        to="students.student",
                    ),
                ),
                (
                    "roommate_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_by_roommate",
                        to="students.student",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_preferences",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_preferences",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "roommate_preferences",
            },
        ),
        migrations.CreateModel(
            name="VisitorPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visitor_name", models.CharField(max_length=200)),
                ("visitor_phone", models.CharField(blank=True, max_length=30)),
                ("visitor_id_number", models.CharField(blank=True, max_length=50)),
                ("relationship", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("expired", "Expired"),
                        ],
                        default="requested",
                        max_length=15,
                    ),
                ),
                ("visit_date", models.DateField()),
                ("expected_arrival", models.TimeField()),
                ("expected_departure", models.TimeField()),
                ("actual_arrival", models.TimeField(blank=True, null=True)),
                ("actual_departure", models.TimeField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("approval_notes", models.TextField(blank=True)),
                ("id_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_pass_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_passes",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "id_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_id_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_passes",
                        to="students.student",
                    ),
                ),
                (
                    "room_visited",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostelroom",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_passes",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "visitor_passes",
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="HostelAttendanceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("missing", "Missing Check-in"),
                            ("no_show", "No-show for Roll Call"),
                            ("late", "Late Return"),
                            ("unauthorized", "Unauthorized Absence"),
                            ("leave_violation", "Leave Policy Violation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("alert_date", models.DateField()),
                ("description", models.TextField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_alerts",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "related_attendance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostelattendance",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hostel_alert_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_attendance_alerts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_attendance_alerts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_attendance_alerts",
                "ordering": ["-alert_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "alert_type"],
                        name="hostel_atte_student_4cfe08_idx",
                    ),
                    models.Index(
                        fields=["school", "status", "severity"],
                        name="hostel_atte_school__164283_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HostelEventParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("attended", models.BooleanField(default=False)),
                (
                    "feedback_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("feedback_comment", models.TextField(blank=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="hostel.hostelevent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_event_participations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_event_participants",
                "unique_together": {("event", "student")},
            },
        ),
        migrations.CreateModel(
            name="HostelFeePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partial", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "late_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank Transfer"),
                            ("online", "Online Payment"),
                            ("cheque", "Cheque"),
                            ("scholarship", "Scholarship/Discount"),
                        ],
                        max_length=15,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                (
                    "billing_period",
                    models.CharField(blank=True, help_text="e.g., Jan 2026", max_length=50),
                ),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "hostel_fee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostelfee",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_fee_payments",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "hostel_fee_payments",
                "ordering": ["-due_date"],
                "indexes": [
                    models.Index(
                        fields=["allocation", "status"],
                        name="hostel_fee__allocat_d08aff_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoommateAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Compatibility score 0-100",
                        max_digits=5,
                    ),
                ),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_assignments",
                        to="hostel.hostelroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_assignments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "roommate_assignments",
                "unique_together": {("room", "student")},
            },
        ),
        migrations.CreateModel(
            name="RoommateMatchRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("response_message", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_match_requests_received",
                        to="students.student",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roommate_match_requests_sent",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "roommate_match_requests",
                "unique_together": {("requester", "requested")},
            },
        ),
        migrations.CreateModel(
            name="WellnessCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine Check"),
                            ("follow_up", "Follow-up Check"),
                            ("welfare", "Welfare Check"),
                            ("medical", "Medical Check"),
                            ("mental", "Mental Health Check"),
                        ],
                        default="routine",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("issue", "Issue Found"),
                            ("escalated", "Escalated"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("check_date", models.DateField()),
                (
                    "physical_wellbeing",
                    models.CharField(blank=True, help_text="Good, Fair, Concern", max_length=20),
                ),
                (
                    "emotional_state",
                    models.CharField(
                        blank=True,
                        help_text="Stable, Anxious, Distressed",
                        max_length=20,
                    ),
                ),
                ("room_condition", models.CharField(blank=True, max_length=20)),
                ("concerns_noted", models.TextField(blank=True)),
                ("action_taken", models.TextField(blank=True)),
                ("referred_to", models.CharField(blank=True, max_length=200)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("parent_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostelallocation",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellness_checks",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellness_checks",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "wellness_checks",
                "ordering": ["-check_date"],
                "indexes": [
                    models.Index(
                        fields=["student", "check_type"],
                        name="wellness_ch_student_620e77_idx",
                    )
                ],
            },
        ),
    ]
