# Generated by Django 5.1.15 on 2026-09-01 10:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
        (
            "infrastructure",
            "0002_accesscontrolpoint_buildinginspection_cctvcamera_and_more",
        ),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        ("timetable", "0003_academiccalendar_cocurricularschedule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., Fall 2026, Spring 2027", max_length=200),
                ),
                ("academic_year", models.CharField(max_length=10)),
                ("semester", models.PositiveIntegerField(help_text="1, 2, 3, etc.")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("enrollment_start", models.DateField(blank=True, null=True)),
                ("enrollment_end", models.DateField(blank=True, null=True)),
                ("exam_start_date", models.DateField(blank=True, null=True)),
                ("exam_end_date", models.DateField(blank=True, null=True)),
                ("results_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="upcoming",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_sessions",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "academic_sessions",
                "ordering": ["-academic_year", "-semester"],
            },
        ),
        migrations.CreateModel(
            name="BellSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Day"),
                            ("early", "Early Dismissal"),
                            ("late", "Late Start"),
                            ("special", "Special Schedule"),
                        ],
                        default="regular",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bell_schedules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "bell_schedules",
            },
        ),
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grade_level", models.CharField(max_length=50)),
                (
                    "section_name",
                    models.CharField(help_text="e.g., A, B, Science, Arts", max_length=50),
                ),
                ("academic_year", models.CharField(max_length=10)),
                ("max_students", models.PositiveIntegerField(default=40)),
                ("current_students", models.PositiveIntegerField(default=0)),
                (
                    "subjects",
                    models.JSONField(blank=True, default=list, help_text="List of subject codes"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_groups_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "homeroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_groups",
                        to="infrastructure.room",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_groups",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "class_groups",
                "ordering": ["grade_level", "section_name"],
                "unique_together": {("school", "grade_level", "section_name", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="ExamRoomAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seating_capacity", models.PositiveIntegerField(default=30)),
                ("students_allocated", models.PositiveIntegerField(default=0)),
                (
                    "seating_arrangement",
                    models.CharField(
                        blank=True,
                        help_text="Rows, Clusters, Individual, etc.",
                        max_length=50,
                    ),
                ),
                ("equipment_needed", models.TextField(blank=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("is_ready", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "co_invigilator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="co_invigilated_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_allocations",
                        to="timetable.examschedule",
                    ),
                ),
                (
                    "invigilator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_allocations",
                        to="infrastructure.room",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_room_allocations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "exam_room_allocations",
                "unique_together": {("exam_schedule", "room")},
            },
        ),
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("plan_date", models.DateField()),
                ("topic", models.CharField(max_length=200)),
                ("learning_objectives", models.TextField(blank=True)),
                ("content_outline", models.TextField(blank=True)),
                ("teaching_methods", models.TextField(blank=True)),
                ("resources_needed", models.TextField(blank=True)),
                ("materials", models.TextField(blank=True)),
                ("formative_assessment", models.TextField(blank=True)),
                ("homework", models.TextField(blank=True)),
                ("differentiation_strategies", models.TextField(blank=True)),
                ("special_needs_accommodations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("delivered", "Delivered"),
                            ("revision", "Needs Revision"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("post_lesson_notes", models.TextField(blank=True)),
                ("what_worked_well", models.TextField(blank=True)),
                ("areas_for_improvement", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.classgroup",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.period",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.timetableslot",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_lesson_plans",
                "ordering": ["-plan_date"],
            },
        ),
        migrations.CreateModel(
            name="SeatingArrangement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                ("row", models.PositiveIntegerField(default=0)),
                ("column", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room_allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_arrangements",
                        to="timetable.examroomallocation",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_seatings",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "seating_arrangements",
                "unique_together": {("room_allocation", "seat_number")},
            },
        ),
        migrations.CreateModel(
            name="SubstituteSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("subject", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("class_covered", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.classgroup",
                    ),
                ),
                (
                    "lesson_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.lessonplan",
                    ),
                ),
                (
                    "original_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substituted_for",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_schedules",
                        to="auth_service.school",
                    ),
                ),
                (
                    "substitute_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.timetableslot",
                    ),
                ),
            ],
            options={
                "db_table": "substitute_schedules",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="TimetableAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=10)),
                ("semester", models.CharField(blank=True, max_length=10)),
                ("generation_date", models.DateField()),
                ("total_classes", models.PositiveIntegerField(default=0)),
                ("total_slots", models.PositiveIntegerField(default=0)),
                ("total_teachers", models.PositiveIntegerField(default=0)),
                ("total_rooms", models.PositiveIntegerField(default=0)),
                ("conflicts_found", models.PositiveIntegerField(default=0)),
                ("conflicts_resolved", models.PositiveIntegerField(default=0)),
                (
                    "validation_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_teacher_load",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("max_teacher_load", models.PositiveIntegerField(default=0)),
                (
                    "avg_room_utilization",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "generation_time_seconds",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_analytics",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_analytics",
            },
        ),
        migrations.CreateModel(
            name="TimetableChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("swap", "Period Swap"),
                            ("room", "Room Change"),
                            ("time", "Time Change"),
                            ("teacher", "Teacher Change"),
                            ("cancel", "Class Cancellation"),
                            ("extra", "Extra Class"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("implemented", "Implemented"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("approval_notes", models.TextField(blank=True)),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                ("is_urgent", models.BooleanField(default=False)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_change_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_requests_from",
                        to="timetable.timetableslot",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_requests_to",
                        to="timetable.timetableslot",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_change_requests",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_change_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimetableResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("projector", "Projector"),
                            ("lab", "Laboratory"),
                            ("computer", "Computer Lab"),
                            ("library", "Library Room"),
                            ("auditorium", "Auditorium"),
                            ("sports", "Sports Facility"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "hourly_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_resources",
                        to="infrastructure.room",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_resources",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_resources",
            },
        ),
        migrations.CreateModel(
            name="TimetableResourceBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("purpose", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.classgroup",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_bookings",
                        to="timetable.schoolevent",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="timetable.timetableresource",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_resource_bookings",
                "ordering": ["-booking_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimetableValidationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("teacher_load", "Teacher Load Limit"),
                            ("room_capacity", "Room Capacity"),
                            ("spacing", "Subject Spacing"),
                            ("consecutive", "Consecutive Period Limit"),
                            ("break", "Break Required"),
                            ("grade_conflict", "Grade Conflict"),
                            ("teacher_conflict", "Teacher Conflict"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "max_value",
                    models.PositiveIntegerField(blank=True, help_text="Maximum allowed value", null=True),
                ),
                (
                    "min_value",
                    models.PositiveIntegerField(blank=True, help_text="Minimum required value", null=True),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "is_hard_constraint",
                    models.BooleanField(
                        default=True,
                        help_text="Hard = cannot violate, Soft = warning only",
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_validation_rules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_validation_rules",
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="TimetableValidationError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error (Must Fix)"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="error",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_errors",
                        to="timetable.timetableslot",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="timetable.timetablevalidationrule",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_validation_errors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimetableVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=10)),
                ("semester", models.CharField(blank=True, max_length=10)),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "timetable_data",
                    models.JSONField(default=dict, help_text="Full timetable snapshot as JSON"),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("changes_from_previous", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_versions",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="BellScheduleEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "is_break",
                    models.BooleanField(default=False, help_text="Is this a break/lunch period?"),
                ),
                (
                    "break_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Morning Break, Lunch",
                        max_length=50,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "bell_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="timetable.bellschedule",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bell_entries",
                        to="timetable.period",
                    ),
                ),
            ],
            options={
                "db_table": "bell_schedule_entries",
                "ordering": ["sort_order"],
                "unique_together": {("bell_schedule", "period")},
            },
        ),
        migrations.CreateModel(
            name="ClassGroupEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enrolled_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="timetable.classgroup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_group_enrollments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "class_group_enrollments",
                "unique_together": {("class_group", "student")},
            },
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=10)),
                ("total_weekly_periods", models.PositiveIntegerField(default=0)),
                ("subjects_scheduled", models.JSONField(blank=True, default=list)),
                ("is_finalized", models.BooleanField(default=False)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_schedules",
                        to="timetable.classgroup",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "class_schedules",
                "unique_together": {("class_group", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="DailySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("day_of_week", models.CharField(max_length=10)),
                ("total_classes_scheduled", models.PositiveIntegerField(default=0)),
                ("total_classes_conducted", models.PositiveIntegerField(default=0)),
                ("total_classes_cancelled", models.PositiveIntegerField(default=0)),
                ("total_substitutes", models.PositiveIntegerField(default=0)),
                ("is_holiday", models.BooleanField(default=False)),
                ("holiday_name", models.CharField(blank=True, max_length=200)),
                ("is_special_schedule", models.BooleanField(default=False)),
                ("special_schedule_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_schedules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "daily_schedules",
                "ordering": ["-date"],
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="RoomUtilization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_hours_available",
                    models.DecimalField(decimal_places=2, default=8, max_digits=5),
                ),
                (
                    "total_hours_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "utilization_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "teaching_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "exam_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "meeting_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "event_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("conflicts_detected", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utilization_records",
                        to="infrastructure.room",
                    ),
                ),
            ],
            options={
                "db_table": "room_utilization",
                "ordering": ["-date"],
                "unique_together": {("room", "date")},
            },
        ),
        migrations.CreateModel(
            name="ExamAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("minutes_late", models.PositiveIntegerField(default=0)),
                ("invigilator_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="timetable.examscheduleentry",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attendances",
                        to="students.student",
                    ),
                ),
                (
                    "seating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="timetable.seatingarrangement",
                    ),
                ),
            ],
            options={
                "db_table": "exam_attendances",
                "unique_together": {("exam_entry", "student")},
            },
        ),
        migrations.CreateModel(
            name="SubjectTeacherAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("subject_code", models.CharField(blank=True, max_length=20)),
                ("periods_per_week", models.PositiveIntegerField(default=3)),
                ("academic_year", models.CharField(max_length=10)),
                ("semester", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="timetable.classgroup",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_teacher_assignments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subject_teacher_assignments",
                "unique_together": {("teacher", "subject", "class_group", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="TeacherWorkload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=10)),
                ("semester", models.CharField(blank=True, max_length=10)),
                ("total_periods_per_week", models.PositiveIntegerField(default=0)),
                ("total_classes", models.PositiveIntegerField(default=0)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("subjects_taught", models.JSONField(blank=True, default=list)),
                ("classes_taught", models.JSONField(blank=True, default=list)),
                ("max_periods_per_week", models.PositiveIntegerField(default=30)),
                (
                    "workload_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "duty_hours_per_week",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_workloads",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_workloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teacher_workloads",
                "unique_together": {("teacher", "academic_year", "semester")},
            },
        ),
    ]
