# Generated by Django 5.1.15 on 2026-09-01 09:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
        ("infrastructure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessControlPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("point_name", models.CharField(max_length=100)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("card", "Card Reader"),
                            ("biometric", "Biometric"),
                            ("pin", "PIN Pad"),
                            ("manual", "Manual Lock"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("access_start_time", models.TimeField(blank=True, null=True)),
                ("access_end_time", models.TimeField(blank=True, null=True)),
                ("restricted_access", models.BooleanField(default=False)),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_control_points",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_control_points",
                        to="infrastructure.room",
                    ),
                ),
            ],
            options={
                "db_table": "access_control_points",
            },
        ),
        migrations.CreateModel(
            name="BuildingInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("fire", "Fire Safety"),
                            ("structural", "Structural"),
                            ("electrical", "Electrical Safety"),
                            ("plumbing", "Plumbing"),
                            ("accessibility", "Accessibility"),
                            ("general", "General"),
                        ],
                        max_length=15,
                    ),
                ),
                ("inspection_date", models.DateField()),
                ("inspector_name", models.CharField(blank=True, max_length=200)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("conditional", "Conditional"),
                            ("fail", "Fail"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                ("violations", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("corrective_actions", models.TextField(blank=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="infrastructure/building_inspections/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_inspections",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "building_inspections",
            },
        ),
        migrations.CreateModel(
            name="CCTVCamera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("camera_name", models.CharField(max_length=100)),
                ("camera_id", models.CharField(max_length=50, unique=True)),
                ("location_description", models.CharField(blank=True, max_length=200)),
                ("stream_url", models.URLField(blank=True)),
                ("recording_enabled", models.BooleanField(default=True)),
                ("storage_days", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="online",
                        max_length=15,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cctv_cameras",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cctv_cameras",
                        to="infrastructure.room",
                    ),
                ),
            ],
            options={
                "db_table": "cctv_cameras",
            },
        ),
        migrations.CreateModel(
            name="EnergyMeter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meter_number", models.CharField(max_length=50, unique=True)),
                (
                    "meter_type",
                    models.CharField(
                        choices=[
                            ("electric", "Electric"),
                            ("water", "Water"),
                            ("gas", "Gas"),
                            ("solar", "Solar"),
                        ],
                        max_length=10,
                    ),
                ),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("last_reading_date", models.DateField(blank=True, null=True)),
                (
                    "last_reading_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_meters",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="energy_meters",
                        to="infrastructure.room",
                    ),
                ),
            ],
            options={
                "db_table": "energy_meters",
            },
        ),
        migrations.CreateModel(
            name="EnergyAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("high", "High Consumption"),
                            ("spike", "Sudden Spike"),
                            ("leak", "Suspected Leak"),
                            ("fault", "Meter Fault"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "threshold_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "actual_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="energy_alerts",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.energymeter",
                    ),
                ),
            ],
            options={
                "db_table": "energy_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GreenInitiative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "initiative_type",
                    models.CharField(
                        choices=[
                            ("solar", "Solar Energy"),
                            ("rainwater", "Rainwater Harvesting"),
                            ("waste", "Waste Reduction"),
                            ("tree", "Tree Plantation"),
                            ("audit", "Energy Audit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="proposed",
                        max_length=15,
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "estimated_savings",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "carbon_reduction_kg",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_end_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.building",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="green_initiatives",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "green_initiatives",
            },
        ),
        migrations.CreateModel(
            name="InfrastructureAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("power", "Power Outage"),
                            ("water", "Water Leak"),
                            ("hvac", "HVAC Failure"),
                            ("structural", "Structural Issue"),
                            ("flooding", "Flooding"),
                            ("fire", "Fire"),
                            ("gas", "Gas Leak"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infra_alert_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.building",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.room",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infrastructure_alerts",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "infrastructure_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InfrastructureMaintenanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                ("estimated_completion", models.DateField(blank=True, null=True)),
                ("actual_completion", models.DateField(blank=True, null=True)),
                (
                    "estimated_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "actual_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "satisfaction_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infra_requests_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.building",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="infra_requests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.room",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infra_maintenance_requests",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "infra_maintenance_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LightingSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zone_name", models.CharField(blank=True, max_length=200)),
                ("day_of_week", models.CharField(blank=True, max_length=10)),
                ("on_time", models.TimeField()),
                ("off_time", models.TimeField()),
                ("brightness_level", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lighting_schedules",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.room",
                    ),
                ),
            ],
            options={
                "db_table": "lighting_schedules",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceCostTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cost_category",
                    models.CharField(
                        choices=[
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("hvac", "HVAC"),
                            ("roofing", "Roofing"),
                            ("painting", "Painting"),
                            ("landscaping", "Landscaping"),
                            ("cleaning", "Cleaning"),
                            ("general", "General"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("cost_date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.building",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_cost_tracking",
                        to="auth_service.school",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_tracking",
                        to="infrastructure.workorder",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_cost_tracking",
            },
        ),
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("total_spots", models.PositiveIntegerField(default=0)),
                ("available_spots", models.PositiveIntegerField(default=0)),
                ("is_covered", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_lots",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "parking_lots",
            },
        ),
        migrations.CreateModel(
            name="PestControlInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("requested", "Requested"),
                            ("follow_up", "Follow-up"),
                        ],
                        default="routine",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("inspector_name", models.CharField(blank=True, max_length=200)),
                ("pests_found", models.TextField(blank=True)),
                ("treatment_applied", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                (
                    "treatment_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="infrastructure/pest_control/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_inspections",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.room",
                    ),
                ),
            ],
            options={
                "db_table": "pest_control_inspections",
            },
        ),
        migrations.CreateModel(
            name="PestTreatment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("treatment_date", models.DateField()),
                ("treatment_type", models.CharField(blank=True, max_length=100)),
                ("pest_target", models.CharField(blank=True, max_length=100)),
                ("chemical_name", models.CharField(blank=True, max_length=200)),
                ("safety_re_entry_hours", models.PositiveIntegerField(default=24)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_treatments",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments",
                        to="infrastructure.pestcontrolinspection",
                    ),
                ),
            ],
            options={
                "db_table": "pest_treatments",
            },
        ),
        migrations.CreateModel(
            name="RoomEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("projector", "Projector"),
                            ("whiteboard", "Whiteboard"),
                            ("computer", "Computer"),
                            ("ac", "Air Conditioning"),
                            ("smartboard", "Smart Board"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("asset_tag", models.CharField(blank=True, max_length=50)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("maintenance", "Under Maintenance"),
                            ("broken", "Broken"),
                        ],
                        default="working",
                        max_length=15,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="infrastructure.room",
                    ),
                ),
            ],
            options={
                "db_table": "room_equipment",
            },
        ),
        migrations.CreateModel(
            name="VendorPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("hvac", "HVAC"),
                            ("pest", "Pest Control"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("evaluation_date", models.DateField()),
                (
                    "quality_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "timeliness_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "value_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ],
                        default=3,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("would_rehire", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="infrastructure.vendorcontract",
                    ),
                ),
            ],
            options={
                "db_table": "vendor_performance_records",
            },
        ),
        migrations.CreateModel(
            name="WasteCollectionSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("general", "General Waste"),
                            ("recyclable", "Recyclable"),
                            ("organic", "Organic"),
                            ("hazardous", "Hazardous"),
                            ("e_waste", "Electronic Waste"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("collection_day", models.CharField(blank=True, max_length=10)),
                ("collection_time", models.TimeField(blank=True, null=True)),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_schedules",
                        to="infrastructure.building",
                    ),
                ),
            ],
            options={
                "db_table": "waste_collection_schedules",
            },
        ),
        migrations.CreateModel(
            name="EnergyReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reading_date", models.DateField()),
                ("reading_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("units", models.CharField(blank=True, max_length=20)),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="infrastructure.energymeter",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "energy_readings",
                "ordering": ["-reading_date"],
                "unique_together": {("meter", "reading_date")},
            },
        ),
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("floor_number", models.IntegerField(default=0)),
                ("floor_name", models.CharField(blank=True, max_length=100)),
                (
                    "plan_file",
                    models.FileField(upload_to="infrastructure/floor_plans/"),
                ),
                ("total_rooms", models.PositiveIntegerField(default=0)),
                (
                    "total_area_sqft",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_plans",
                        to="infrastructure.building",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "floor_plans",
                "unique_together": {("building", "floor_number")},
            },
        ),
        migrations.CreateModel(
            name="ParkingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("spot_number", models.CharField(max_length=20)),
                (
                    "spot_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("reserved", "Reserved"),
                            ("handicap", "Handicap"),
                            ("visitor", "Visitor"),
                        ],
                        default="regular",
                        max_length=10,
                    ),
                ),
                ("vehicle_plate", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parking_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="infrastructure.parkinglot",
                    ),
                ),
            ],
            options={
                "db_table": "parking_assignments",
                "unique_together": {("parking_lot", "spot_number")},
            },
        ),
        migrations.CreateModel(
            name="WaterUsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_date", models.DateField()),
                (
                    "usage_gallons",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("leak_detected", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_usage_records",
                        to="infrastructure.building",
                    ),
                ),
            ],
            options={
                "db_table": "water_usage_records",
                "unique_together": {("building", "record_date")},
            },
        ),
    ]
