# Generated by Django 5.1.15 on 2026-09-01 10:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
        ("cafeteria", "0002_allergenmanagement_freereducedlunch_and_more"),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CafeteriaAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("inventory", "Low Inventory"),
                            ("equipment", "Equipment Failure"),
                            ("safety", "Safety Issue"),
                            ("waste", "High Food Waste"),
                            ("budget", "Over Budget"),
                            ("staff", "Staff Shortage"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cafeteria_alert_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_alerts",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CafeteriaCapacity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seating_area", models.CharField(max_length=200)),
                ("total_seats", models.PositiveIntegerField(default=0)),
                ("available_seats", models.PositiveIntegerField(default=0)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time_slot_start", models.TimeField()),
                ("time_slot_end", models.TimeField()),
                ("is_full", models.BooleanField(default=False)),
                ("reservation_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_capacities",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_capacities",
            },
        ),
        migrations.CreateModel(
            name="CafeteriaEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("oven", "Oven"),
                            ("fridge", "Refrigerator"),
                            ("freezer", "Freezer"),
                            ("dishwasher", "Dishwasher"),
                            ("mixer", "Mixer"),
                            ("fryer", "Fryer"),
                            ("steamer", "Steamer"),
                            ("warmer", "Food Warmer"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("asset_tag", models.CharField(blank=True, max_length=50)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("maintenance", "Under Maintenance"),
                            ("broken", "Broken"),
                            ("retired", "Retired"),
                        ],
                        default="working",
                        max_length=15,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_equipment",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_equipment",
            },
        ),
        migrations.CreateModel(
            name="CafeteriaFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("food", "Food Quality"),
                            ("service", "Service"),
                            ("cleanliness", "Cleanliness"),
                            ("price", "Price/Value"),
                            ("wait", "Wait Time"),
                            ("general", "General"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Poor"),
                            (2, "Poor"),
                            (3, "Average"),
                            (4, "Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("date_of_experience", models.DateField(blank=True, null=True)),
                ("response", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meal_rated",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="cafeteria.mealmenu",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_feedbacks",
                        to="auth_service.school",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cafeteria_feedback_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cafeteria_feedbacks",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CafeteriaInventoryAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("expiring", "Expiring Soon"),
                            ("out_of_stock", "Out of Stock"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "current_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "reorder_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="cafeteria.cafeteriainventory",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_inventory_alerts",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_inventory_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CafeteriaReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reservation_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("meeting", "Meeting"),
                            ("celebration", "Celebration"),
                            ("lunch_meeting", "Lunch Meeting"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("reservation_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("expected_guests", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("menu_items", models.JSONField(blank=True, default=list)),
                ("special_requests", models.TextField(blank=True)),
                (
                    "estimated_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_reservations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_reservations",
                "ordering": ["-reservation_date"],
            },
        ),
        migrations.CreateModel(
            name="CashRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("register_name", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("is_open", models.BooleanField(default=False)),
                (
                    "opening_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closing_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "expected_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "variance",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registers_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_registers",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_cash_registers",
            },
        ),
        migrations.CreateModel(
            name="FoodSafetyCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperature Check"),
                            ("cleanliness", "Cleanliness"),
                            ("storage", "Storage Check"),
                            ("hygiene", "Personal Hygiene"),
                            ("equipment", "Equipment Check"),
                            ("waste", "Waste Management"),
                        ],
                        max_length=15,
                    ),
                ),
                ("check_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("conditional", "Conditional"),
                            ("pending", "Pending Review"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "temperature_reading",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("findings", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                ("compliance_notes", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="cafeteria/safety_checks/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_safety_checks",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_food_safety_checks",
                "ordering": ["-check_date"],
            },
        ),
        migrations.CreateModel(
            name="FoodSafetyIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="reported",
                        max_length=15,
                    ),
                ),
                ("people_affected", models.PositiveIntegerField(default=0)),
                ("root_cause", models.TextField(blank=True)),
                ("investigation_notes", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                ("preventive_measures", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("incident_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="food_safety_incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="food_safety_incidents_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_safety_incidents",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_food_safety_incidents",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.CreateModel(
            name="MealDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("delivery_date", models.DateField()),
                ("delivery_time", models.TimeField()),
                ("delivery_location", models.CharField(max_length=200)),
                ("class_group", models.CharField(blank=True, max_length=50)),
                ("meals_ordered", models.PositiveIntegerField(default=0)),
                ("meals_delivered", models.PositiveIntegerField(default=0)),
                ("meals_returned", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_deliveries",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_meal_deliveries",
                "ordering": ["-delivery_date"],
            },
        ),
        migrations.CreateModel(
            name="MealPreOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meal_date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("menu_items", models.JSONField(default=list)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("collected", "Collected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("paid_via", models.CharField(blank=True, max_length=20)),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("pickup_location", models.CharField(blank=True, max_length=200)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_pre_orders",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_pre_orders",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_meal_pre_orders",
                "ordering": ["-meal_date"],
            },
        ),
        migrations.CreateModel(
            name="MealSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "meals_included",
                    models.JSONField(default=list, help_text="Which meals are included"),
                ),
                ("meals_per_week", models.PositiveIntegerField(default=5)),
                ("price_per_meal", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=20)),
                ("auto_renew", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_subscriptions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_subscriptions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_meal_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="MenuItemRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(help_text="1-5 stars")),
                ("review", models.TextField(blank=True)),
                ("would_order_again", models.BooleanField(blank=True, null=True)),
                ("date_rated", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_ratings",
                        to="cafeteria.mealmenu",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_menu_item_ratings",
            },
        ),
        migrations.CreateModel(
            name="NutritionAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("calories", models.PositiveIntegerField(default=0)),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "carbohydrates_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fiber_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sugar_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "vitamin_a",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "vitamin_c",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "calcium",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "iron",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "health_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=5,
                        help_text="1-10 scale",
                        max_digits=3,
                    ),
                ),
                ("is_healthy_choice", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analyzed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_analysis",
                        to="cafeteria.mealmenu",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_nutrition_analysis",
            },
        ),
        migrations.CreateModel(
            name="OnlineOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready for Pickup"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "items",
                    models.JSONField(default=list, help_text="List of ordered items"),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("delivery_location", models.CharField(blank=True, max_length=200)),
                ("delivery_required", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                ("payment_method", models.CharField(blank=True, max_length=20)),
                ("special_instructions", models.TextField(blank=True)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_orders",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_orders",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_online_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("special_requests", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cafeteria.mealmenu",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="cafeteria.onlineorder",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_online_order_items",
            },
        ),
        migrations.CreateModel(
            name="CafeteriaAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_visitors", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                (
                    "avg_wait_time_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("peak_hour", models.TimeField(blank=True, null=True)),
                ("total_meals_served", models.PositiveIntegerField(default=0)),
                ("meals_by_type", models.JSONField(blank=True, default=dict)),
                ("top_items", models.JSONField(blank=True, default=list)),
                ("least_popular", models.JSONField(blank=True, default=list)),
                (
                    "total_waste_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "waste_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_analytics",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_analytics",
                "ordering": ["-date"],
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="CafeteriaHolidaySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("is_closed", models.BooleanField(default=True)),
                ("special_hours", models.BooleanField(default=False)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_holiday_schedules",
                        to="auth_service.school",
                    ),
                ),
                (
                    "special_menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cafeteria.mealmenu",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_holiday_schedules",
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="CafeteriaMonthlyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_meals_served", models.PositiveIntegerField(default=0)),
                ("total_operational_days", models.PositiveIntegerField(default=0)),
                (
                    "avg_food_rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("total_complaints", models.PositiveIntegerField(default=0)),
                ("complaints_resolved", models.PositiveIntegerField(default=0)),
                (
                    "total_waste_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("highlights", models.TextField(blank=True)),
                ("improvements_needed", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_monthly_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_monthly_reports",
                "unique_together": {("school", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="CafeteriaStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("cook", "Cook"),
                            ("assistant", "Assistant"),
                            ("cashier", "Cashier"),
                            ("manager", "Manager"),
                            ("cleaner", "Cleaner"),
                            ("delivery", "Delivery"),
                            ("supervisor", "Supervisor"),
                        ],
                        max_length=15,
                    ),
                ),
                ("shift_start", models.TimeField(blank=True, null=True)),
                ("shift_end", models.TimeField(blank=True, null=True)),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_certified", models.BooleanField(default=False)),
                ("certification_expiry", models.DateField(blank=True, null=True)),
                (
                    "performance_rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_staff",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafeteria_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_staff",
                "unique_together": {("school", "user", "role")},
            },
        ),
        migrations.CreateModel(
            name="DailySalesSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                ("total_items_sold", models.PositiveIntegerField(default=0)),
                (
                    "avg_transaction_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cash_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "card_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "account_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "free_meal_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "breakfast_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lunch_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "snack_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "dinner_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("top_items", models.JSONField(blank=True, default=list)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_sales_summaries",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_daily_sales_summaries",
                "ordering": ["-date"],
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meal_date", models.DateField()),
                ("meal_type", models.CharField(max_length=10)),
                ("used", models.BooleanField(default=True)),
                ("skipped", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cafeteria.mealmenu",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="cafeteria.mealsubscription",
                    ),
                ),
            ],
            options={
                "db_table": "cafeteria_subscription_usage",
                "unique_together": {("subscription", "meal_date", "meal_type")},
            },
        ),
    ]
