# Generated by Django 4.2.13 on 2026-07-15 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("graduation_year", models.PositiveSmallIntegerField()),
                ("student_id", models.CharField(blank=True, max_length=30)),
                ("occupation", models.CharField(blank=True, max_length=150)),
                ("employer", models.CharField(blank=True, max_length=150)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-Employed"),
                            ("student", "Further Studies"),
                            ("unemployed", "Unemployed"),
                            ("retired", "Retired"),
                        ],
                        default="employed",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("linkedin_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("is_newsletter_subscribed", models.BooleanField(default=True)),
                ("is_visible_to_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_profiles",
                        to="auth_service.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alumni_profiles",
                "ordering": ["-graduation_year", "user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="AlumniEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("max_attendees", models.PositiveSmallIntegerField(default=0)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_alumni_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_events",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="AlumniDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "fund_type",
                    models.CharField(
                        choices=[
                            ("general", "General Fund"),
                            ("scholarship", "Scholarship Fund"),
                            ("infrastructure", "Infrastructure"),
                            ("sports", "Sports Fund"),
                            ("library", "Library Fund"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online Payment"),
                            ("other", "Other"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("donation_date", models.DateField(auto_now_add=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("is_recurring", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_donations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_donations",
                "ordering": ["-donation_date"],
            },
        ),
        migrations.CreateModel(
            name="AlumniChapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "president",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presided_chapters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_chapters",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_chapters",
                "ordering": ["name"],
                "unique_together": {("school", "name")},
            },
        ),
    ]
