# Generated by Django 5.1.15 on 2026-08-31 08:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0002_alumnidonation_recurring_frequency_and_more"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniprofile",
            name="interests",
            field=models.JSONField(blank=True, default=list, help_text="List of interests"),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="skills",
            field=models.JSONField(blank=True, default=list, help_text="List of skills"),
        ),
        migrations.CreateModel(
            name="AlumniBadge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("milestone", "Milestone"),
                            ("donation", "Donation"),
                            ("engagement", "Engagement"),
                            ("mentorship", "Mentorship"),
                            ("event", "Event Attendance"),
                            ("volunteer", "Volunteering"),
                            ("referral", "Referral"),
                            ("special", "Special Recognition"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(blank=True, help_text="Badge icon image URL"),
                ),
                (
                    "color",
                    models.CharField(default="#007bff", help_text="Hex color code", max_length=7),
                ),
                (
                    "criteria_description",
                    models.TextField(blank=True, help_text="How to earn this badge"),
                ),
                (
                    "criteria_value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Threshold value (e.g., donate $100)",
                        null=True,
                    ),
                ),
                ("total_awarded", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_badges",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_badges",
                "ordering": ["badge_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="AlumniCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("general", "General Fund"),
                            ("scholarship", "Scholarship"),
                            ("infrastructure", "Infrastructure"),
                            ("emergency", "Emergency Fund"),
                            ("annual", "Annual Fund"),
                            ("class_gift", "Class Gift"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("donor_count", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "has_matching",
                    models.BooleanField(default=False, help_text="Enable matching gifts"),
                ),
                (
                    "matching_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="e.g., 2.0 = 2x match",
                        max_digits=5,
                    ),
                ),
                ("matching_deadline", models.DateField(blank=True, null=True)),
                ("cover_image_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("is_anonymous_allowed", models.BooleanField(default=True)),
                ("is_recurring_allowed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_campaigns",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("interest", "Interest Group"),
                            ("batch", "Batch/Class"),
                            ("sports", "Sports Team"),
                            ("club", "Club"),
                            ("industry", "Industry Network"),
                            ("regional", "Regional Group"),
                            ("other", "Other"),
                        ],
                        default="interest",
                        max_length=20,
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, help_text="Require approval to join"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_members",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited"),
                ),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("cover_image_url", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_groups",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_groups",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_groups",
                "ordering": ["name"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="AlumniGroupPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("attachment_url", models.URLField(blank=True)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_posts",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="alumni.alumnigroup",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_group_posts",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniNewsletter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                (
                    "content",
                    models.TextField(help_text="HTML content of the newsletter"),
                ),
                (
                    "plain_text",
                    models.TextField(blank=True, help_text="Plain text version"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_graduation_years",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Target specific graduation years",
                    ),
                ),
                (
                    "target_cities",
                    models.JSONField(blank=True, default=list, help_text="Target specific cities"),
                ),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_opened", models.PositiveIntegerField(default=0)),
                ("total_clicked", models.PositiveIntegerField(default=0)),
                ("total_bounced", models.PositiveIntegerField(default=0)),
                ("total_unsubscribed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_newsletters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_newsletters",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_newsletters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniPoll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "poll_type",
                    models.CharField(
                        choices=[
                            ("poll", "Poll"),
                            ("survey", "Survey"),
                            ("feedback", "Feedback"),
                            ("election", "Election"),
                        ],
                        default="poll",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("allow_multiple_answers", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_polls",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_polls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniPollOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="alumni.alumnipoll",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_poll_options",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AlumniReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("referred_name", models.CharField(max_length=150)),
                ("referred_email", models.EmailField(max_length=254)),
                ("referred_phone", models.CharField(blank=True, max_length=20)),
                (
                    "referral_type",
                    models.CharField(
                        choices=[
                            ("admission", "Admission Referral"),
                            ("job", "Job Referral"),
                            ("event", "Event Referral"),
                            ("other", "Other"),
                        ],
                        default="admission",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("referred_at", models.DateTimeField(auto_now_add=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("reward_points", models.PositiveIntegerField(default=0)),
                ("reward_description", models.CharField(blank=True, max_length=200)),
                (
                    "job_posting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="alumni.alumnijobposting",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_referrals",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_referrals",
                "ordering": ["-referred_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniSuccessStory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "story_type",
                    models.CharField(
                        choices=[
                            ("career", "Career Achievement"),
                            ("entrepreneurship", "Entrepreneurship"),
                            ("social_impact", "Social Impact"),
                            ("academic", "Academic Excellence"),
                            ("sports", "Sports Achievement"),
                            ("arts", "Arts & Culture"),
                            ("other", "Other"),
                        ],
                        default="career",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_stories",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_success_stories",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_success_stories",
                "ordering": ["-featured", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("degree", "Degree Certificate"),
                            ("student_id", "Student ID"),
                            ("admin_approval", "Admin Approval"),
                            ("email_verification", "Email Verification"),
                            ("manual", "Manual Review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "document_url",
                    models.URLField(blank=True, help_text="URL to uploaded verification document"),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="Verification expiry date", null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_alumni",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alumni_verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniVolunteer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("skills_required", models.JSONField(blank=True, default=list)),
                ("max_volunteers", models.PositiveIntegerField(default=0)),
                ("current_volunteers", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "time_commitment",
                    models.CharField(
                        choices=[
                            ("one_time", "One-time"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("flexible", "Flexible"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                ("estimated_hours", models.PositiveIntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("full", "Full"),
                            ("closed", "Closed"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_volunteer_opps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_volunteer_opportunities",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_volunteer_opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniActivityFeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("profile_update", "Profile Updated"),
                            ("event_registered", "Event Registration"),
                            ("event_attended", "Event Attendance"),
                            ("donation_made", "Donation Made"),
                            ("badge_earned", "Badge Earned"),
                            ("mentorship_started", "Mentorship Started"),
                            ("job_posted", "Job Posted"),
                            ("discussion_created", "Discussion Created"),
                            ("chapter_joined", "Chapter Joined"),
                            ("volunteered", "Volunteered"),
                            ("referral_made", "Referral Made"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "reference_id",
                    models.UUIDField(blank=True, help_text="ID of related object", null=True),
                ),
                (
                    "reference_model",
                    models.CharField(
                        blank=True,
                        help_text="Model name of related object",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, help_text="Additional activity data"),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_feed",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_activity_feed",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["alumni", "created_at"],
                        name="alumni_acti_alumni__cbd4d2_idx",
                    ),
                    models.Index(fields=["activity_type"], name="alumni_acti_activit_c5d1e4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlumniBadgeAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for awarding this badge"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, help_text="Show on public profile"),
                ),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="alumni.alumnibadge",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_badge_awards",
                "ordering": ["-awarded_at"],
                "unique_together": {("badge", "alumni")},
            },
        ),
        migrations.CreateModel(
            name="AlumniCampaignDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_matching",
                    models.BooleanField(default=False, help_text="Is this a matching donation?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="alumni.alumnicampaign",
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_links",
                        to="alumni.alumnidonation",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_campaign_donations",
                "ordering": ["-created_at"],
                "unique_together": {("campaign", "donation")},
            },
        ),
        migrations.CreateModel(
            name="AlumniGroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("banned", "Banned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_muted",
                    models.BooleanField(default=False, help_text="Mute notifications from this group"),
                ),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="alumni.alumnigroup",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_group_members",
                "ordering": ["role", "-joined_at"],
                "unique_together": {("group", "alumni")},
            },
        ),
        migrations.CreateModel(
            name="AlumniPollResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text_response",
                    models.TextField(blank=True, help_text="For open-ended questions"),
                ),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_responses",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="alumni.alumnipolloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="alumni.alumnipoll",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_poll_responses",
                "ordering": ["-responded_at"],
                "unique_together": {("poll", "alumni", "option")},
            },
        ),
        migrations.CreateModel(
            name="AlumniVolunteerSignup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("hours_logged", models.PositiveIntegerField(default=0)),
                ("feedback", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(blank=True, help_text="1-5 rating", null=True),
                ),
                ("signed_up_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_signups",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="alumni.alumnivolunteer",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_volunteer_signups",
                "ordering": ["-signed_up_at"],
                "unique_together": {("opportunity", "alumni")},
            },
        ),
    ]
