# Generated by Django 5.1.15 on 2026-08-31 09:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0003_alumniprofile_interests_alumniprofile_skills_and_more"),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniAwardCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("icon_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_award_categories",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_award_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlumniAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nominations_open", "Nominations Open"),
                            ("nominations_closed", "Nominations Closed"),
                            ("judging", "Judging"),
                            ("winners_announced", "Winners Announced"),
                            ("completed", "Completed"),
                        ],
                        default="nominations_open",
                        max_length=20,
                    ),
                ),
                ("nominations_start", models.DateField()),
                ("nominations_end", models.DateField()),
                ("judging_end", models.DateField(blank=True, null=True)),
                ("announcement_date", models.DateField(blank=True, null=True)),
                ("ceremony_date", models.DateField(blank=True, null=True)),
                (
                    "max_nominations_per_person",
                    models.PositiveSmallIntegerField(default=3),
                ),
                ("requires_nomination_statement", models.BooleanField(default=True)),
                ("total_nominations", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_awards",
                        to="auth_service.school",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="alumni.alumniawardcategory",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_awards",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniCalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reunion", "Reunion"),
                            ("networking", "Networking"),
                            ("gala", "Gala"),
                            ("workshop", "Workshop"),
                            ("webinar", "Webinar"),
                            ("sports", "Sports"),
                            ("cultural", "Cultural"),
                            ("career", "Career"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("recurrence_end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("is_virtual", models.BooleanField(default=False)),
                ("virtual_link", models.URLField(blank=True)),
                ("ical_uid", models.CharField(blank=True, max_length=100, unique=True)),
                ("google_event_id", models.CharField(blank=True, max_length=100)),
                ("max_attendees", models.PositiveIntegerField(default=0)),
                ("requires_registration", models.BooleanField(default=False)),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organized_calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_calendar_events",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_calendar_events",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="AlumniDirectMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("link", "Link"),
                            ("system", "System"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("attachment_url", models.URLField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted_by_sender", models.BooleanField(default=False)),
                ("is_deleted_by_receiver", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_direct_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived_by_p1", models.BooleanField(default=False)),
                ("is_archived_by_p2", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_p1",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "participant2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_p2",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "last_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="alumni.alumnidirectmessage",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_conversations",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniDirectoryFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "graduation_year_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "graduation_year_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cities", models.JSONField(blank=True, default=list)),
                ("countries", models.JSONField(blank=True, default=list)),
                ("industries", models.JSONField(blank=True, default=list)),
                ("companies", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("employment_status", models.JSONField(blank=True, default=list)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_directory_filters",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlumniDonationRecurring",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fund_type",
                    models.CharField(
                        choices=[
                            ("general", "General Fund"),
                            ("scholarship", "Scholarship Fund"),
                            ("infrastructure", "Infrastructure"),
                            ("sports", "Sports Fund"),
                            ("library", "Library Fund"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("next_payment_date", models.DateField(blank=True, null=True)),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online Payment"),
                            ("other", "Other"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "payment_token",
                    models.CharField(blank=True, help_text="Payment processor token", max_length=200),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_payments", models.PositiveIntegerField(default=0)),
                ("failed_payments", models.PositiveIntegerField(default=0)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_donations",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_donation_recurring",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniEmailCampaignAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                            ("spam_report", "Spam Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("link_url", models.URLField(blank=True, help_text="Clicked link URL")),
                ("bounce_reason", models.CharField(blank=True, max_length=200)),
                ("event_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_analytics",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_events",
                        to="alumni.alumninewsletter",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_email_campaign_analytics",
                "ordering": ["-event_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniPhotoAlbum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("cover_photo_url", models.URLField(blank=True)),
                ("photo_count", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_albums",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_albums",
                        to="alumni.alumnievent",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_photo_albums",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_photo_albums",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("photo_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                ("caption", models.CharField(blank=True, max_length=300)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_photos",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="alumni.alumniphotoalbum",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_photos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniPhotoComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_comments",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="alumni.alumniphoto",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_photo_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniPodcastEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "episode_type",
                    models.CharField(
                        choices=[
                            ("interview", "Interview"),
                            ("panel", "Panel Discussion"),
                            ("solo", "Solo"),
                            ("q_and_a", "Q&A"),
                            ("other", "Other"),
                        ],
                        default="interview",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("audio_url", models.URLField(help_text="Podcast audio URL")),
                ("thumbnail_url", models.URLField(blank=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                ("season_number", models.PositiveIntegerField(default=1)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guest_podcasts",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_podcasts",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_podcasts",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_podcast_episodes",
                "ordering": ["-season_number", "-episode_number"],
            },
        ),
        migrations.CreateModel(
            name="AlumniPodcastSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_subscriptions",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_podcast_subscriptions",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniProfileCompleteness",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("has_photo", models.BooleanField(default=False)),
                ("has_bio", models.BooleanField(default=False)),
                ("has_occupation", models.BooleanField(default=False)),
                ("has_employer", models.BooleanField(default=False)),
                ("has_phone", models.BooleanField(default=False)),
                ("has_address", models.BooleanField(default=False)),
                ("has_linkedin", models.BooleanField(default=False)),
                ("has_skills", models.BooleanField(default=False)),
                ("has_interests", models.BooleanField(default=False)),
                ("has_graduation_year", models.BooleanField(default=False)),
                ("completion_percentage", models.PositiveSmallIntegerField(default=0)),
                ("last_calculated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumni",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completeness",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_profile_completeness",
            },
        ),
        migrations.CreateModel(
            name="AlumniProfileView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "viewed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views_received",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_views_made",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_profile_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniVideoGallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("event_recording", "Event Recording"),
                            ("testimonial", "Testimonial"),
                            ("interview", "Interview"),
                            ("tutorial", "Tutorial"),
                            ("highlights", "Highlights"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(help_text="YouTube, Vimeo, or direct URL"),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="alumni.alumnievent",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_videos",
                        to="auth_service.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_videos",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_videos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AlumniAwardNomination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "statement",
                    models.TextField(help_text="Why this person deserves this award"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("winner", "Winner"),
                            ("runner_up", "Runner Up"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Links to supporting evidence",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("judge_notes", models.TextField(blank=True)),
                ("nominated_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="alumni.alumniaward",
                    ),
                ),
                (
                    "nominated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award_nominations_made",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award_nominations_received",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_award_nominations",
                "ordering": ["-nominated_at"],
                "unique_together": {("award", "nominee", "nominated_by")},
            },
        ),
        migrations.CreateModel(
            name="AlumniCalendarRSVP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("tentative", "Tentative"),
                            ("declined", "Declined"),
                        ],
                        default="accepted",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_rsvps",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_rsvps",
                        to="alumni.alumnicalendarevent",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_calendar_rsvps",
                "ordering": ["-responded_at"],
                "unique_together": {("event", "alumni")},
            },
        ),
        migrations.AddIndex(
            model_name="alumnidirectmessage",
            index=models.Index(fields=["sender", "receiver"], name="alumni_dire_sender__a8c049_idx"),
        ),
        migrations.AddIndex(
            model_name="alumnidirectmessage",
            index=models.Index(fields=["created_at"], name="alumni_dire_created_b51f63_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="alumniconversation",
            unique_together={("participant1", "participant2")},
        ),
        migrations.AddIndex(
            model_name="alumniemailcampaignanalytics",
            index=models.Index(
                fields=["newsletter", "event_type"],
                name="alumni_emai_newslet_6b2897_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alumniemailcampaignanalytics",
            index=models.Index(fields=["alumni", "event_type"], name="alumni_emai_alumni__e96893_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="alumnipodcastsubscription",
            unique_together={("alumni",)},
        ),
        migrations.AddIndex(
            model_name="alumniprofileview",
            index=models.Index(fields=["viewer", "viewed"], name="alumni_prof_viewer__9847e3_idx"),
        ),
        migrations.AddIndex(
            model_name="alumniprofileview",
            index=models.Index(fields=["viewed", "viewed_at"], name="alumni_prof_viewed__6e6738_idx"),
        ),
    ]
