# Generated by Django 5.1.15 on 2026-08-31 14:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("health_clinic", "0001_initial"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllergyManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allergen_name", models.CharField(max_length=100)),
                (
                    "allergy_type",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("medication", "Medication"),
                            ("environmental", "Environmental"),
                            ("insect", "Insect"),
                            ("latex", "Latex"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("life_threatening", "Life-Threatening"),
                        ],
                        max_length=20,
                    ),
                ),
                ("symptoms", models.TextField(blank=True, help_text="Common symptoms")),
                ("reaction_description", models.TextField(blank=True)),
                (
                    "treatment_protocol",
                    models.TextField(blank=True, help_text="What to do in case of reaction"),
                ),
                (
                    "emergency_medication",
                    models.CharField(blank=True, help_text="e.g., EpiPen", max_length=100),
                ),
                (
                    "medication_location",
                    models.CharField(
                        blank=True,
                        help_text="Where emergency med is stored",
                        max_length=100,
                    ),
                ),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("diagnosed_by", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergy_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergy_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "allergy_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChronicConditionTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("diabetes", "Diabetes"),
                            ("asthma", "Asthma"),
                            ("epilepsy", "Epilepsy"),
                            ("allergies", "Severe Allergies"),
                            ("heart", "Heart Condition"),
                            ("sickle_cell", "Sickle Cell Disease"),
                            ("cystic_fibrosis", "Cystic Fibrosis"),
                            ("autism", "Autism Spectrum"),
                            ("adhd", "ADHD"),
                            ("other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("condition_name", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        max_length=15,
                    ),
                ),
                ("diagnosed_date", models.DateField(blank=True, null=True)),
                ("diagnosed_by", models.CharField(blank=True, max_length=150)),
                (
                    "management_plan",
                    models.TextField(help_text="How to manage the condition at school"),
                ),
                (
                    "medication_schedule",
                    models.TextField(blank=True, help_text="When and what medications to give"),
                ),
                ("dietary_restrictions", models.TextField(blank=True)),
                ("activity_restrictions", models.TextField(blank=True)),
                (
                    "emergency_protocol",
                    models.TextField(blank=True, help_text="What to do in emergency"),
                ),
                ("emergency_medication", models.CharField(blank=True, max_length=100)),
                (
                    "emergency_med_location",
                    models.CharField(blank=True, max_length=100),
                ),
                ("specialist_name", models.CharField(blank=True, max_length=150)),
                ("specialist_phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("last_review_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chronic_conditions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chronic_conditions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "chronic_conditions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_name", models.CharField(max_length=150)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("guardian", "Guardian"),
                            ("grandparent", "Grandparent"),
                            ("sibling", "Sibling"),
                            ("other_family", "Other Family"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_primary", models.CharField(max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "can_pickup",
                    models.BooleanField(default=False, help_text="Authorized for pickup?"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "emergency_contacts",
                "ordering": ["-is_primary", "contact_name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical Emergency"),
                            ("allergic", "Allergic Reaction"),
                            ("seizure", "Seizure Protocol"),
                            ("diabetic", "Diabetic Emergency"),
                            ("asthma", "Asthma Attack"),
                            ("injury", "Injury Protocol"),
                            ("mental_health", "Mental Health Crisis"),
                            ("general", "General Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("under_review", "Under Review"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("procedures", models.TextField(help_text="Step-by-step procedures")),
                (
                    "responsible_staff",
                    models.JSONField(default=list, help_text="List of staff responsible"),
                ),
                (
                    "contact_numbers",
                    models.JSONField(default=dict, help_text="Emergency contact numbers"),
                ),
                (
                    "required_equipment",
                    models.TextField(blank=True, help_text="Equipment needed"),
                ),
                ("equipment_location", models.CharField(blank=True, max_length=200)),
                ("last_training_date", models.DateField(blank=True, null=True)),
                ("training_notes", models.TextField(blank=True)),
                ("effective_date", models.DateField()),
                ("review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_plans",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "emergency_plans",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("epi_pen", "EpiPen Required"),
                            ("inhaler", "Asthma Inhaler Required"),
                            ("diabetic", "Diabetic Kit Required"),
                            ("seizure", "Seizure Medication Required"),
                            ("allergy", "Severe Allergy"),
                            ("other", "Other Critical Health Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[("immediate", "Immediate Action Required")],
                        default="immediate",
                        max_length=15,
                    ),
                ),
                ("alert_message", models.TextField()),
                ("emergency_instructions", models.TextField()),
                ("medication_name", models.CharField(max_length=100)),
                ("medication_location", models.CharField(max_length=200)),
                ("emergency_contact_name", models.CharField(max_length=150)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_alerts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_alerts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCompliance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "compliance_type",
                    models.CharField(
                        choices=[
                            ("immunization", "Immunization Compliance"),
                            ("physical", "Physical Examination"),
                            ("dental", "Dental Examination"),
                            ("tb", "TB Test"),
                            ("vision", "Vision Test"),
                            ("hearing", "Hearing Test"),
                            ("form", "Health Form"),
                            ("med_auth", "Medication Authorization"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("pending", "Pending"),
                            ("exempted", "Exempted"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "requirement",
                    models.CharField(help_text="Specific requirement description", max_length=200),
                ),
                ("notes", models.TextField(blank=True)),
                ("document_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_compliance",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_compliance",
                        to="students.student",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_compliance",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthEducation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("video", "Video"),
                            ("link", "External Link"),
                            ("handout", "Handout"),
                            ("presentation", "Presentation"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "topic_category",
                    models.CharField(
                        choices=[
                            ("nutrition", "Nutrition"),
                            ("hygiene", "Personal Hygiene"),
                            ("mental_health", "Mental Health"),
                            ("substance", "Substance Abuse Prevention"),
                            ("sex_ed", "Sex Education"),
                            ("first_aid", "First Aid"),
                            ("exercise", "Physical Activity"),
                            ("sleep", "Sleep Health"),
                            ("general", "General Health"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("content_url", models.URLField(blank=True)),
                ("file_url", models.URLField(blank=True)),
                ("content_text", models.TextField(blank=True)),
                (
                    "target_grades",
                    models.JSONField(default=list, help_text="List of grade levels"),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_education",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "health_education",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("health_history", "Health History Form"),
                            ("immunization_record", "Immunization Record"),
                            ("medication_auth", "Medication Authorization"),
                            ("allergy_plan", "Allergy Action Plan"),
                            ("asthma_plan", "Asthma Action Plan"),
                            ("diabetes_mgmt", "Diabetes Management Plan"),
                            ("emergency_contact", "Emergency Contact Form"),
                            ("physical_exam", "Physical Examination Form"),
                            ("consent", "Consent Form"),
                            ("waiver", "Liability Waiver"),
                            ("other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "form_fields",
                    models.JSONField(default=dict, help_text="JSON schema for form fields"),
                ),
                ("instructions", models.TextField(blank=True)),
                (
                    "is_required",
                    models.BooleanField(default=False, help_text="Required for enrollment?"),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_forms",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "health_forms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthFormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(default=dict, help_text="Submitted form field values"),
                ),
                (
                    "attachments",
                    models.JSONField(default=list, help_text="List of attachment URLs"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "signature_data",
                    models.TextField(blank=True, help_text="Digital signature data"),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="health_clinic.healthform",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_health_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_form_submissions",
                        to="students.student",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_form_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("immunization", "Immunization Status Report"),
                            ("clinic", "Clinic Usage Report"),
                            ("medication", "Medication Usage Report"),
                            ("allergy", "Allergy Summary"),
                            ("incident", "Incident Summary"),
                            ("screening", "Screening Results Report"),
                            ("compliance", "Compliance Status Report"),
                            ("chronic", "Chronic Conditions Report"),
                            ("general", "General Health Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.TextField(blank=True)),
                ("findings", models.JSONField(default=dict)),
                ("recommendations", models.TextField(blank=True)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_visits", models.PositiveIntegerField(default=0)),
                ("total_incidents", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "health_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthScreening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "screening_type",
                    models.CharField(
                        choices=[
                            ("vision", "Vision Screening"),
                            ("hearing", "Hearing Screening"),
                            ("scoliosis", "Scoliosis Screening"),
                            ("bmi", "BMI Screening"),
                            ("dental", "Dental Screening"),
                            ("bp", "Blood Pressure Screening"),
                            ("tb", "Tuberculosis Test"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("screening_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("referred", "Referred"),
                            ("follow_up", "Follow-up Needed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("result_summary", models.TextField(blank=True)),
                ("is_normal", models.BooleanField(blank=True, null=True)),
                ("referral_needed", models.BooleanField(default=False)),
                ("referral_notes", models.TextField(blank=True)),
                ("referred_to", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_screenings",
                        to="auth_service.school",
                    ),
                ),
                (
                    "screened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_screenings",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_screenings",
                "ordering": ["-screening_date"],
            },
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("injury", "Injury"),
                            ("illness", "Illness"),
                            ("allergy", "Allergic Reaction"),
                            ("seizure", "Seizure"),
                            ("fainting", "Fainting"),
                            ("breathing", "Breathing Difficulty"),
                            ("headache", "Severe Headache"),
                            ("blood", "Blood/Bodily Fluid"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("incident_date", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("none", "No Action Needed"),
                            ("first_aid", "First Aid Given"),
                            ("medication", "Medication Given"),
                            ("referral", "Referred to Hospital"),
                            ("ems", "EMS Called"),
                            ("parent", "Parent Contacted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action_details", models.TextField(blank=True)),
                (
                    "witnessed_by",
                    models.JSONField(default=list, help_text="List of witnesses"),
                ),
                ("parent_notified", models.BooleanField(default=False)),
                ("parent_notified_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("treatment_given", models.TextField(blank=True)),
                ("hospital_name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "incident_reports",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalReferral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "referral_reason",
                    models.CharField(
                        choices=[
                            ("specialist", "Specialist Consultation"),
                            ("hospital", "Hospital Referral"),
                            ("testing", "Medical Testing"),
                            ("treatment", "Treatment Follow-up"),
                            ("emergency", "Emergency Care"),
                            ("mental_health", "Mental Health Service"),
                            ("dental", "Dental Care"),
                            ("vision", "Vision Care"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("provider_name", models.CharField(max_length=150)),
                ("provider_phone", models.CharField(blank=True, max_length=20)),
                ("provider_address", models.TextField(blank=True)),
                ("reason_for_referral", models.TextField()),
                ("urgency", models.CharField(blank=True, max_length=20)),
                ("referral_date", models.DateField()),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_referrals",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_referrals",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "medical_referrals",
                "ordering": ["-referral_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicationInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medication_name", models.CharField(max_length=100)),
                ("generic_name", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pain", "Pain Relievers"),
                            ("antihistamine", "Antihistamines"),
                            ("respiratory", "Respiratory"),
                            ("gastro", "Gastrointestinal"),
                            ("topical", "Topical"),
                            ("emergency", "Emergency Medications"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_on_hand", models.PositiveIntegerField(default=0)),
                ("unit_of_measure", models.CharField(default="tablets", max_length=20)),
                ("reorder_threshold", models.PositiveIntegerField(default=10)),
                ("storage_location", models.CharField(max_length=100)),
                ("requires_refrigeration", models.BooleanField(default=False)),
                ("expiration_date", models.DateField()),
                ("lot_number", models.CharField(blank=True, max_length=50)),
                ("supplier", models.CharField(blank=True, max_length=100)),
                ("last_reorder_date", models.DateField(blank=True, null=True)),
                ("is_controlled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_inventory",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "medication_inventory",
                "ordering": ["medication_name"],
            },
        ),
        migrations.CreateModel(
            name="MedicationPrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medication_name", models.CharField(max_length=100)),
                ("dosage", models.CharField(max_length=50)),
                ("frequency", models.CharField(max_length=50)),
                ("route", models.CharField(blank=True, max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("times_per_day", models.PositiveSmallIntegerField(default=1)),
                (
                    "administration_times",
                    models.JSONField(default=list, help_text='List of times e.g., ["08:00", "12:00"]'),
                ),
                ("prescribed_by", models.CharField(max_length=150)),
                ("prescriber_phone", models.CharField(blank=True, max_length=20)),
                ("parent_consent", models.BooleanField(default=False)),
                ("consent_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_prescriptions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_prescriptions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "medication_prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NurseSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning Shift"),
                            ("afternoon", "Afternoon Shift"),
                            ("full_day", "Full Day"),
                            ("on_call", "On Call"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_available", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_recurring", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_schedule",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "nurse_schedule",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ParentNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("medication", "Medication Given"),
                            ("clinic", "Clinic Visit"),
                            ("fever", "Fever Detected"),
                            ("injury", "Injury Reported"),
                            ("illness", "Illness Detected"),
                            ("allergy", "Allergy Reaction"),
                            ("screening", "Health Screening Results"),
                            ("immunization", "Immunization Due"),
                            ("form", "Health Form Due"),
                            ("emergency", "Emergency"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medication_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="health_clinic.medicationlog",
                    ),
                ),
                (
                    "nurse_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="health_clinic.nursevisit",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_notifications",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_notifications",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.CharField(max_length=100)),
                ("normal_range", models.CharField(blank=True, max_length=100)),
                ("is_abnormal", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "screening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="health_clinic.healthscreening",
                    ),
                ),
            ],
            options={
                "db_table": "screening_results",
            },
        ),
        migrations.CreateModel(
            name="TelehealthSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("consultation", "General Consultation"),
                            ("follow_up", "Follow-up"),
                            ("mental_health", "Mental Health"),
                            ("specialist", "Specialist Consultation"),
                            ("emergency", "Emergency"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("meeting_link", models.URLField(blank=True)),
                ("meeting_id", models.CharField(blank=True, max_length=100)),
                ("meeting_password", models.CharField(blank=True, max_length=50)),
                ("parent_present", models.BooleanField(default=False)),
                ("nurse_present", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "healthcare_provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="telehealth_provided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telehealth_sessions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telehealth_sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "telehealth_sessions",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
    ]
