# Generated by Django 5.1.15 on 2026-09-01 08:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0006_add_auth_gap_models"),
        ("health_clinic", "0002_add_health_clinic_gaps"),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DentalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visit_date", models.DateField()),
                ("dentist_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("follow_up", "Follow-up Needed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("examination_findings", models.TextField(blank=True)),
                ("cavities_count", models.PositiveSmallIntegerField(default=0)),
                ("gum_health", models.CharField(blank=True, max_length=50)),
                ("treatment_provided", models.TextField(blank=True)),
                ("prescriptions", models.TextField(blank=True)),
                ("next_checkup_date", models.DateField(blank=True, null=True)),
                ("xray_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_dental_records",
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMedicalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("sibling", "Sibling"),
                            ("grandparent", "Grandparent"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_name", models.CharField(max_length=200)),
                (
                    "age_at_diagnosis",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_hereditary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_medical_history_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_medical_history_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_family_medical_history",
                "ordering": ["relationship", "condition_name"],
            },
        ),
        migrations.CreateModel(
            name="GrowthChart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recorded_date", models.DateField()),
                (
                    "height_cm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "weight_kg",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "bmi",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "head_circumference_cm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_charts",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growth_charts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_growth_charts",
                "ordering": ["-recorded_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Physical"),
                            ("sports", "Sports Physical"),
                            ("pre_enrollment", "Pre-Enrollment"),
                            ("follow_up", "Follow-up"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assessment_date", models.DateField()),
                ("general_health", models.CharField(blank=True, max_length=50)),
                ("immunizations_current", models.BooleanField(default=True)),
                ("allergies_checked", models.BooleanField(default=True)),
                ("medications_checked", models.BooleanField(default=True)),
                ("vision_screened", models.BooleanField(default=False)),
                ("hearing_screened", models.BooleanField(default=False)),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("document_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_assessments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_assessments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_assessments",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("compliance", "Compliance"),
                            ("quality", "Quality"),
                            ("safety", "Safety"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("audit_date", models.DateField()),
                ("auditor", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("findings", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                (
                    "compliance_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("report_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_audits",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "health_audits",
                "ordering": ["-audit_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthEducationMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("brochure", "Brochure"),
                            ("video", "Video"),
                            ("article", "Article"),
                            ("poster", "Poster"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("file_url", models.URLField(blank=True, max_length=500)),
                ("target_audience", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_education_materials",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "health_education_materials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("campaign_type", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("target_audience", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("participants_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_campaigns",
                        to="auth_service.school",
                    ),
                ),
                (
                    "materials",
                    models.ManyToManyField(blank=True, to="health_clinic.healtheducationmaterial"),
                ),
            ],
            options={
                "db_table": "health_campaigns",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthInsuranceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("health", "Health Insurance"),
                            ("dental", "Dental Insurance"),
                            ("vision", "Vision Insurance"),
                            ("other", "Other"),
                        ],
                        default="health",
                        max_length=20,
                    ),
                ),
                ("provider_name", models.CharField(max_length=200)),
                ("policy_number", models.CharField(max_length=100)),
                ("group_number", models.CharField(blank=True, max_length=100)),
                ("subscriber_name", models.CharField(blank=True, max_length=200)),
                (
                    "subscriber_relationship",
                    models.CharField(blank=True, max_length=50),
                ),
                ("effective_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "copay_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "deductible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_insurance_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_insurance_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_insurance_records",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthRiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_date", models.DateField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("risk_factors", models.JSONField(blank=True, default=list)),
                ("chronic_conditions", models.TextField(blank=True)),
                ("family_history_risks", models.TextField(blank=True)),
                ("lifestyle_factors", models.TextField(blank=True)),
                ("environmental_factors", models.TextField(blank=True)),
                ("mitigation_plan", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_risk_assessments",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_risk_assessments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_risk_assessments",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthStaffTraining",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("training_name", models.CharField(max_length=200)),
                ("training_type", models.CharField(blank=True, max_length=100)),
                ("provider", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("certificate_url", models.URLField(blank=True, max_length=500)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_staff_training",
                        to="auth_service.school",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_training",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_staff_training",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("questions", models.JSONField(blank=True, default=list)),
                ("target_audience", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=True)),
                ("response_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_surveys",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "health_surveys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("test_date", models.DateField()),
                ("result_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_value", models.CharField(blank=True, max_length=100)),
                ("normal_range", models.CharField(blank=True, max_length=100)),
                ("is_abnormal", models.BooleanField(default=False)),
                ("lab_name", models.CharField(blank=True, max_length=200)),
                ("document_url", models.URLField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_lab_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_lab_results",
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalEquipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("equipment_type", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                            ("out_of_service", "Out of Service"),
                        ],
                        default="operational",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("last_calibration_date", models.DateField(blank=True, null=True)),
                ("next_calibration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_equipment",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "health_medical_equipment",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("calibration", "Calibration"),
                            ("repair", "Repair"),
                            ("preventive", "Preventive"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("maintenance_date", models.DateField()),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("performed_by", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="health_clinic.medicalequipment",
                    ),
                ),
            ],
            options={
                "db_table": "health_equipment_maintenance",
                "ordering": ["-maintenance_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("condition", "Medical Condition"),
                            ("surgery", "Surgery"),
                            ("hospitalization", "Hospitalization"),
                            ("injury", "Injury"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("condition_name", models.CharField(max_length=200)),
                ("diagnosis_date", models.DateField(blank=True, null=True)),
                ("treating_physician", models.CharField(blank=True, max_length=200)),
                ("treatment", models.TextField(blank=True)),
                ("outcome", models.TextField(blank=True)),
                ("is_chronic", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_medical_history",
                "ordering": ["-diagnosis_date"],
            },
        ),
        migrations.CreateModel(
            name="MentalHealthRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("counseling", "Counseling"),
                            ("therapy", "Therapy"),
                            ("assessment", "Assessment"),
                            ("crisis", "Crisis Intervention"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_date", models.DateField()),
                ("presenting_issue", models.TextField(blank=True)),
                ("assessment_findings", models.TextField(blank=True)),
                ("diagnosis", models.CharField(blank=True, max_length=200)),
                ("treatment_plan", models.TextField(blank=True)),
                ("interventions", models.TextField(blank=True)),
                ("progress_notes", models.TextField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("is_confidential", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mental_health_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mental_health_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_mental_health_records",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=200)),
                ("dose_number", models.PositiveSmallIntegerField(default=1)),
                ("due_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("due", "Due"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("exempted", "Exempted"),
                        ],
                        default="due",
                        max_length=20,
                    ),
                ),
                ("administered_by", models.CharField(blank=True, max_length=200)),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                ("site_of_administration", models.CharField(blank=True, max_length=50)),
                ("reactions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_schedule_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_schedule_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_vaccination_schedule",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="VisionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("screening_date", models.DateField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("needs_correction", "Needs Correction"),
                            ("referred", "Referred to Specialist"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("left_eye_vision", models.CharField(blank=True, max_length=20)),
                ("right_eye_vision", models.CharField(blank=True, max_length=20)),
                ("color_blindness", models.BooleanField(default=False)),
                ("glasses_prescribed", models.BooleanField(default=False)),
                ("prescription_details", models.TextField(blank=True)),
                ("specialist_referral", models.BooleanField(default=False)),
                ("referral_details", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_records",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_vision_records",
                "ordering": ["-screening_date"],
            },
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recorded_date", models.DateField()),
                ("recorded_time", models.TimeField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
                ),
                ("heart_rate", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "respiratory_rate",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "blood_pressure_systolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "oxygen_saturation",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "blood_glucose",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "pain_scale",
                    models.PositiveSmallIntegerField(blank=True, help_text="0-10 scale", null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "health_vital_signs",
                "ordering": ["-recorded_date", "-recorded_time"],
            },
        ),
    ]
