# Generated by Django 4.2.13 on 2026-07-15 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sport", "Sport"),
                            ("academic", "Academic"),
                            ("arts", "Arts & Culture"),
                            ("club", "Club & Society"),
                            ("other", "Other"),
                        ],
                        default="sport",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("min_players", models.PositiveSmallIntegerField(default=1)),
                ("max_players", models.PositiveSmallIntegerField(default=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "sports_sports",
                "ordering": ["name"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("boys", "Boys"),
                            ("girls", "Girls"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assistant_coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_coached_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coached_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_teams",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "db_table": "sports_teams",
                "ordering": ["sport", "name"],
                "unique_together": {("school", "sport", "name")},
            },
        ),
        migrations.CreateModel(
            name="SportEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        help_text="Match, Tournament, Tryout, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "opponent",
                    models.CharField(
                        blank=True,
                        help_text="Opposing school/team name",
                        max_length=150,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("event_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("home_score", models.CharField(blank=True, max_length=30)),
                ("opponent_score", models.CharField(blank=True, max_length=30)),
                ("result", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sport_events",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="sports.sport",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_events",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="SportAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="1st Place, Best Player, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="School, District, State, National, International",
                        max_length=50,
                    ),
                ),
                ("awarded_date", models.DateField()),
                ("certificate_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="achievements",
                        to="sports.sportevent",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sport_achievements",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sport_achievements",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="achievements",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_achievements",
                "ordering": ["-awarded_date"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("captain", "Captain"),
                            ("vice_captain", "Vice Captain"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("dropped", "Dropped"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_team_members",
                "ordering": ["team", "student"],
                "unique_together": {("team", "student")},
            },
        ),
    ]
