# Generated by Django 5.1.15 on 2026-08-31 10:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("sports", "0001_initial"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("ball", "Ball"),
                            ("uniform", "Uniform"),
                            ("protective", "Protective Gear"),
                            ("training", "Training Equipment"),
                            ("maintenance", "Maintenance"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("retired", "Retired"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("vendor", models.CharField(blank=True, max_length=150)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("maintenance_notes", models.TextField(blank=True)),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_equipment",
                        to="students.student",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_inventory",
                        to="auth_service.school",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "equipment_inventory",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameLineup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lineup_type",
                    models.CharField(
                        choices=[
                            ("starting", "Starting"),
                            ("bench", "Bench"),
                            ("substitute", "Substitute"),
                            ("injured", "Injured"),
                            ("scratched", "Scratched"),
                        ],
                        default="starting",
                        max_length=15,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=50)),
                (
                    "jersey_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("subbed_in_at", models.TimeField(blank=True, null=True)),
                ("subbed_out_at", models.TimeField(blank=True, null=True)),
                ("substitution_reason", models.CharField(blank=True, max_length=100)),
                ("minutes_played", models.PositiveSmallIntegerField(default=0)),
                ("stats_snapshot", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="sports.sportevent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_lineups",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "game_lineups",
                "ordering": ["lineup_type", "position"],
            },
        ),
        migrations.CreateModel(
            name="InjuryTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "injury_type",
                    models.CharField(
                        choices=[
                            ("sprain", "Sprain"),
                            ("strain", "Strain"),
                            ("fracture", "Fracture"),
                            ("concussion", "Concussion"),
                            ("bruise", "Bruise"),
                            ("cut", "Cut/Laceration"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("critical", "Critical"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                ("body_part", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("injury_date", models.DateField()),
                ("reported_date", models.DateField(auto_now_add=True)),
                ("expected_return", models.DateField(blank=True, null=True)),
                ("actual_return", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("recovering", "Recovering"),
                            ("cleared", "Cleared"),
                            ("chronic", "Chronic"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("treatment_notes", models.TextField(blank=True)),
                ("doctor_name", models.CharField(blank=True, max_length=150)),
                ("doctor_contact", models.CharField(blank=True, max_length=100)),
                (
                    "activity_restriction",
                    models.TextField(blank=True, help_text="Restricted activities"),
                ),
                ("return_to_play_protocol", models.TextField(blank=True)),
                ("cleared_date", models.DateField(blank=True, null=True)),
                ("medical_report_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cleared_injuries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_injuries",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injuries",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="injuries",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_injuries",
                "ordering": ["-injury_date"],
            },
        ),
        migrations.CreateModel(
            name="PlayerStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("games_played", models.PositiveSmallIntegerField(default=0)),
                ("games_started", models.PositiveSmallIntegerField(default=0)),
                ("minutes_played", models.PositiveIntegerField(default=0)),
                (
                    "stats",
                    models.JSONField(blank=True, default=dict, help_text="Sport-specific statistics"),
                ),
                ("goals", models.PositiveSmallIntegerField(default=0)),
                ("assists", models.PositiveSmallIntegerField(default=0)),
                ("points", models.PositiveSmallIntegerField(default=0)),
                ("rebounds", models.PositiveSmallIntegerField(default=0)),
                ("steals", models.PositiveSmallIntegerField(default=0)),
                ("blocks", models.PositiveSmallIntegerField(default=0)),
                ("turnovers", models.PositiveSmallIntegerField(default=0)),
                ("fouls", models.PositiveSmallIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("season", models.CharField(blank=True, max_length=50)),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_statistics",
                        to="sports.sportevent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_statistics",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_statistics",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "player_statistics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "practice_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Practice"),
                            ("conditioning", "Conditioning"),
                            ("scrimmage", "Scrimmage"),
                            ("film", "Film Session"),
                            ("meeting", "Team Meeting"),
                            ("other", "Other"),
                        ],
                        default="regular",
                        max_length=15,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("field_court", models.CharField(blank=True, max_length=100)),
                ("is_recurring", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("required", models.BooleanField(default=True)),
                (
                    "min_attendance",
                    models.PositiveSmallIntegerField(default=0, help_text="Minimum attendance required"),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coached_practices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_schedules",
                        to="auth_service.school",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practices",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "practice_schedules",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="SportsAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analytics_type",
                    models.CharField(
                        choices=[
                            ("team_performance", "Team Performance"),
                            ("player_stats", "Player Statistics"),
                            ("win_loss", "Win/Loss Analysis"),
                            ("scoring_trends", "Scoring Trends"),
                            ("attendance", "Attendance Analytics"),
                            ("injury", "Injury Analytics"),
                            ("opponent", "Opponent Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("analytics_data", models.JSONField(blank=True, default=dict)),
                ("insights", models.JSONField(blank=True, default=list)),
                ("recommendations", models.TextField(blank=True)),
                ("chart_type", models.CharField(blank=True, max_length=50)),
                ("chart_data", models.JSONField(blank=True, default=dict)),
                ("key_metrics", models.JSONField(blank=True, default=dict)),
                ("is_shared", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_sports_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_analytics",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="SportsFundraising",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("equipment", "Equipment"),
                            ("travel", "Travel"),
                            ("fees", "Player Fees"),
                            ("facility", "Facility"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("donor_count", models.PositiveIntegerField(default=0)),
                (
                    "average_donation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_online", models.BooleanField(default=True)),
                ("online_donation_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sports_fundraising",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraising",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_fundraising",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SportsMedicalClearance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "clearance_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Examination"),
                            ("concussion", "Concussion Protocol"),
                            ("cardiac", "Cardiac Screening"),
                            ("allergy", "Allergy Action Plan"),
                            ("other", "Other"),
                        ],
                        default="physical",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("expired", "Expired"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("physician_name", models.CharField(max_length=150)),
                ("physician_contact", models.CharField(blank=True, max_length=100)),
                ("exam_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("document_url", models.URLField(blank=True)),
                (
                    "restrictions",
                    models.TextField(blank=True, help_text="Medical restrictions"),
                ),
                (
                    "cleared_for",
                    models.TextField(blank=True, help_text="Cleared for which activities"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_clearances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_medical_clearances",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_clearances",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "sports_medical_clearances",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="SportsPhotoGallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("team", "Team Photo"),
                            ("game", "Game Photo"),
                            ("practice", "Practice Photo"),
                            ("award", "Award Photo"),
                            ("event", "Event Photo"),
                            ("other", "Other"),
                        ],
                        default="team",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("photo_url", models.URLField()),
                ("thumbnail_url", models.URLField(blank=True)),
                ("photographer", models.CharField(blank=True, max_length=150)),
                ("taken_date", models.DateField(auto_now_add=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="sports.sportevent",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_galleries",
                        to="sports.team",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_sports_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sports_photo_galleries",
                "ordering": ["-taken_date"],
            },
        ),
        migrations.CreateModel(
            name="SportsRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("team", "Team"),
                            ("season", "Season"),
                            ("tryout", "Tryout"),
                        ],
                        default="individual",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Fall 2025, Spring 2026",
                        max_length=50,
                    ),
                ),
                ("academic_year", models.CharField(blank=True, max_length=20)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=15,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("medical_clearance", models.BooleanField(default=False)),
                ("emergency_contact", models.CharField(blank=True, max_length=150)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("consent_form_signed", models.BooleanField(default=False)),
                ("physical_exam_date", models.DateField(blank=True, null=True)),
                ("physical_exam_expiry", models.DateField(blank=True, null=True)),
                ("parent_name", models.CharField(blank=True, max_length=150)),
                ("parent_email", models.EmailField(blank=True, max_length=254)),
                ("parent_phone", models.CharField(blank=True, max_length=20)),
                ("parent_consent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_registrations",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="sports.sport",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_registrations",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrations",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_registrations",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="SportsSponsorship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sponsor_name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(blank=True, max_length=150)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "sponsorship_level",
                    models.CharField(
                        choices=[
                            ("platinum", "Platinum"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "in_kind_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Value of in-kind donations",
                        max_digits=12,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("logo_on_jersey", models.BooleanField(default=False)),
                ("banner_at_field", models.BooleanField(default=False)),
                ("mention_in_programs", models.BooleanField(default=False)),
                ("social_media_recognition", models.BooleanField(default=False)),
                ("other_benefits", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("renewed", "Renewed"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorships",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_sponsorships",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SportsTravelManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "travel_type",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("van", "Van"),
                            ("carpool", "Carpool"),
                            ("flight", "Flight"),
                            ("other", "Other"),
                        ],
                        default="bus",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=15,
                    ),
                ),
                ("departure_date", models.DateTimeField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("vehicle_info", models.CharField(blank=True, max_length=200)),
                ("driver_name", models.CharField(blank=True, max_length=150)),
                ("driver_contact", models.CharField(blank=True, max_length=20)),
                ("hotel_name", models.CharField(blank=True, max_length=200)),
                ("hotel_address", models.TextField(blank=True)),
                ("hotel_confirmation", models.CharField(blank=True, max_length=100)),
                ("meal_plan", models.TextField(blank=True)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("travelers", models.JSONField(blank=True, default=list)),
                ("itinerary_url", models.URLField(blank=True)),
                ("emergency_contact", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel",
                        to="sports.sportevent",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_arrangements",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_travel_management",
                "ordering": ["-departure_date"],
            },
        ),
        migrations.CreateModel(
            name="SportsUniformOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uniform_type",
                    models.CharField(help_text="Jersey, Shorts, etc.", max_length=100),
                ),
                ("size", models.CharField(max_length=20)),
                (
                    "jersey_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sizing", "Sizing"),
                            ("ordered", "Ordered"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=15,
                    ),
                ),
                ("ordered_date", models.DateField(blank=True, null=True)),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("delivered_date", models.DateField(blank=True, null=True)),
                ("vendor", models.CharField(blank=True, max_length=150)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniform_orders",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniform_orders",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_uniform_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SportsVolunteerManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_name", models.CharField(max_length=150)),
                ("parent_email", models.EmailField(max_length=254)),
                ("parent_phone", models.CharField(max_length=20)),
                (
                    "volunteer_type",
                    models.CharField(
                        choices=[
                            ("coach", "Coach"),
                            ("assistant", "Assistant Coach"),
                            ("scorekeeper", "Scorekeeper"),
                            ("timer", "Timer"),
                            ("chaperone", "Chaperone"),
                            ("fundraiser", "Fundraiser"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="interested",
                        max_length=15,
                    ),
                ),
                (
                    "availability",
                    models.JSONField(blank=True, default=list, help_text="Available days/times"),
                ),
                ("background_check_complete", models.BooleanField(default=False)),
                ("background_check_date", models.DateField(blank=True, null=True)),
                (
                    "total_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("skills", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_volunteers",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteers",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_volunteer_management",
                "ordering": ["team", "parent_name"],
            },
        ),
        migrations.CreateModel(
            name="TeamCommunication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement"),
                            ("message", "Message"),
                            ("reminder", "Reminder"),
                            ("alert", "Alert"),
                        ],
                        default="message",
                        max_length=15,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Members"),
                            ("players", "Players Only"),
                            ("coaches", "Coaches Only"),
                            ("parents", "Parents Only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("attachment_url", models.URLField(blank=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("read_by", models.JSONField(blank=True, default=list)),
                ("send_immediately", models.BooleanField(default=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_team_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_communications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeagueStanding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("league_name", models.CharField(max_length=200)),
                ("season", models.CharField(max_length=50)),
                ("division", models.CharField(blank=True, max_length=100)),
                ("games_played", models.PositiveSmallIntegerField(default=0)),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("losses", models.PositiveSmallIntegerField(default=0)),
                ("ties", models.PositiveSmallIntegerField(default=0)),
                ("points_for", models.PositiveIntegerField(default=0)),
                ("points_against", models.PositiveIntegerField(default=0)),
                ("rank", models.PositiveSmallIntegerField(default=0)),
                (
                    "streak",
                    models.CharField(blank=True, help_text="e.g., W3, L1", max_length=20),
                ),
                (
                    "last_5",
                    models.CharField(blank=True, help_text="Last 5 games: W3-L2", max_length=20),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_standings",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_standings",
                        to="sports.sport",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_standings",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "league_standings",
                "ordering": ["rank"],
                "unique_together": {("league_name", "team", "season")},
            },
        ),
        migrations.CreateModel(
            name="SportsAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("practice", "Practice"),
                            ("game", "Game"),
                            ("tryout", "Tryout"),
                            ("conditioning", "Conditioning"),
                            ("other", "Other"),
                        ],
                        default="practice",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("tardy", "Late"),
                            ("excused", "Excused"),
                            ("injured", "Injured"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("minutes_late", models.PositiveSmallIntegerField(default=0)),
                ("date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance",
                        to="sports.sportevent",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance",
                        to="sports.practiceschedule",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_sports_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_attendance",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_attendance",
                "ordering": ["-date"],
                "unique_together": {("student", "team", "date", "session_type")},
            },
        ),
        migrations.CreateModel(
            name="TeamRoster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "roster_type",
                    models.CharField(
                        choices=[
                            ("varsity", "Varsity"),
                            ("jv", "Junior Varsity"),
                            ("freshman", "Freshman"),
                            ("club", "Club"),
                        ],
                        default="varsity",
                        max_length=10,
                    ),
                ),
                ("season", models.CharField(max_length=50)),
                ("academic_year", models.CharField(max_length=20)),
                (
                    "roster_data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of players with jersey numbers",
                    ),
                ),
                ("total_players", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("max_roster_size", models.PositiveSmallIntegerField(default=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rosters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_rosters",
                "ordering": ["-created_at"],
                "unique_together": {("team", "roster_type", "season")},
            },
        ),
    ]
