# Generated by Django 5.1.15 on 2026-08-31 10:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("sports", "0003_compliancetracking_facilitybooking_livegamescore_and_more"),
        ("students", "0004_role_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Eligibility"),
                            ("age", "Age Eligibility"),
                            ("grade", "Grade Eligibility"),
                            ("attendance", "Attendance Eligibility"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "min_gpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("min_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("min_grade", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_grade", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "min_attendance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum attendance percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "db_table": "sports_eligibility_rules",
                "ordering": ["rule_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Insurance"),
                            ("school", "School Insurance"),
                            ("athletic", "Athletic Insurance"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("provider", models.CharField(max_length=200)),
                ("policy_number", models.CharField(max_length=100)),
                ("group_number", models.CharField(blank=True, max_length=100)),
                ("coverage_start", models.DateField()),
                ("coverage_end", models.DateField()),
                ("provider_phone", models.CharField(blank=True, max_length=20)),
                ("provider_email", models.EmailField(blank=True, max_length=254)),
                ("insurance_card_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                            ("denied", "Denied"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_records",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_records",
                        to="students.student",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_insurance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sports_insurance",
                "ordering": ["-coverage_end"],
            },
        ),
        migrations.CreateModel(
            name="MerchandiseStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("jersey", "Jersey"),
                            ("shorts", "Shorts"),
                            ("jacket", "Jacket"),
                            ("cap", "Cap"),
                            ("bag", "Bag"),
                            ("accessory", "Accessory"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sale_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                ("sizes_available", models.JSONField(blank=True, default=list)),
                ("colors_available", models.JSONField(blank=True, default=list)),
                ("image_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("total_sold", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_online", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchandise",
                        to="auth_service.school",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchandise",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_merchandise",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MerchandiseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("buyer_name", models.CharField(max_length=150)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("buyer_phone", models.CharField(blank=True, max_length=20)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("size", models.CharField(blank=True, max_length=20)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=15,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("shipping_address", models.TextField(blank=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("shipped_date", models.DateField(blank=True, null=True)),
                ("delivered_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchandise_orders",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchandise_orders",
                        to="students.student",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="sports.merchandisestore",
                    ),
                ),
            ],
            options={
                "db_table": "sports_merchandise_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerTransferSystem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Transfer"),
                            ("external", "External Transfer"),
                            ("loan", "Loan"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "from_school",
                    models.CharField(blank=True, help_text="For external transfers", max_length=200),
                ),
                (
                    "to_school",
                    models.CharField(blank=True, help_text="For external transfers", max_length=200),
                ),
                ("reason", models.TextField(blank=True)),
                ("request_date", models.DateField(auto_now_add=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("transfer_paperwork_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_out",
                        to="sports.team",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="students.student",
                    ),
                ),
                (
                    "to_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_in",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_transfers",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="SportsGamification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("participation", "Participation"),
                            ("achievement", "Achievement"),
                            ("milestone", "Milestone"),
                            ("special", "Special"),
                            ("team", "Team Badge"),
                        ],
                        max_length=15,
                    ),
                ),
                ("icon_url", models.URLField(blank=True)),
                ("icon_color", models.CharField(blank=True, max_length=20)),
                ("criteria", models.JSONField(blank=True, default=dict)),
                ("points_value", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("times_awarded", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_badges",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "sports_gamification_badges",
                "ordering": ["badge_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SportsLeaderboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("points", "Points Leaderboard"),
                            ("wins", "Wins Leaderboard"),
                            ("goals", "Goals Leaderboard"),
                            ("attendance", "Attendance Leaderboard"),
                            ("academic", "Academic-Athletic"),
                            ("overall", "Overall"),
                        ],
                        max_length=15,
                    ),
                ),
                ("season", models.CharField(max_length=50)),
                ("entries", models.JSONField(blank=True, default=list)),
                ("is_public", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_leaderboards",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leaderboards",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "db_table": "sports_leaderboards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SuspensionManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suspension_type",
                    models.CharField(
                        choices=[
                            ("game", "Game Suspension"),
                            ("practice", "Practice Suspension"),
                            ("season", "Season Suspension"),
                            ("indefinite", "Indefinite"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField()),
                ("incident_date", models.DateField()),
                ("games_missed", models.PositiveSmallIntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("appealed", "Appealed"),
                            ("lifted", "Lifted"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("appeal_submitted", models.BooleanField(default=False)),
                ("appeal_date", models.DateField(blank=True, null=True)),
                ("appeal_outcome", models.TextField(blank=True)),
                ("document_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_sports_suspensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_suspensions",
                        to="auth_service.school",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_suspensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_suspensions",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_suspensions",
                "ordering": ["-incident_date"],
            },
        ),
        migrations.CreateModel(
            name="TournamentBracket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "bracket_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Elimination"),
                            ("double", "Double Elimination"),
                            ("round_robin", "Round Robin"),
                            ("swiss", "Swiss System"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("max_teams", models.PositiveSmallIntegerField(default=16)),
                ("current_round", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("bracket_data", models.JSONField(blank=True, default=dict)),
                ("first_prize", models.CharField(blank=True, max_length=200)),
                ("second_prize", models.CharField(blank=True, max_length=200)),
                ("third_prize", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_brackets",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_brackets",
                        to="sports.sport",
                    ),
                ),
            ],
            options={
                "db_table": "sports_tournament_brackets",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TournamentMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("round_number", models.PositiveSmallIntegerField()),
                ("match_number", models.PositiveSmallIntegerField()),
                ("team_1_score", models.PositiveSmallIntegerField(default=0)),
                ("team_2_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("bye", "Bye"),
                            ("forfeit", "Forfeit"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("match_date", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="sports.tournamentbracket",
                    ),
                ),
                (
                    "team_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_matches_as_team1",
                        to="sports.team",
                    ),
                ),
                (
                    "team_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_matches_as_team2",
                        to="sports.team",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_wins",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_tournament_matches",
                "ordering": ["round_number", "match_number"],
            },
        ),
        migrations.CreateModel(
            name="SeasonArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season", models.CharField(max_length=50)),
                ("academic_year", models.CharField(max_length=20)),
                ("games_played", models.PositiveSmallIntegerField(default=0)),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("losses", models.PositiveSmallIntegerField(default=0)),
                ("ties", models.PositiveSmallIntegerField(default=0)),
                ("points_scored", models.PositiveIntegerField(default=0)),
                ("points_allowed", models.PositiveIntegerField(default=0)),
                ("roster_snapshot", models.JSONField(blank=True, default=list)),
                ("championships", models.PositiveSmallIntegerField(default=0)),
                ("tournament_appearances", models.PositiveSmallIntegerField(default=0)),
                ("archive_data", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_archives",
                        to="auth_service.school",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_archives",
                        to="sports.team",
                    ),
                ),
            ],
            options={
                "db_table": "sports_season_archives",
                "ordering": ["-academic_year", "-season"],
                "unique_together": {("team", "season")},
            },
        ),
        migrations.CreateModel(
            name="BadgeAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("awarded_date", models.DateField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_sports_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports_badge_awards",
                        to="students.student",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badge_awards",
                        to="sports.team",
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="sports.sportsgamification",
                    ),
                ),
            ],
            options={
                "db_table": "sports_badge_awards",
                "ordering": ["-awarded_date"],
                "unique_together": {("badge", "student")},
            },
        ),
        migrations.CreateModel(
            name="StudentEligibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("ineligible", "Ineligible"),
                            ("probation", "Probation"),
                            ("pending", "Pending Review"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "current_gpa",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                (
                    "current_attendance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Attendance percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("last_review_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_eligibility",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_eligibility",
                        to="auth_service.school",
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_eligibility",
                        to="sports.sport",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_status",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "sports_student_eligibility",
                "ordering": ["student"],
                "unique_together": {("student", "school")},
            },
        ),
    ]
