# Generated by Django 4.2.13 on 2026-07-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferenceslot",
            name="is_zoom_created",
            field=models.BooleanField(
                default=False,
                help_text="Whether a Zoom meeting has been created for this slot",
            ),
        ),
        migrations.AddField(
            model_name="conferenceslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="conferenceslot",
            name="zoom_join_url",
            field=models.URLField(
                blank=True, default="", help_text="Zoom join link for participants"
            ),
        ),
        migrations.AddField(
            model_name="conferenceslot",
            name="zoom_meeting_id",
            field=models.CharField(
                blank=True, default="", help_text="Zoom meeting ID", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="conferenceslot",
            name="zoom_password",
            field=models.CharField(
                blank=True, default="", help_text="Zoom meeting password", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="conferenceslot",
            name="zoom_start_url",
            field=models.URLField(
                blank=True, default="", help_text="Zoom start link for host"
            ),
        ),
    ]
