# Generated by Django 5.1.15 on 2026-08-31 15:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0005_user_backup_code_failed_attempts_and_more"),
        ("conferences", "0002_add_zoom_meeting_fields"),
        ("students", "0005_studentcategory_studentcontact_studentcustomfield_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "availability_type",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("tentative", "Tentative"),
                        ],
                        default="available",
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("is_virtual_available", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_availability",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conference_availability",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("is_virtual", models.BooleanField(default=False)),
                ("meeting_link", models.URLField(blank=True)),
                ("meeting_id", models.CharField(blank=True, max_length=100)),
                ("meeting_password", models.CharField(blank=True, max_length=50)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for conference"),
                ),
                ("notes", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="conferences.conferenceslot",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_bookings",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conference_bookings",
                "ordering": ["-booked_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_for",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("conference", "Conference"),
                            ("school", "School"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "preparedness_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "helpfulness_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("positive_feedback", models.TextField(blank=True)),
                ("suggestions", models.TextField(blank=True)),
                ("additional_comments", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="conferences.conferencebooking",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conference_feedbacks",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceNotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General Notes"),
                            ("academic", "Academic Discussion"),
                            ("behavior", "Behavior Notes"),
                            ("action", "Action Items"),
                            ("follow_up", "Follow-up Required"),
                            ("recommendations", "Recommendations"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("has_action_items", models.BooleanField(default=False)),
                (
                    "action_items",
                    models.JSONField(default=list, help_text="List of action items"),
                ),
                ("action_items_completed", models.BooleanField(default=False)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("shared_with_parent", models.BooleanField(default=False)),
                ("shared_with_student", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_notes",
                        to="conferences.conferencebooking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conference_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "send_before_minutes",
                    models.PositiveIntegerField(default=60, help_text="Minutes before conference"),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="conferences.conferencebooking",
                    ),
                ),
            ],
            options={
                "db_table": "conference_reminders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("attendance", "Attendance Report"),
                            ("summary", "Conference Summary"),
                            ("teacher", "Teacher-wise Report"),
                            ("grade", "Grade-wise Report"),
                            ("follow_up", "Follow-up Report"),
                            ("feedback", "Feedback Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("summary", models.TextField(blank=True)),
                ("findings", models.JSONField(default=dict)),
                ("recommendations", models.TextField(blank=True)),
                ("total_conferences", models.PositiveIntegerField(default=0)),
                ("total_attended", models.PositiveIntegerField(default=0)),
                ("total_no_show", models.PositiveIntegerField(default=0)),
                (
                    "attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("by_teacher", models.JSONField(default=dict)),
                ("by_grade", models.JSONField(default=dict)),
                ("by_type", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_reports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ptc", "Parent-Teacher Conference"),
                            ("student_led", "Student-Led Conference"),
                            ("three_way", "Three-Way Conference"),
                            ("iep", "IEP Meeting"),
                            ("planning", "Academic Planning"),
                            ("progress", "Progress Review"),
                            ("discipline", "Discipline Conference"),
                            ("orientation", "Orientation"),
                            ("other", "Other"),
                        ],
                        default="ptc",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_duration_minutes",
                    models.PositiveSmallIntegerField(default=15),
                ),
                ("max_participants", models.PositiveSmallIntegerField(default=3)),
                ("allow_virtual", models.BooleanField(default=True)),
                ("allow_notes", models.BooleanField(default=True)),
                ("require_student", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_types",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_duration_minutes",
                    models.PositiveSmallIntegerField(default=15),
                ),
                (
                    "agenda_items",
                    models.JSONField(default=list, help_text="List of agenda items"),
                ),
                (
                    "discussion_topics",
                    models.JSONField(default=list, help_text="Discussion topics"),
                ),
                (
                    "questions_to_ask",
                    models.JSONField(default=list, help_text="Questions for parent/teacher"),
                ),
                ("require_notes", models.BooleanField(default=True)),
                ("require_feedback", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_templates",
                        to="auth_service.school",
                    ),
                ),
                (
                    "conference_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conferences.conferencetype",
                    ),
                ),
            ],
            options={
                "db_table": "conference_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="conferencebooking",
            name="booking_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conferences.conferencetype",
            ),
        ),
        migrations.CreateModel(
            name="FollowUpTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("overdue", "Overdue"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("due_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conference_follow_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="conferences.conferencebooking",
                    ),
                ),
            ],
            options={
                "db_table": "follow_up_tracking",
                "ordering": ["due_date", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="VirtualConference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("zoom", "Zoom"),
                            ("meet", "Google Meet"),
                            ("teams", "Microsoft Teams"),
                            ("other", "Other"),
                        ],
                        default="zoom",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("meeting_id", models.CharField(max_length=100)),
                ("meeting_url", models.URLField()),
                ("meeting_password", models.CharField(blank=True, max_length=50)),
                ("host_url", models.URLField(blank=True)),
                ("recording_url", models.URLField(blank=True)),
                ("has_recording", models.BooleanField(default=False)),
                ("participants_joined", models.PositiveSmallIntegerField(default=0)),
                ("scheduled_duration", models.PositiveSmallIntegerField(default=15)),
                (
                    "actual_duration",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("had_technical_issues", models.BooleanField(default=False)),
                ("technical_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_details",
                        to="conferences.conferencebooking",
                    ),
                ),
            ],
            options={
                "db_table": "virtual_conferences",
            },
        ),
        migrations.CreateModel(
            name="WaitlistManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("offered", "Slot Offered"),
                            ("booked", "Booked"),
                            ("expired", "Offer Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=15,
                    ),
                ),
                ("offered_at", models.DateTimeField(blank=True, null=True)),
                ("offer_expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_waitlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist",
                        to="conferences.conferenceslot",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_waitlist",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "waitlist_management",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conference_date", models.DateField()),
                ("was_virtual", models.BooleanField(default=False)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=15)),
                ("was_attended", models.BooleanField(default=True)),
                ("had_notes", models.BooleanField(default=False)),
                ("had_action_items", models.BooleanField(default=False)),
                ("had_follow_up", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="conferences.conferencebooking",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_conferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_history",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_conferences",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_conferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conference_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conferences.conferencetype",
                    ),
                ),
            ],
            options={
                "db_table": "conference_history",
                "ordering": ["-conference_date"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "conference_date"],
                        name="conference__teacher_8a5166_idx",
                    ),
                    models.Index(
                        fields=["parent", "conference_date"],
                        name="conference__parent__1807c9_idx",
                    ),
                    models.Index(
                        fields=["student", "conference_date"],
                        name="conference__student_6437b6_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="conferencebooking",
            index=models.Index(fields=["parent", "status"], name="conference__parent__000328_idx"),
        ),
        migrations.AddIndex(
            model_name="conferencebooking",
            index=models.Index(fields=["student", "status"], name="conference__student_ef1ed5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="waitlistmanagement",
            unique_together={("slot", "parent")},
        ),
    ]
