# Generated by Django 5.1.15 on 2026-09-01 10:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_service",
            "0007_ipgeolocationcache_permission_auditreportschedule_and_more",
        ),
        ("conferences", "0003_add_conferences_gaps"),
        ("students", "0006_studentacademicadvisor_studentachievement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceAccessibilityRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("interpreter", "Sign Language Interpreter"),
                            ("translator", "Language Translator"),
                            ("wheelchair", "Wheelchair Access"),
                            ("large_print", "Large Print Materials"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("language", models.CharField(blank=True, max_length=50)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibility_requirements",
                        to="conferences.conferencebooking",
                    ),
                ),
            ],
            options={
                "db_table": "conference_accessibility_requirements",
            },
        ),
        migrations.CreateModel(
            name="ConferenceBlockedSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.TextField(blank=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_blocked_slots",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_blocked_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conference_blocked_slots",
            },
        ),
        migrations.CreateModel(
            name="ConferenceBookingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("time_slot", "Time Slot Restriction"),
                            ("grade", "Grade Restriction"),
                            ("teacher_limit", "Teacher Booking Limit"),
                            ("parent_limit", "Parent Booking Limit"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_booking_rules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_booking_rules",
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("schedule", "Schedule Export"),
                            ("attendance", "Attendance Report"),
                            ("feedback", "Feedback Summary"),
                            ("all", "All Data"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("pdf", "PDF"), ("excel", "Excel")],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="conferences/exports/"),
                ),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_exports",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_exports",
            },
        ),
        migrations.CreateModel(
            name="ConferenceFeedbackTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("questions", models.JSONField(default=list)),
                ("target_audience", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_feedback_templates",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_feedback_templates",
            },
        ),
        migrations.CreateModel(
            name="ConferenceFollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_required", models.TextField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_follow_ups",
                        to="conferences.conferencebooking",
                    ),
                ),
            ],
            options={
                "db_table": "conference_follow_ups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceHistoryDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conference_date", models.DateField()),
                ("conference_type", models.CharField(blank=True, max_length=50)),
                ("topics_discussed", models.JSONField(blank=True, default=list)),
                ("outcome", models.TextField(blank=True)),
                ("follow_up_needed", models.BooleanField(default=False)),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conferences.conferencebooking",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_history_details",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_history_details",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "conference_history_details",
                "ordering": ["-conference_date"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In-Person"),
                            ("virtual", "Virtual"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=10,
                    ),
                ),
                ("building", models.CharField(blank=True, max_length=200)),
                ("room", models.CharField(blank=True, max_length=100)),
                ("capacity", models.PositiveIntegerField(default=10)),
                ("virtual_link", models.URLField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_locations",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_locations",
            },
        ),
        migrations.CreateModel(
            name="ConferenceConferenceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requires_parent_consent", models.BooleanField(default=False)),
                ("requires_student_consent", models.BooleanField(default=False)),
                ("auto_generate_notes", models.BooleanField(default=False)),
                ("max_duration_minutes", models.PositiveIntegerField(default=60)),
                ("allow_virtual", models.BooleanField(default=True)),
                ("allow_walk_in", models.BooleanField(default=False)),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extended_settings",
                        to="conferences.conferencetype",
                    ),
                ),
                (
                    "default_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conferences.conferencelocation",
                    ),
                ),
            ],
            options={
                "db_table": "conference_type_extended_settings",
            },
        ),
        migrations.CreateModel(
            name="ConferenceNoShow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rescheduled", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_shows",
                        to="conferences.conferencebooking",
                    ),
                ),
                (
                    "rescheduled_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_from",
                        to="conferences.conferencebooking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_no_shows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conference_no_shows",
            },
        ),
        migrations.CreateModel(
            name="ConferenceNoteTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sections", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_note_templates",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_note_templates",
            },
        ),
        migrations.CreateModel(
            name="ConferenceReminderSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("hours_before", models.PositiveIntegerField()),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("push", "Push")],
                        max_length=10,
                    ),
                ),
                ("message_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_reminder_schedules",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_reminder_schedules",
            },
        ),
        migrations.CreateModel(
            name="ConferenceResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("room", "Meeting Room"),
                            ("equipment", "Equipment"),
                            ("document", "Document"),
                            ("translator", "Translator"),
                        ],
                        max_length=15,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_reserved", models.BooleanField(default=False)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="conferences.conferencebooking",
                    ),
                ),
            ],
            options={
                "db_table": "conference_resources",
            },
        ),
        migrations.CreateModel(
            name="ConferenceRoomBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to="conferences.conferencebooking",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to="conferences.conferencelocation",
                    ),
                ),
            ],
            options={
                "db_table": "conference_room_bookings",
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_window_days", models.PositiveIntegerField(default=30)),
                ("cancellation_window_hours", models.PositiveIntegerField(default=24)),
                ("buffer_between_minutes", models.PositiveIntegerField(default=5)),
                ("max_conferences_per_day", models.PositiveIntegerField(default=20)),
                ("send_confirmation_email", models.BooleanField(default=True)),
                ("send_reminder_email", models.BooleanField(default=True)),
                ("reminder_hours_before", models.PositiveIntegerField(default=24)),
                ("collect_feedback", models.BooleanField(default=True)),
                ("feedback_deadline_days", models.PositiveIntegerField(default=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_settings",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_settings",
            },
        ),
        migrations.CreateModel(
            name="ConferenceSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("questions", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_surveys",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_surveys",
            },
        ),
        migrations.CreateModel(
            name="ConferenceSurveyResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answers", models.JSONField(default=dict)),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("comments", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="conferences.conferencesurvey",
                    ),
                ),
            ],
            options={
                "db_table": "conference_survey_responses",
            },
        ),
        migrations.CreateModel(
            name="ConferenceSystemNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_reminder", "Booking Reminder"),
                            ("booking_cancelled", "Booking Cancellation"),
                            ("waitlist_available", "Waitlist Spot Available"),
                            ("feedback_request", "Feedback Request"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("channel", models.CharField(default="email", max_length=10)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_sys_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_system_notifications",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_system_notifications",
            },
        ),
        migrations.CreateModel(
            name="ConferenceTemplateSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("suggested_questions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="conferences.conferencetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "conference_template_sections",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceTimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("blocked", "Blocked"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conferences.conferencebooking",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="conferences.conferencelocation",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_time_slots",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_time_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conference_time_slots",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ConferenceWaitingList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=15,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("preferred_dates", models.JSONField(blank=True, default=list)),
                ("preferred_times", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_waiting_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_waiting_lists",
                        to="auth_service.school",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_waiting_lists",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "conference_waiting_lists",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="RecurringConference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("day_of_week", models.CharField(blank=True, max_length=10)),
                ("time_of_day", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("last_occurrence", models.DateField(blank=True, null=True)),
                ("next_occurrence", models.DateField(blank=True, null=True)),
                ("total_occurrences", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_conferences",
                        to="auth_service.school",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_conferences_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recurring_conferences",
            },
        ),
        migrations.CreateModel(
            name="ConferenceAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_scheduled", models.PositiveIntegerField(default=0)),
                ("total_completed", models.PositiveIntegerField(default=0)),
                ("total_no_show", models.PositiveIntegerField(default=0)),
                ("total_cancelled", models.PositiveIntegerField(default=0)),
                ("total_parents", models.PositiveIntegerField(default=0)),
                ("total_teachers", models.PositiveIntegerField(default=0)),
                (
                    "parent_participation_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_duration_minutes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_satisfaction_rating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
                ),
                ("by_type_breakdown", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_analytics",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_analytics",
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="ConferenceApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_approvals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="conferences.conferencebooking",
                    ),
                ),
            ],
            options={
                "db_table": "conference_approvals",
                "unique_together": {("booking", "approver")},
            },
        ),
        migrations.CreateModel(
            name="ConferenceCalendarSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "calendar_type",
                    models.CharField(
                        choices=[
                            ("google", "Google Calendar"),
                            ("outlook", "Outlook Calendar"),
                            ("ics", "iCal Feed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("error", "Sync Error"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("calendar_id", models.CharField(blank=True, max_length=255)),
                ("ical_url", models.URLField(blank=True, max_length=500)),
                ("auto_sync", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_calendar_syncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conference_calendar_syncs",
                "unique_together": {("user", "calendar_type")},
            },
        ),
        migrations.CreateModel(
            name="ConferenceScheduleOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "override_type",
                    models.CharField(
                        choices=[
                            ("early_close", "Early Closure"),
                            ("late_open", "Late Opening"),
                            ("no_conferences", "No Conferences"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conference_schedule_overrides",
                        to="auth_service.school",
                    ),
                ),
            ],
            options={
                "db_table": "conference_schedule_overrides",
                "unique_together": {("school", "date")},
            },
        ),
        migrations.CreateModel(
            name="RecurringConferenceParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recurring_conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="conferences.recurringconference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_conference_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recurring_conference_participants",
                "unique_together": {("recurring_conference", "user")},
            },
        ),
    ]
